// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BooleanDisplay: typeof import('./theme/components/BooleanDisplay.vue')['default']
    CarbonCheckmark: typeof import('~icons/carbon/checkmark')['default']
    CarbonError: typeof import('~icons/carbon/error')['default']
    Changelog: typeof import('./theme/components/Changelog.vue')['default']
    Contributors: typeof import('./theme/components/Contributors.vue')['default']
    DemoContainer: typeof import('./theme/components/DemoContainer.vue')['default']
    FunctionBadge: typeof import('./theme/components/FunctionBadge.vue')['default']
    FunctionInfo: typeof import('./theme/components/FunctionInfo.vue')['default']
    FunctionsList: typeof import('./theme/components/FunctionsList.vue')['default']
    Home: typeof import('./theme/components/Home.vue')['default']
    HomeFeatures: typeof import('./theme/components/HomeFeatures.vue')['default']
    HomeFooter: typeof import('./theme/components/HomeFooter.vue')['default']
    HomeHero: typeof import('./theme/components/HomeHero.vue')['default']
    LearnMoreComponents: typeof import('./theme/components/LearnMoreComponents.vue')['default']
    Note: typeof import('./theme/components/Note.vue')['default']
    ReloadPrompt: typeof import('./theme/components/ReloadPrompt.vue')['default']
  }
}

export { }
