/**
 * Generated by tsnapi — public API snapshot of `@vueuse/firebase`
 */
// #region Other
export { FirebaseDocRef }
export { useAuth }
export { UseFirebaseAuthOptions }
export { useFirestore }
export { UseFirestoreOptions }
export { useRTDB }
export { UseRTDBOptions }
// #endregion