/**
 * Generated by tsnapi — public API snapshot of `@vueuse/firebase/useAuth`
 */
// #region Interfaces
export interface UseFirebaseAuthOptions {
  isAuthenticated: ComputedRef<boolean>;
  user: Ref<User | null>;
}
// #endregion

// #region Functions
export declare function useAuth(_: Auth): {
  isAuthenticated: ComputedRef<boolean>;
  user: Ref<{
    readonly emailVerified: boolean;
    readonly isAnonymous: boolean;
    readonly metadata: {
      readonly creationTime?: string | undefined;
      readonly lastSignInTime?: string | undefined;
    };
    readonly providerData: {
      readonly displayName: string | null;
      readonly email: string | null;
      readonly phoneNumber: string | null;
      readonly photoURL: string | null;
      readonly providerId: string;
      readonly uid: string;
    }[];
    readonly refreshToken: string;
    readonly tenantId: string | null;
    delete: () => Promise<void>;
    getIdToken: (forceRefresh?: boolean) => Promise<string>;
    getIdTokenResult: (forceRefresh?: boolean) => Promise<_$firebase_auth0.IdTokenResult>;
    reload: () => Promise<void>;
    toJSON: () => object;
    readonly displayName: string | null;
    readonly email: string | null;
    readonly phoneNumber: string | null;
    readonly photoURL: string | null;
    readonly providerId: string;
    readonly uid: string;
  } | null, User | {
    readonly emailVerified: boolean;
    readonly isAnonymous: boolean;
    readonly metadata: {
      readonly creationTime?: string | undefined;
      readonly lastSignInTime?: string | undefined;
    };
    readonly providerData: {
      readonly displayName: string | null;
      readonly email: string | null;
      readonly phoneNumber: string | null;
      readonly photoURL: string | null;
      readonly providerId: string;
      readonly uid: string;
    }[];
    readonly refreshToken: string;
    readonly tenantId: string | null;
    delete: () => Promise<void>;
    getIdToken: (forceRefresh?: boolean) => Promise<string>;
    getIdTokenResult: (forceRefresh?: boolean) => Promise<_$firebase_auth0.IdTokenResult>;
    reload: () => Promise<void>;
    toJSON: () => object;
    readonly displayName: string | null;
    readonly email: string | null;
    readonly phoneNumber: string | null;
    readonly photoURL: string | null;
    readonly providerId: string;
    readonly uid: string;
  } | null>;
};
// #endregion