/**
 * Generated by tsnapi — public API snapshot of `@vueuse/firebase/useFirestore` */
// Interfaces
export interface UseFirestoreOptions {
  errorHandler?: (_: Error) => void;
  autoDispose?: boolean | number;
}

// Types
export type FirebaseDocRef<T> = Query<T> | DocumentReference<T>;

// Functions
export declare function useFirestore<T extends DocumentData>(_: MaybeRef<Query<T> | Falsy>, _?: T[], _?: UseFirestoreOptions): Ref<T[] | undefined>;