/**
 * Generated by tsnapi — public API snapshot of `@vueuse/firebase/useFirestore`
 */
// #region Interfaces
export interface UseFirestoreOptions {
  errorHandler?: (_: Error) => void;
  autoDispose?: boolean | number;
}
// #endregion

// #region Types
export type FirebaseDocRef<T> = Query<T> | DocumentReference<T>;
// #endregion

// #region Functions
export declare function useFirestore<T extends DocumentData>(_: MaybeRef<Query<T> | Falsy>, _?: T[], _?: UseFirestoreOptions): Ref<T[] | undefined>;
// #endregion