/**
 * Generated by tsnapi — public API snapshot of `@vueuse/firebase/useRTDB` */
// Interfaces
export interface UseRTDBOptions {
  errorHandler?: (_: Error) => void;
  autoDispose?: boolean;
}

// Functions
export declare function useRTDB<T = any>(_: DatabaseReference, _?: UseRTDBOptions): Ref<T | undefined, T | undefined>;