/**
 * Generated by tsnapi — public API snapshot of `@vueuse/nuxt`
 */
// #region Interfaces
export interface VueUseNuxtOptions {
  autoImports?: boolean;
  ssrHandlers?: boolean;
}
// #endregion

// #region Default Export
declare const _default: _$_nuxt_schema0.NuxtModule<VueUseNuxtOptions, VueUseNuxtOptions, false>;
export default _default
// #endregion