/**
 * Generated by tsnapi — public API snapshot of `@vueuse/nuxt/module`
 */
// #region Interfaces
export interface VueUseNuxtOptions {
  autoImports?: boolean;
  ssrHandlers?: boolean;
}
// #endregion

// #region Types
export type ModuleOptions = VueUseNuxtOptions;
// #endregion

// #region Default Export
declare const _default: import("@nuxt/schema").NuxtModule<VueUseNuxtOptions, VueUseNuxtOptions, false>;
export default _default
// #endregion