packages:
  - packages/*
  - '!playgrounds'
catalog:
  '@antfu/eslint-config': ^3.8.0
  '@antfu/ni': ^0.23.0
  '@iconify/json': ^2.2.263
  '@nuxt/kit': ^3.13.2
  '@nuxt/schema': ^3.13.2
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-replace': ^5.0.7
  '@shikijs/vitepress-twoslash': ^1.22.1
  '@type-challenges/utils': ^0.1.1
  '@types/fs-extra': ^11.0.4
  '@types/js-yaml': ^4.0.9
  '@types/md5': ^2.3.5
  '@types/node': ^22.7.9
  '@types/nprogress': ^0.2.3
  '@types/qrcode': ^1.5.5
  '@types/remove-markdown': ^0.3.4
  '@types/semver': ^7.5.8
  '@types/sortablejs': ^1.15.8
  '@types/web-bluetooth': ^0.0.20
  '@typescript-eslint/utils': ^8.11.0
  '@vite-pwa/vitepress': ^0.5.3
  '@vitest/coverage-v8': ^2.1.3
  '@vitest/ui': ^2.1.3
  '@vue/compiler-sfc': ^3.5.12
  '@vue/test-utils': ^2.4.6
  async-validator: ^4.2.5
  axios: ^1.7.7
  bumpp: ^9.7.1
  change-case: ^5.4.4
  consola: ^3.2.3
  drauu: ^0.4.1
  electron: ^13.1.0
  esbuild-register: ^3.6.0
  eslint: ^9.13.0
  eslint-plugin-format: ^0.1.2
  esno: ^4.8.0
  export-size: ^0.7.0
  fake-indexeddb: ^6.0.0
  fast-glob: ^3.3.2
  firebase: ^10.14.1
  focus-trap: ^7.6.0
  fs-extra: ^11.2.0
  fuse.js: ^7.0.0
  google-font-installer: ^1.2.0
  gray-matter: ^4.0.3
  idb-keyval: ^6.2.1
  js-yaml: ^4.1.0
  jsdom: ^25.0.1
  jwt-decode: ^4.0.0
  lint-staged: ^15.2.10
  local-pkg: ^0.5.0
  magic-string: ^0.30.12
  markdown-table: ^3.0.4
  md5: ^2.3.0
  msw: ^2.3.0
  node-fetch: ^3.3.2
  node-fetch-native: ^1.6.4
  nprogress: ^0.2.0
  nuxt: ^3.13.2
  ofetch: ^1.4.1
  pnpm: ^9.12.2
  postcss: ^8.4.47
  postcss-nested: ^6.2.0
  prettier: ^3.3.3
  prism-theme-vars: ^0.2.5
  qrcode: ^1.5.4
  remove-markdown: ^0.5.5
  rimraf: ^6.0.1
  rollup: ^4.24.0
  rollup-plugin-dts: ^6.1.1
  rollup-plugin-esbuild: ^6.1.1
  rollup-plugin-pure: ^0.2.1
  rxjs: ^6.6.7
  sharp: ^0.33.5
  simple-git: ^3.27.0
  simple-git-hooks: ^2.11.1
  sortablejs: ^1.15.3
  taze: ^0.16.9
  typescript: ^5.6.3
  unimport: ^3.13.1
  universal-cookie: ^7.2.1
  unocss: ^0.62.4
  unplugin-icons: ^0.19.3
  unplugin-vue-components: ^0.27.4
  vite: ^5.4.10
  vite-plugin-inspect: ^0.8.7
  vite-plugin-pwa: ^0.20.5
  vitepress: ^1.4.1
  vitest: ^2.1.3
  vue: ^3.5.12
  vue-demi: '>=0.14.10'
  vue-router: ^4.4.5
  vue2: npm:vue@^2.7.14
