packages:
  - packages/*
  - '!playgrounds'

catalogs:
  dev:
    '@antfu/eslint-config': ^4.13.2
    '@antfu/ni': ^25.0.0
    '@iconify/json': ^2.2.342
    '@rollup/plugin-json': ^6.1.0
    '@rollup/plugin-replace': ^6.0.2
    '@vitejs/plugin-vue': ^5.2.4
    '@vue/compiler-sfc': ^3.5.15
    bumpp: ^10.1.1
    consola: ^3.4.2
    eslint: ^9.27.0
    eslint-factory: ^0.1.2
    eslint-plugin-format: ^1.0.1
    eslint-plugin-unimport: ^0.1.2
    export-size: ^0.7.0
    jsdom: ^26.1.0
    lint-staged: ^16.0.0
    nuxt: ^3.17.4
    ofetch: ^1.4.1
    pnpm: ^10.11.0
    postcss: ^8.5.3
    postcss-nested: ^7.0.2
    prettier: ^3.5.3
    rollup: ^4.41.1
    rollup-plugin-dts: ^6.2.1
    rollup-plugin-esbuild: ^6.2.1
    rollup-plugin-pure: ^0.4.0
    sharp: ^0.34.2
    simple-git: ^3.27.0
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    tinyglobby: ^0.2.14
    tsx: ^4.19.4
    typescript: ^5.8.3
    unimport: ^5.0.1
    unocss: ^66.1.2
    vite: ^6.3.5
    vite-plugin-inspect: ^11.1.0
    vue: ^3.5.15
    vue-tsc: ^2.2.10
  docs:
    '@shikijs/vitepress-twoslash': ^3.4.2
    '@vite-pwa/vitepress': ^1.0.0
    '@vue/repl': ^4.5.1
    google-font-installer: ^1.2.0
    gray-matter: ^4.0.3
    markdown-table: ^3.0.4
    md5: ^2.3.0
    remove-markdown: ^0.6.2
    unplugin-icons: ^22.1.0
    unplugin-vue-components: ^28.7.0
    vite-plugin-pwa: ^1.0.0
    vitepress: ^2.0.0-alpha.5
    yaml: ^2.8.0
  integrations:
    '@nuxt/kit': ^3.17.4
    '@nuxt/schema': ^3.17.4
    async-validator: ^4.2.5
    axios: ^1.9.0
    change-case: ^5.4.4
    drauu: ^0.4.3
    electron: ^13.1.0
    firebase: ^10.14.1
    focus-trap: ^7.6.4
    fuse.js: ^7.1.0
    idb-keyval: ^6.2.2
    jwt-decode: ^4.0.0
    local-pkg: ^1.1.1
    nprogress: ^0.2.0
    qrcode: ^1.5.4
    rxjs: ^6.6.7
    sortablejs: ^1.15.6
    universal-cookie: ^7.2.2
    vue-router: ^4.5.1
  test:
    '@arethetypeswrong/cli': ^0.18.1
    '@vitest/browser': ^3.1.4
    '@vitest/coverage-v8': ^3.1.4
    '@vitest/ui': ^3.1.4
    '@vue/test-utils': ^2.4.6
    fake-indexeddb: ^6.0.1
    msw: ^2.3.0
    playwright: 1.49.0
    vitest: ^3.1.4
    vitest-browser-vue: ^0.2.0
    vitest-package-exports: ^0.1.1
  types:
    '@type-challenges/utils': ^0.1.1
    '@types/md5': ^2.3.5
    '@types/node': ^22.15.21
    '@types/nprogress': ^0.2.3
    '@types/qrcode': ^1.5.5
    '@types/remove-markdown': ^0.3.4
    '@types/semver': ^7.7.0
    '@types/sortablejs': ^1.15.8
    '@types/web-bluetooth': ^0.0.21

neverBuiltDependencies:
  - electron
