packages:
  - packages/*
  - '!playgrounds'

patchedDependencies:
  google-font-installer@1.2.0: patches/google-font-installer@1.2.0.patch

catalogs:
  dev:
    '@antfu/eslint-config': ^6.0.0
    '@antfu/ni': ^27.0.0
    '@iconify/json': ^2.2.398
    '@vitejs/plugin-vue': ^6.0.1
    '@vue/compiler-sfc': ^3.5.22
    bumpp: ^10.3.1
    consola: ^3.4.2
    eslint: ^9.38.0
    eslint-factory: ^0.1.2
    eslint-plugin-format: ^1.0.2
    eslint-plugin-unimport: ^0.1.2
    export-size: ^0.7.0
    lint-staged: ^16.2.5
    nuxt: ^4.1.3
    ofetch: ^1.4.1
    pnpm: ^10.19.0
    postcss: ^8.5.6
    postcss-nested: ^7.0.2
    prettier: ^3.6.2
    sharp: ^0.34.4
    simple-git: ^3.28.0
    simple-git-hooks: ^2.13.1
    taze: ^19.8.1
    tinyglobby: ^0.2.15
    tsdown: ^0.15.9
    tsx: ^4.20.6
    turbo: ^2.5.8
    typescript: ^5.9.3
    unimport: ^5.5.0
    unocss: ^66.5.4
    vite: ^8.0.0-beta.2
    vite-plugin-inspect: ^11.3.3
    vue: ^3.5.22
    vue-tsc: ^3.1.1
  docs:
    '@shikijs/vitepress-twoslash': ^3.13.0
    '@vite-pwa/vitepress': ^1.0.1
    '@vue/repl': ^4.7.0
    google-font-installer: ^1.2.0
    gray-matter: ^4.0.3
    markdown-table: ^3.0.4
    md5: ^2.3.0
    remove-markdown: ^0.6.2
    unplugin-icons: ^22.5.0
    unplugin-vue-components: ^30.0.0
    vite-plugin-pwa: ^1.1.0
    vitepress: ^2.0.0-alpha.12
    yaml: ^2.8.1
  integrations:
    '@nuxt/kit': ^4.1.3
    '@nuxt/schema': ^4.1.3
    async-validator: ^4.2.5
    axios: ^1.12.2
    change-case: ^5.4.4
    drauu: ^0.4.3
    electron: ^13.1.0
    firebase: ^12.4.0
    focus-trap: ^7.6.5
    fuse.js: ^7.1.0
    idb-keyval: ^6.2.2
    jwt-decode: ^4.0.0
    local-pkg: ^1.1.2
    nprogress: ^0.2.0
    qrcode: ^1.5.4
    rxjs: ^6.6.7
    sortablejs: ^1.15.6
    universal-cookie: ^8.0.1
    vue-router: ^4.6.3
  test:
    '@arethetypeswrong/cli': ^0.18.2
    '@vitest/browser-playwright': ^4.0.8
    '@vitest/coverage-v8': ^4.0.8
    '@vitest/ui': ^4.0.8
    '@vue/test-utils': ^2.4.6
    fake-indexeddb: ^6.2.4
    jsdom: ^27.1.0
    msw: ^2.12.4
    playwright: 1.49.0
    vitest: ^4.0.8
    vitest-browser-vue: ^2.0.1
    vitest-package-exports: ^0.1.1
  types:
    '@type-challenges/utils': ^0.1.1
    '@types/md5': ^2.3.6
    '@types/node': ^24.9.1
    '@types/nprogress': ^0.2.3
    '@types/qrcode': ^1.5.5
    '@types/remove-markdown': ^0.3.4
    '@types/semver': ^7.7.1
    '@types/sortablejs': ^1.15.8
    '@types/web-bluetooth': ^0.0.21

neverBuiltDependencies:
  - electron

shamefullyHoist: true
shellEmulator: true
sideEffectsCache: false
strictPeerDependencies: false
