packages:
  - packages/*
  - '!playgrounds'
catalog:
  '@antfu/eslint-config': ^3.13.0
  '@antfu/ni': ^23.2.0
  '@iconify/json': ^2.2.293
  '@nuxt/kit': ^3.15.1
  '@nuxt/schema': ^3.15.1
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-replace': ^6.0.2
  '@shikijs/vitepress-twoslash': ^1.26.1
  '@type-challenges/utils': ^0.1.1
  '@types/js-yaml': ^4.0.9
  '@types/md5': ^2.3.5
  '@types/node': ^22.10.5
  '@types/nprogress': ^0.2.3
  '@types/qrcode': ^1.5.5
  '@types/remove-markdown': ^0.3.4
  '@types/semver': ^7.5.8
  '@types/sortablejs': ^1.15.8
  '@types/web-bluetooth': ^0.0.20
  '@typescript-eslint/utils': ^8.19.1
  '@vite-pwa/vitepress': ^0.5.3
  '@vitejs/plugin-vue': ^5.2.1
  '@vitest/browser': ^2.1.8
  '@vitest/coverage-v8': ^2.1.8
  '@vitest/ui': ^2.1.8
  '@vue/compiler-sfc': ^3.5.13
  '@vue/test-utils': ^2.4.6
  async-validator: ^4.2.5
  axios: ^1.7.9
  bumpp: ^9.10.0
  change-case: ^5.4.4
  consola: ^3.3.3
  drauu: ^0.4.2
  electron: ^13.1.0
  esbuild-register: ^3.6.0
  eslint: ^9.17.0
  eslint-plugin-format: ^1.0.1
  export-size: ^0.7.0
  fake-indexeddb: ^6.0.0
  firebase: ^10.14.1
  focus-trap: ^7.6.2
  fuse.js: ^7.0.0
  google-font-installer: ^1.2.0
  gray-matter: ^4.0.3
  idb-keyval: ^6.2.1
  js-yaml: ^4.1.0
  jsdom: ^26.0.0
  jwt-decode: ^4.0.0
  lint-staged: ^15.3.0
  local-pkg: ^1.0.0
  magic-string: ^0.30.17
  markdown-table: ^3.0.4
  md5: ^2.3.0
  msw: ^2.3.0
  node-fetch: ^3.3.2
  node-fetch-native: ^1.6.4
  nprogress: ^0.2.0
  nuxt: ^3.15.1
  ofetch: ^1.4.1
  playwright: ^1.49.1
  pnpm: ^9.15.3
  postcss: ^8.4.49
  postcss-nested: ^7.0.2
  prettier: ^3.4.2
  prism-theme-vars: ^0.2.5
  qrcode: ^1.5.4
  remove-markdown: ^0.6.0
  rimraf: ^6.0.1
  rollup: ^4.30.1
  rollup-plugin-dts: ^6.1.1
  rollup-plugin-esbuild: ^6.1.1
  rollup-plugin-pure: ^0.2.1
  rxjs: ^6.6.7
  sharp: ^0.33.5
  simple-git: ^3.27.0
  simple-git-hooks: ^2.11.1
  sortablejs: ^1.15.6
  taze: ^18.1.0
  tinyglobby: ^0.2.10
  tsx: ^4.19.2
  typescript: ^5.7.3
  unimport: ^3.14.5
  universal-cookie: ^7.2.2
  unocss: ^0.65.4
  unplugin-icons: ^22.0.0
  unplugin-vue-components: ^28.0.0
  vite: ^6.0.7
  vite-plugin-inspect: ^10.0.6
  vite-plugin-pwa: ^0.21.1
  vitepress: ^1.5.0
  vitest: ^2.1.8
  vitest-browser-vue: ^0.0.1
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.0
