packages:
  - packages/*
  - '!playgrounds'

catalogs:
  dev:
    '@antfu/eslint-config': ^5.2.1
    '@antfu/ni': ^25.0.0
    '@iconify/json': ^2.2.380
    '@vitejs/plugin-vue': ^6.0.1
    '@vue/compiler-sfc': ^3.5.20
    bumpp: ^10.2.3
    consola: ^3.4.2
    eslint: ^9.34.0
    eslint-factory: ^0.1.2
    eslint-plugin-format: ^1.0.1
    eslint-plugin-unimport: ^0.1.2
    export-size: ^0.7.0
    jsdom: ^26.1.0
    lint-staged: ^16.1.5
    nuxt: ^3.18.1
    ofetch: ^1.4.1
    pnpm: ^10.15.1
    postcss: ^8.5.6
    postcss-nested: ^7.0.2
    prettier: ^3.6.2
    rolldown-vite: ^7.1.5
    sharp: ^0.34.3
    simple-git: ^3.28.0
    simple-git-hooks: ^2.13.1
    taze: ^19.4.0
    tinyglobby: ^0.2.14
    tsdown: ^0.14.2
    tsx: ^4.20.5
    typescript: ^5.9.2
    unimport: ^5.2.0
    unocss: ^66.5.0
    vite: ^7.1.4
    vite-plugin-inspect: ^11.3.3
    vue: ^3.5.20
    vue-tsc: ^3.0.6
  docs:
    '@shikijs/vitepress-twoslash': ^3.12.1
    '@vite-pwa/vitepress': ^1.0.0
    '@vue/repl': ^4.6.3
    google-font-installer: ^1.2.0
    gray-matter: ^4.0.3
    markdown-table: ^3.0.4
    md5: ^2.3.0
    remove-markdown: ^0.6.2
    unplugin-icons: ^22.2.0
    unplugin-vue-components: ^29.0.0
    vite-plugin-pwa: ^1.0.3
    vitepress: ^2.0.0-alpha.12
    yaml: ^2.8.1
  integrations:
    '@nuxt/kit': ^3.18.1
    '@nuxt/schema': ^3.18.1
    async-validator: ^4.2.5
    axios: ^1.11.0
    change-case: ^5.4.4
    drauu: ^0.4.3
    electron: ^13.1.0
    firebase: ^10.14.1
    focus-trap: ^7.6.5
    fuse.js: ^7.1.0
    idb-keyval: ^6.2.2
    jwt-decode: ^4.0.0
    local-pkg: ^1.1.2
    nprogress: ^0.2.0
    qrcode: ^1.5.4
    rxjs: ^6.6.7
    sortablejs: ^1.15.6
    universal-cookie: ^8.0.1
    vue-router: ^4.5.1
  test:
    '@arethetypeswrong/cli': ^0.18.2
    '@vitest/browser': ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    '@vue/test-utils': ^2.4.6
    fake-indexeddb: ^6.2.2
    msw: ^2.3.0
    playwright: 1.49.0
    vitest: ^3.2.4
    vitest-browser-vue: ^1.1.0
    vitest-package-exports: ^0.1.1
  types:
    '@type-challenges/utils': ^0.1.1
    '@types/md5': ^2.3.5
    '@types/node': ^24.3.0
    '@types/nprogress': ^0.2.3
    '@types/qrcode': ^1.5.5
    '@types/remove-markdown': ^0.3.4
    '@types/semver': ^7.7.0
    '@types/sortablejs': ^1.15.8
    '@types/web-bluetooth': ^0.0.21

neverBuiltDependencies:
  - electron
