shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*
  - '!playgrounds'

patchedDependencies:
  google-font-installer@1.2.0: patches/google-font-installer@1.2.0.patch

catalogs:
  dev:
    '@antfu/eslint-config': ^8.2.0
    '@antfu/ni': ^30.0.0
    '@iconify/json': ^2.2.463
    '@vitejs/plugin-vue': ^6.0.6
    '@vue/compiler-sfc': ^3.5.32
    bumpp: ^11.0.1
    chokidar: ^5.0.0
    consola: ^3.4.2
    eslint: ^10.2.0
    eslint-factory: ^0.1.2
    eslint-plugin-format: ^2.0.1
    eslint-plugin-unimport: ^1.0.0
    export-size: ^0.8.0
    lint-staged: ^16.4.0
    nuxt: ^4.4.2
    ofetch: ^1.5.1
    pnpm: ^10.33.0
    postcss: ^8.5.10
    postcss-nested: ^7.0.2
    prettier: ^3.8.3
    semver: ^7.7.4
    sharp: ^0.34.5
    simple-git: ^3.36.0
    simple-git-hooks: ^2.13.1
    taze: ^19.11.0
    tinyglobby: ^0.2.16
    tsdown: ^0.21.9
    tsdown-stale-guard: ^0.1.1
    tsx: ^4.21.0
    turbo: ^2.9.6
    typescript: ^6.0.2
    unimport: ^6.1.0
    unocss: ^66.6.8
    vite: ^8.0.8
    vite-plugin-inspect: ^11.3.3
    vue: ^3.5.27
    vue-tsc: ^3.2.6
  docs:
    '@shikijs/vitepress-twoslash': ^4.0.2
    '@vite-pwa/vitepress': ^1.1.0
    '@vue/repl': ^4.7.2
    google-font-installer: ^1.2.0
    gray-matter: ^4.0.3
    markdown-table: ^3.0.4
    md5: ^2.3.0
    remove-markdown: ^0.6.3
    unplugin-icons: ^23.0.1
    unplugin-vue-components: ^32.0.0
    vite-plugin-pwa: ^1.2.0
    vitepress: ^2.0.0-alpha.17
    yaml: ^2.8.3
  integrations:
    '@nuxt/kit': ^4.4.2
    '@nuxt/schema': ^4.4.2
    async-validator: ^4.2.5
    axios: ^1.15.0
    change-case: ^5.4.4
    drauu: ^1.0.0
    electron: ^13.1.0
    firebase: ^12.12.0
    focus-trap: ^8.0.1
    fuse.js: ^7.3.0
    idb-keyval: ^6.2.2
    jwt-decode: ^4.0.0
    local-pkg: ^1.1.2
    nprogress: ^0.2.0
    qrcode: ^1.5.4
    rxjs: ^6.6.7
    sortablejs: ^1.15.7
    universal-cookie: ^8.1.0
    vue-router: ^5.0.4
  test:
    '@arethetypeswrong/core': ^0.18.2
    '@vitest/browser-playwright': ^4.1.4
    '@vitest/coverage-v8': ^4.1.4
    '@vitest/ui': ^4.1.4
    '@vue/test-utils': ^2.4.6
    fake-indexeddb: ^6.2.5
    jsdom: ^29.0.2
    msw: ^2.13.3
    playwright: 1.49.0
    tsnapi: ^0.3.2
    vitest: ^4.1.4
    vitest-browser-vue: ^2.1.0
  types:
    '@type-challenges/utils': ^0.1.1
    '@types/md5': ^2.3.6
    '@types/node': ^25.6.0
    '@types/nprogress': ^0.2.3
    '@types/qrcode': ^1.5.6
    '@types/remove-markdown': ^0.3.4
    '@types/semver': ^7.7.1
    '@types/sortablejs': ^1.15.9
    '@types/web-bluetooth': ^0.0.21

neverBuiltDependencies:
  - electron

sideEffectsCache: false
strictPeerDependencies: false
