/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useAsyncValidator/component` */
// Interfaces
export interface UseAsyncValidatorProps {
  form: Record<string, any>;
  rules: Rules;
  options?: UseAsyncValidatorOptions;
}

// Variables
export declare const UseAsyncValidator: vue.DefineSetupFnComponent<UseAsyncValidatorProps, Record<string, never>, SlotsType<UseAsyncValidatorSlots>, UseAsyncValidatorProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, vue.PublicProps>;