/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useAsyncValidator/component`
 */
// #region Interfaces
export interface UseAsyncValidatorProps {
  form: Record<string, any>;
  rules: Rules;
  options?: UseAsyncValidatorOptions;
}
// #endregion

// #region Variables
export declare const UseAsyncValidator: _$vue.DefineSetupFnComponent<UseAsyncValidatorProps, Record<string, never>, SlotsType<UseAsyncValidatorSlots>, UseAsyncValidatorProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, _$vue.PublicProps>;
// #endregion