/**
 * Generated by tsnapi — public API snapshot of `@vueuse/shared`
 */
// #region Interfaces
export interface ComputedRefWithControl<T> extends ComputedRef<T>, ComputedWithControlRefExtra {}
export interface ComputedWithControlRefExtra {
  trigger: () => void;
}
export interface ConfigurableEventFilter {
  eventFilter?: EventFilter;
}
export interface ConfigurableFlush {
  flush?: WatchOptionFlush;
}
export interface ConfigurableFlushSync {
  flush?: WatchOptionFlush;
}
export interface ControlledRefOptions<T> {
  onBeforeChange?: (_: T, _: T) => void | boolean;
  onChanged?: (_: T, _: T) => void;
}
export interface CreateInjectionStateOptions<Return> {
  injectionKey?: string | InjectionKey<Return>;
  defaultValue?: Return;
}
export interface DebounceFilterOptions {
  maxWait?: MaybeRefOrGetter<number>;
  rejectOnCancel?: boolean;
}
export interface EventHook<T = any> {
  on: EventHookOn<T>;
  off: EventHookOff<T>;
  trigger: EventHookTrigger<T>;
  clear: () => void;
}
export interface ExtendRefOptions<Unwrap extends boolean = boolean> {
  enumerable?: boolean;
  unwrap?: Unwrap;
}
export interface FunctionWrapperOptions<Args extends any[] = any[], This = any> {
  fn: FunctionArgs<Args, This>;
  args: Args;
  thisArg: This;
}
export interface ManualResetRefReturn<T> extends Ref<T> {
  reset: Fn;
}
export interface Pausable {
  readonly isActive: Readonly<ShallowRef<boolean>>;
  pause: Fn;
  resume: Fn;
}
export interface PausableFilterOptions {
  initialState?: 'active' | 'paused';
}
export interface ReactifyObjectOptions<T extends boolean> extends ReactifyOptions<T> {
  includeOwnProperties?: boolean;
}
export interface ReactifyOptions<T extends boolean> {
  computedGetter?: T;
}
export interface SingletonPromiseReturn<T> {
  (): Promise<T>;
  reset: () => Promise<void>;
}
export interface Stoppable<StartFnArgs extends any[] = any[]> {
  readonly isPending: Readonly<Ref<boolean>>;
  stop: Fn;
  start: (..._: StartFnArgs) => void;
}
export interface SyncRefsOptions extends ConfigurableFlushSync {
  deep?: boolean;
  immediate?: boolean;
}
export interface ThrottleFilterOptions {
  delay: MaybeRefOrGetter<number>;
  trailing?: boolean;
  leading?: boolean;
  rejectOnCancel?: boolean;
}
export interface ToRefsOptions {
  replaceRef?: MaybeRefOrGetter<boolean>;
}
export interface UntilArrayInstance<T> extends UntilBaseInstance<T> {
  readonly not: UntilArrayInstance<T>;
  toContains: (_: MaybeRefOrGetter<ElementOf<ShallowUnwrapRef<T>>>, _?: UntilToMatchOptions) => Promise<T>;
}
export interface UntilBaseInstance<T, Not extends boolean = false> {
  toMatch: (<U extends T = T>(_: (_: T) => v is U, _?: UntilToMatchOptions) => Not extends true ? Promise<Exclude<T, U>> : Promise<U>) & ((_: (_: T) => boolean, _?: UntilToMatchOptions) => Promise<T>);
  changed: (_?: UntilToMatchOptions) => Promise<T>;
  changedTimes: (_?: number, _?: UntilToMatchOptions) => Promise<T>;
}
export interface UntilToMatchOptions extends ConfigurableFlushSync {
  timeout?: number;
  throwOnTimeout?: boolean;
  deep?: WatchOptions['deep'];
}
export interface UntilValueInstance<T, Not extends boolean = false> extends UntilBaseInstance<T, Not> {
  readonly not: UntilValueInstance<T, Not extends true ? false : true>;
  toBe: <P = T>(_: MaybeRefOrGetter<P>, _?: UntilToMatchOptions) => Not extends true ? Promise<T> : Promise<P>;
  toBeTruthy: (_?: UntilToMatchOptions) => Not extends true ? Promise<T & Falsy> : Promise<Exclude<T, Falsy>>;
  toBeNull: (_?: UntilToMatchOptions) => Not extends true ? Promise<Exclude<T, null>> : Promise<null>;
  toBeUndefined: (_?: UntilToMatchOptions) => Not extends true ? Promise<Exclude<T, undefined>> : Promise<undefined>;
  toBeNaN: (_?: UntilToMatchOptions) => Promise<T>;
}
export interface UseArrayDifferenceOptions {
  symmetric?: boolean;
}
export interface UseArrayIncludesOptions<T, V> {
  fromIndex?: number;
  comparator?: UseArrayIncludesComparatorFn<T, V> | keyof T;
}
export interface UseCounterOptions {
  min?: number;
  max?: number;
}
export interface UseCounterReturn {
  readonly count: Readonly<Ref<number>>;
  inc: (_?: number) => void;
  dec: (_?: number) => void;
  get: () => number;
  set: (_: number) => void;
  reset: (_?: number) => number;
}
export interface UseDateFormatOptions {
  locales?: MaybeRefOrGetter<Intl.LocalesArgument>;
  customMeridiem?: (_: number, _: number, _?: boolean, _?: boolean) => string;
}
export interface UseIntervalControls {
  counter: ShallowRef<number>;
  reset: () => void;
}
export interface UseIntervalFnOptions {
  immediate?: boolean;
  immediateCallback?: boolean;
}
export interface UseIntervalOptions<Controls extends boolean> {
  controls?: Controls;
  immediate?: boolean;
  callback?: (_: number) => void;
}
export interface UseLastChangedOptions<Immediate extends boolean, InitialValue extends number | null | undefined = undefined> extends WatchOptions<Immediate> {
  initialValue?: InitialValue;
}
export interface UseTimeoutFnOptions {
  immediate?: boolean;
  immediateCallback?: boolean;
}
export interface UseTimeoutOptions<Controls extends boolean> extends UseTimeoutFnOptions {
  controls?: Controls;
  callback?: Fn;
}
export interface UseToggleOptions<Truthy, Falsy> {
  truthyValue?: MaybeRefOrGetter<Truthy>;
  falsyValue?: MaybeRefOrGetter<Falsy>;
}
export interface UseToNumberOptions {
  method?: 'parseFloat' | 'parseInt' | ((_: string | number) => number);
  radix?: number;
  nanToZero?: boolean;
}
export interface WatchAtMostOptions<Immediate> extends WatchWithFilterOptions<Immediate> {
  count: MaybeRefOrGetter<number>;
}
export interface WatchAtMostReturn {
  stop: WatchStopHandle;
  pause: () => void;
  resume: () => void;
  count: ShallowRef<number>;
}
export interface WatchDebouncedOptions<Immediate> extends WatchOptions<Immediate>, DebounceFilterOptions {
  debounce?: MaybeRefOrGetter<number>;
}
export interface WatchIgnorableReturn {
  ignoreUpdates: IgnoredUpdater;
  ignorePrevAsyncUpdates: IgnoredPrevAsyncUpdates;
  stop: WatchStopHandle;
}
export interface WatchPausableReturn extends Pausable {
  stop: WatchStopHandle;
}
export interface WatchThrottledOptions<Immediate> extends WatchOptions<Immediate> {
  throttle?: MaybeRefOrGetter<number>;
  trailing?: boolean;
  leading?: boolean;
}
export interface WatchTriggerableReturn<FnReturnT = void> extends WatchIgnorableReturn {
  trigger: () => FnReturnT;
}
export interface WatchWithFilterOptions<Immediate> extends WatchOptions<Immediate>, ConfigurableEventFilter {}
export interface WheneverOptions<Immediate = boolean> extends WatchOptions<Immediate> {
  once?: boolean;
}
export interface WritableComputedRefWithControl<T> extends WritableComputedRef<T>, ComputedWithControlRefExtra {}
// #endregion

// #region Types
export type AnyFn = (..._: any[]) => any;
export type ArgumentsType<T> = T extends ((...args: infer U) => any) ? U : never;
export type Arrayable<T> = T[] | T;
export type Awaitable<T> = Promise<T> | T;
export type Awaited<T> = T extends null | undefined ? T : T extends object & {
  then: (onfulfilled: infer F, ...args: infer _) => any;
} ? F extends ((value: infer V, ...args: infer _) => any) ? Awaited<V> : never : T;
export type ComputedEagerOptions = WatchOptionsBase;
export type ComputedEagerReturn<T = any> = Readonly<ShallowRef<T>>;
export type ComputedWithControlRef<T = any> = ComputedRefWithControl<T> | WritableComputedRefWithControl<T>;
export type CreateGlobalStateReturn<Fn extends AnyFn = AnyFn> = Fn;
export type CreateInjectionStateReturn<Arguments extends Array<any>, ProvideReturn, InjectReturn> = Readonly<[
useProvidingState: (...args: Arguments) => ProvideReturn,
useInjectedState: () => InjectReturn]>;
export type CreateRefReturn<T = any, D extends boolean = false> = ShallowOrDeepRef<T, D>;
export type DateLike = Date | number | string | undefined;
export type DeepMaybeRef<T> = T extends Ref<infer V> ? MaybeRef<V> : T extends Array<any> | object ? { [K in keyof T]: DeepMaybeRef<T[K]> } : MaybeRef<T>;
export type ElementOf<T> = T extends (infer E)[] ? E : never;
export type EventFilter<Args extends any[] = any[], This = any, Invoke extends AnyFn = AnyFn> = (_: Invoke, _: FunctionWrapperOptions<Args, This>) => ReturnType<Invoke> | Promisify<ReturnType<Invoke>>;
export type EventHookOff<T = any> = (_: Callback<T>) => void;
export type EventHookOn<T = any> = (_: Callback<T>) => {
  off: () => void;
};
export type EventHookReturn<T> = EventHook<T>;
export type EventHookTrigger<T = any> = (..._: Parameters<Callback<T>>) => Promise<unknown[]>;
export type ExtendRefReturn<T = any> = Ref<T>;
export type Fn = () => void;
export type FunctionArgs<Args extends any[] = any[], Return = unknown> = (..._: Args) => Return;
export type IfAny<T, Y, N> = 0 extends (1 & T) ? Y : N;
export type IgnoredPrevAsyncUpdates = () => void;
export type IgnoredUpdater = (_: () => void) => void;
export type InstanceProxy = NonNullable<NonNullable<ReturnType<typeof getCurrentInstance>>['proxy']>;
export type IsAny<T> = IfAny<T, true, false>;
export type IsDefinedReturn = boolean;
export type MapOldSources<T, Immediate> = { [K in keyof T]: T[K] extends WatchSource<infer V> ? Immediate extends true ? V | undefined : V : never };
export type MapSources<T> = { [K in keyof T]: T[K] extends WatchSource<infer V> ? V : never };
export type Mutable<T> = { -readonly [P in keyof T]: T[P] };
export type Promisify<T> = Promise<Awaited<T>>;
export type PromisifyFn<T extends AnyFn> = (..._: ArgumentsType<T>) => Promisify<ReturnType<T>>;
export type ProvideLocalReturn = void;
export type Reactified<T, Computed extends boolean> = T extends ((...args: infer A) => infer R) ? (...args: { [K in keyof A]: Computed extends true ? MaybeRefOrGetter<A[K]> : MaybeRef<A[K]> }) => ComputedRef<R> : never;
export type ReactifyNested<T, Keys extends keyof T = keyof T, S extends boolean = true> = { [K in Keys]: T[K] extends AnyFn ? Reactified<T[K], S> : T[K] };
export type ReactifyObjectReturn<T, Keys extends keyof T, S extends boolean = true> = ReactifyNested<T, Keys, S>;
export type ReactifyReturn<T extends AnyFn = AnyFn, K extends boolean = true> = Reactified<T, K>;
export type ReactiveComputedReturn<T extends object> = UnwrapNestedRefs<T>;
export type ReactiveOmitPredicate<T> = (_: T[keyof T], _: keyof T) => boolean;
export type ReactiveOmitReturn<T extends object, K extends keyof T | undefined = undefined> = [K] extends [undefined] ? Partial<T> : Omit<T, Extract<K, keyof T>>;
export type ReactivePickPredicate<T> = (_: T[keyof T], _: keyof T) => boolean;
export type ReactivePickReturn<T extends object, K extends keyof T> = { [S in K]: UnwrapRef<T[S]> };
export type ReadonlyRefOrGetter<T> = ComputedRef<T> | (() => T);
export type RefAutoResetReturn<T = any> = Ref<T>;
export type RefDebouncedReturn<T = any> = Readonly<Ref<T>>;
export type RefThrottledReturn<T = any> = Ref<T>;
export type RemovableRef<T> = Ref<T, T | null | undefined>;
export type ShallowOrDeepRef<T = any, D extends boolean = false> = D extends true ? Ref<T> : ShallowRef<T>;
export type ShallowUnwrapRef<T> = T extends Ref<infer P> ? P : T;
export type SharedComposableReturn<T extends AnyFn = AnyFn> = T;
export type SyncRefOptions<L, R, D extends Direction> = ConfigurableFlushSync & {
  deep?: boolean;
  immediate?: boolean;
  direction?: D;
} & TransformType<D, L, R>;
export type TimerHandle = ReturnType<typeof setTimeout> | undefined;
export type ToggleFn = (_?: boolean) => void;
export type UseArrayDifferenceReturn<T = any> = ComputedRef<T[]>;
export type UseArrayEveryReturn = ComputedRef<boolean>;
export type UseArrayFilterReturn<T = any> = ComputedRef<T[]>;
export type UseArrayFindIndexReturn = ComputedRef<number>;
export type UseArrayFindLastReturn<T = any> = ComputedRef<T | undefined>;
export type UseArrayFindReturn<T = any> = ComputedRef<T | undefined>;
export type UseArrayIncludesComparatorFn<T, V> = ((_: T, _: V, _: number, _: MaybeRefOrGetter<T>[]) => boolean);
export type UseArrayIncludesReturn = ComputedRef<boolean>;
export type UseArrayJoinReturn = ComputedRef<string>;
export type UseArrayMapReturn<T = any> = ComputedRef<T[]>;
export type UseArrayReducer<PV, CV, R> = (_: PV, _: CV, _: number) => R;
export type UseArrayReduceReturn<T = any> = ComputedRef<T>;
export type UseArraySomeReturn = ComputedRef<boolean>;
export type UseArrayUniqueReturn<T = any> = ComputedRef<T[]>;
export type UseDateFormatReturn = ComputedRef<string>;
export type UseDebounceFnReturn<T extends FunctionArgs> = PromisifyFn<T>;
export type UseIntervalFnReturn = Pausable;
export type UseIntervalReturn = Readonly<ShallowRef<number>> | Readonly<UseIntervalControls & Pausable>;
export type UseLastChangedReturn = Readonly<ShallowRef<number | null>> | Readonly<ShallowRef<number>>;
export type UseTimeoutFnReturn<CallbackFn extends AnyFn> = Stoppable<Parameters<CallbackFn> | []>;
export type UseTimeoutReturn = ComputedRef<boolean> | {
  readonly ready: ComputedRef<boolean>;
} & Stoppable;
export type UseTimoutReturn = UseTimeoutReturn;
export type UseToggleReturn = [ShallowRef<boolean>, ToggleFn] | ToggleFn;
export declare type WatchArrayCallback<V = any, OV = any> = (_: V, _: OV, _: V, _: OV, _: (_: () => void) => void) => any;
export type WatchOptionFlush = WatchOptions['flush'];
export type WatchPausableOptions<Immediate> = WatchWithFilterOptions<Immediate> & PausableFilterOptions;
export type WatchTriggerableCallback<V = any, OV = any, R = void> = (_: V, _: OV, _: OnCleanup) => R;
// #endregion

// #region Functions
export declare function computedEager<T>(_: () => T, _?: ComputedEagerOptions): ComputedEagerReturn<T>;
export declare function computedWithControl<T>(_: WatchSource | MultiWatchSources$1, _: WritableComputedOptions<T>, _?: WatchOptions): WritableComputedRefWithControl<T>;
export declare function containsProp(_: object, ..._: string[]): boolean;
export declare function createDisposableDirective<H extends HTMLElement, V, A = any>(_?: originDirective<H, V, A>): originDirective<H, V, A>;
export declare function createEventHook<T = any>(): EventHookReturn<T>;
export declare function createFilterWrapper<T extends AnyFn>(_: EventFilter, _: T): (this: any, ..._: ArgumentsType<T>) => Promise<Awaited<ReturnType<T>>>;
export declare function createGlobalState<Fn extends AnyFn>(_: Fn): CreateGlobalStateReturn<Fn>;
export declare function createInjectionState<Arguments extends Array<any>, Return>(_: (..._: Arguments) => Return, _?: CreateInjectionStateOptions<Return>): CreateInjectionStateReturn<Arguments, Return, Return | undefined>;
export declare function createRef<T = any, D extends boolean = false>(_: T, _?: D): CreateRefReturn<T, D>;
export declare function createSharedComposable<Fn extends AnyFn>(_: Fn): SharedComposableReturn<Fn>;
export declare function createSingletonPromise<T>(_: () => Promise<T>): SingletonPromiseReturn<T>;
export declare function debounceFilter(_: MaybeRefOrGetter<number>, _?: DebounceFilterOptions): EventFilter<any[], any, AnyFn>;
export declare function extendRef<R extends Ref<any>, Extend extends object, Options extends ExtendRefOptions>(_: R, _: Extend, _?: Options): Extend & R;
export declare function formatDate(_: Date, _: string, _?: UseDateFormatOptions): string;
export declare function get<T, K extends keyof T>(_: MaybeRef<T>, _: K): T[K];
export declare function getLifeCycleTarget(_?: ComponentInternalInstance | null): ComponentInternalInstance | null;
export declare function identity<T>(_: T): T;
export declare function increaseWithUnit(_: string | number, _: number): string | number;
export declare function invoke<T>(_: () => T): T;
export declare function isDefined<T>(_: T): v is Exclude<T, null | undefined>;
export declare function makeDestructurable<T extends Record<string, unknown>, A extends readonly any[]>(_: T, _: A): T & A;
export declare function normalizeDate(_: DateLike): Date;
export declare function objectEntries<T extends object>(_: T): Array<[keyof T, T[keyof T]]>;
export declare function objectOmit<O extends object, T extends keyof O>(_: O, _: T[], _?: boolean): Omit<O, T>;
export declare function objectPick<O extends object, T extends keyof O>(_: O, _: T[], _?: boolean): Pick<O, T>;
export declare function pausableFilter(_?: EventFilter, _?: PausableFilterOptions): Pausable & {
  eventFilter: EventFilter;
};
export declare function promiseTimeout(_: number, _?: boolean, _?: string): Promise<void>;
export declare function provideLocal<T, K = LocalProvidedKey<T>>(_: K, _: K extends InjectionKey<infer V> ? V : T): ProvideLocalReturn;
export declare function pxValue(_: string): number;
export declare function reactify<T extends AnyFn, K extends boolean = true>(_: T, _?: ReactifyOptions<K>): ReactifyReturn<T, K>;
export declare function reactifyObject<T extends object, S extends boolean = true>(_: T, _?: ReactifyObjectOptions<S>): ReactifyObjectReturn<T, keyof T, S>;
export declare function reactiveComputed<T extends object>(_: ComputedGetter<T>): ReactiveComputedReturn<T>;
export declare function reactiveOmit<T extends object>(_: T, _: ReactiveOmitPredicate<T>): ReactiveOmitReturn<T>;
export declare function reactivePick<T extends object>(_: T, _: ReactivePickPredicate<T>): ReactivePickReturn<T, keyof T>;
export declare function refAutoReset<T>(_: MaybeRefOrGetter<T>, _?: MaybeRefOrGetter<number>): RefAutoResetReturn<T>;
export declare function refDebounced<T>(_: Ref<T>, _?: MaybeRefOrGetter<number>, _?: DebounceFilterOptions): RefDebouncedReturn<T>;
export declare function refDefault<T>(_: Ref<T | undefined | null>, _: T): Ref<T>;
export declare function refManualReset<T>(_: MaybeRefOrGetter<T>): ManualResetRefReturn<T>;
export declare function refThrottled<T = any>(_: Ref<T>, _?: number, _?: boolean, _?: boolean): RefThrottledReturn<T>;
export declare function refWithControl<T>(_: T, _?: ControlledRefOptions<T>): _$vue.ShallowUnwrapRef<{
  get: (tracking?: boolean) => T;
  set: (value: T, triggering?: boolean) => void;
  untrackedGet: () => T;
  silentSet: (v: T) => void;
  peek: () => T;
  lay: (v: T) => void;
}> & _$vue.Ref<T, T>;
export declare function set<O extends object, K extends keyof O>(_: O, _: K, _: O[K]): void;
export declare function syncRef<L, R, D extends Direction = 'both'>(_: Ref<L>, _: Ref<R>, ...[options]: Equal<L, R> extends true ? [options?: SyncRefOptions<L, R, D>] : [options: SyncRefOptions<L, R, D>]): () => void;
export declare function syncRefs<T>(_: WatchSource<T>, _: Ref<T> | Ref<T>[], _?: SyncRefsOptions): _$vue.WatchHandle;
export declare function throttleFilter(_: ThrottleFilterOptions): EventFilter;
export declare function toArray<T>(_: T | T[]): T[];
export declare function toReactive<T extends object>(_: MaybeRef<T>): UnwrapNestedRefs<T>;
export declare function toRef<T extends object, K extends keyof T>(_: T, _: K, _: T[K]): ToRef<Exclude<T[K], undefined>>;
export declare function toRefs<T extends object>(_: MaybeRef<T>, _?: ToRefsOptions): ToRefs<T>;
export declare function tryOnBeforeMount(_: Fn, _?: boolean, _?: ComponentInternalInstance | null): void;
export declare function tryOnBeforeUnmount(_: Fn, _?: ComponentInternalInstance | null): void;
export declare function tryOnMounted(_: Fn, _?: boolean, _?: ComponentInternalInstance | null): void;
export declare function tryOnScopeDispose(_: Fn, _?: boolean): boolean;
export declare function tryOnUnmounted(_: Fn, _?: ComponentInternalInstance | null): void;
export declare function until<T>(_: WatchSource<T> | MaybeRefOrGetter<T>): UntilValueInstance<T>;
export declare function useArrayDifference<T>(_: MaybeRefOrGetter<T[]>, _: MaybeRefOrGetter<T[]>, _?: (_: T, _: T) => boolean, _?: UseArrayDifferenceOptions): UseArrayDifferenceReturn<T>;
export declare function useArrayEvery<T>(_: MaybeRefOrGetter<MaybeRefOrGetter<T>[]>, _: (_: T, _: number, _: MaybeRefOrGetter<T>[]) => unknown): UseArrayEveryReturn;
export declare function useArrayFilter<T>(_: MaybeRefOrGetter<MaybeRefOrGetter<T>[]>, _: (_: T, _: number, _: T[]) => unknown): UseArrayFilterReturn<T>;
export declare function useArrayFind<T>(_: MaybeRefOrGetter<MaybeRefOrGetter<T>[]>, _: (_: T, _: number, _: MaybeRefOrGetter<T>[]) => boolean): UseArrayFindReturn<T>;
export declare function useArrayFindIndex<T>(_: MaybeRefOrGetter<MaybeRefOrGetter<T>[]>, _: (_: T, _: number, _: MaybeRefOrGetter<T>[]) => unknown): UseArrayFindIndexReturn;
export declare function useArrayFindLast<T>(_: MaybeRefOrGetter<MaybeRefOrGetter<T>[]>, _: (_: T, _: number, _: MaybeRefOrGetter<T>[]) => boolean): UseArrayFindLastReturn<T>;
export declare function useArrayIncludes<T, V = any>(_: MaybeRefOrGetter<MaybeRefOrGetter<T>[]>, _: MaybeRefOrGetter<V>, _?: UseArrayIncludesOptions<T, V>): UseArrayIncludesReturn;
export declare function useArrayJoin(_: MaybeRefOrGetter<MaybeRefOrGetter<any>[]>, _?: MaybeRefOrGetter<string>): UseArrayJoinReturn;
export declare function useArrayMap<T, U = T>(_: MaybeRefOrGetter<MaybeRefOrGetter<T>[]>, _: (_: T, _: number, _: T[]) => U): UseArrayMapReturn<U>;
export declare function useArrayReduce<T, U>(_: MaybeRefOrGetter<MaybeRefOrGetter<T>[]>, _: UseArrayReducer<U, T, U>, _: MaybeRefOrGetter<U>): UseArrayReduceReturn<U>;
export declare function useArraySome<T>(_: MaybeRefOrGetter<MaybeRefOrGetter<T>[]>, _: (_: T, _: number, _: MaybeRefOrGetter<T>[]) => unknown): UseArraySomeReturn;
export declare function useArrayUnique<T>(_: MaybeRefOrGetter<MaybeRefOrGetter<T>[]>, _?: (_: T, _: T, _: T[]) => boolean): UseArrayUniqueReturn<T>;
export declare function useCounter(_?: MaybeRef<number>, _?: UseCounterOptions): {
  count: Readonly<Ref<number, number> | _$vue.ShallowRef<number, number> | _$vue.WritableComputedRef<number, number>>;
  inc: (_?: number) => number;
  dec: (_?: number) => number;
  get: () => number;
  set: (_: number) => number;
  reset: (_?: number) => number;
};
export declare function useDateFormat(_: MaybeRefOrGetter<DateLike>, _?: MaybeRefOrGetter<string>, _?: UseDateFormatOptions): UseDateFormatReturn;
export declare function useDebounceFn<T extends FunctionArgs>(_: T, _?: MaybeRefOrGetter<number>, _?: DebounceFilterOptions): UseDebounceFnReturn<T>;
export declare function useInterval(_: MaybeRefOrGetter<number>, _: UseIntervalOptions<true>): Readonly<UseIntervalControls & Pausable>;
export declare function useIntervalFn(_: Fn, _?: MaybeRefOrGetter<number>, _?: UseIntervalFnOptions): UseIntervalFnReturn;
export declare function useLastChanged(_: WatchSource, _: UseLastChangedOptions<true> | UseLastChangedOptions<boolean, number>): Readonly<ShallowRef<number>>;
export declare function useThrottleFn<T extends FunctionArgs>(_: T, _?: MaybeRefOrGetter<number>, _?: boolean, _?: boolean, _?: boolean): PromisifyFn<T>;
export declare function useTimeout(_: MaybeRefOrGetter<number>, _: UseTimeoutOptions<true>): {
  ready: ComputedRef<boolean>;
} & Stoppable;
export declare function useTimeoutFn<CallbackFn extends AnyFn>(_: CallbackFn, _: MaybeRefOrGetter<number>, _?: UseTimeoutFnOptions): UseTimeoutFnReturn<CallbackFn>;
export declare function useToggle<Truthy = true, Falsy = false, T = Truthy | Falsy>(_?: T, _?: UseToggleOptions<Truthy, Falsy>): [ShallowRef<T>, (value?: T) => T];
export declare function useToNumber(_: MaybeRefOrGetter<number | string>, _?: UseToNumberOptions): ComputedRef<number>;
export declare function useToString(_: MaybeRefOrGetter<unknown>): ComputedRef<string>;
export declare function watchArray<T, Immediate extends Readonly<boolean> = false>(_: WatchSource<T[]> | T[], _: WatchArrayCallback<T[], Immediate extends true ? T[] | undefined : T[]>, _?: WatchOptions<Immediate>): _$vue.WatchHandle;
export declare function watchAtMost<T extends object, Immediate extends Readonly<boolean> = false>(_: T, _: WatchCallback<MapSources<T>, MapOldSources<T, Immediate>>, _: WatchAtMostOptions<Immediate>): WatchAtMostReturn;
export declare function watchDebounced<T extends object, Immediate extends Readonly<boolean> = false>(_: T, _: WatchCallback<T, Immediate extends true ? T | undefined : T>, _?: WatchDebouncedOptions<Immediate>): WatchHandle;
export declare function watchDeep<T extends object, Immediate extends Readonly<boolean> = false>(_: T, _: WatchCallback<T, Immediate extends true ? T | undefined : T>, _?: Omit<WatchOptions<Immediate>, 'deep'>): WatchHandle;
export declare function watchIgnorable<T extends object, Immediate extends Readonly<boolean> = false>(_: T, _: WatchCallback<T, Immediate extends true ? T | undefined : T>, _?: WatchWithFilterOptions<Immediate>): WatchIgnorableReturn;
export declare function watchImmediate<T extends object>(_: T, _: WatchCallback<T, T | undefined>, _?: Omit<WatchOptions<true>, 'immediate'>): WatchHandle;
export declare function watchOnce<T extends object>(_: T, _: WatchCallback<T, T | undefined>, _?: Omit<WatchOptions<true>, 'once'>): WatchHandle;
export declare function watchPausable<T extends object, Immediate extends Readonly<boolean> = false>(_: T, _: WatchCallback<T, Immediate extends true ? T | undefined : T>, _?: WatchPausableOptions<Immediate>): WatchPausableReturn;
export declare function watchThrottled<T extends object, Immediate extends Readonly<boolean> = false>(_: T, _: WatchCallback<T, Immediate extends true ? T | undefined : T>, _?: WatchThrottledOptions<Immediate>): WatchHandle;
export declare function watchTriggerable<T extends object, FnReturnT>(_: T, _: WatchTriggerableCallback<T, T | undefined, FnReturnT>, _?: WatchWithFilterOptions<boolean>): WatchTriggerableReturn<FnReturnT>;
export declare function watchWithFilter<T extends object, Immediate extends Readonly<boolean> = false>(_: T, _: WatchCallback<T, Immediate extends true ? T | undefined : T>, _?: WatchWithFilterOptions<Immediate>): WatchHandle;
export declare function whenever<T>(_: WatchSource<T>, _: WatchCallback<Truthy<T>, T>, _?: WheneverOptions<false>): WatchHandle;
// #endregion

// #region Variables
export declare const assert: (condition: boolean, ...infos: any[]) => void;
export declare const autoResetRef: typeof refAutoReset;
export declare const bypassFilter: EventFilter;
export declare const camelize: (str: string) => string;
export declare const clamp: (n: number, min: number, max: number) => number;
export declare const controlledComputed: typeof computedWithControl;
export declare const controlledRef: typeof refWithControl;
export declare const createReactiveFn: typeof reactify;
export declare const debouncedRef: typeof refDebounced;
export declare const debouncedWatch: typeof watchDebounced;
export declare const eagerComputed: typeof computedEager;
export declare const hasOwn: <T extends object, K extends keyof T>(val: T, key: K) => key is K;
export declare const hyphenate: (str: string) => string;
export declare const ignorableWatch: typeof watchIgnorable;
export declare const injectLocal: typeof inject;
export declare const isClient: boolean;
export declare const isDef: <T = any>(val?: T) => val is T;
export declare const isIOS: boolean;
export declare const isObject: (val: any) => val is object;
export declare const isWorker: boolean;
export declare const noop: () => void;
export declare const notNullish: <T = any>(val?: T | null | undefined) => val is T;
export declare const now: () => number;
export declare const pausableWatch: typeof watchPausable;
export declare const rand: (min: number, max: number) => number;
export declare const throttledRef: typeof refThrottled;
export declare const throttledWatch: typeof watchThrottled;
export declare const timestamp: () => number;
export declare const useDebounce: typeof refDebounced;
export declare const useThrottle: typeof refThrottled;
// #endregion

// #region Other
export { MultiWatchSources }
// #endregion