/**
 * Generated by tsnapi — public API snapshot of `@vueuse/math`
 */
// #region Interfaces
export interface UsePrecisionOptions {
  math?: 'floor' | 'ceil' | 'round';
}
// #endregion

// #region Types
export type ProjectorFunction<F, T> = (_: F, _: readonly [F, F], _: readonly [T, T]) => T;
export type UseMathKeys = keyof { [K in keyof Math as Math[K] extends ((...args: any) => any) ? K : never]: unknown };
export type UseMathReturn<K extends keyof Math> = ReturnType<Reactified<Math[K], true>>;
export type UseProjection<F, T> = (_: MaybeRefOrGetter<F>) => ComputedRef<T>;
// #endregion

// #region Functions
export declare function createGenericProjection<F = number, T = number>(_: MaybeRefOrGetter<readonly [F, F]>, _: MaybeRefOrGetter<readonly [T, T]>, _: ProjectorFunction<F, T>): UseProjection<F, T>;
export declare function createProjection(_: MaybeRefOrGetter<readonly [number, number]>, _: MaybeRefOrGetter<readonly [number, number]>, _?: ProjectorFunction<number, number>): UseProjection<number, number>;
export declare function logicAnd(..._: MaybeRefOrGetter<any>[]): ComputedRef<boolean>;
export declare function logicNot(_: MaybeRefOrGetter<any>): ComputedRef<boolean>;
export declare function logicOr(..._: MaybeRefOrGetter<any>[]): ComputedRef<boolean>;
export declare function useAbs(_: MaybeRefOrGetter<number>): ComputedRef<number>;
export declare function useAverage(..._: MaybeRefOrGetter<number>[]): ComputedRef<number>;
export declare function useCeil(_: MaybeRefOrGetter<number>): ComputedRef<number>;
export declare function useClamp(_: MaybeRefOrGetter<number>, _: MaybeRefOrGetter<number>, _: MaybeRefOrGetter<number>): Ref<number>;
export declare function useFloor(_: MaybeRefOrGetter<number>): ComputedRef<number>;
export declare function useMath<K extends keyof Math>(_: K, ..._: ArgumentsType<Reactified<Math[K], true>>): UseMathReturn<K>;
export declare function useMax(..._: MaybeRefOrGetter<number>[]): ComputedRef<number>;
export declare function useMin(..._: MaybeRefOrGetter<number>[]): ComputedRef<number>;
export declare function usePrecision(_: MaybeRefOrGetter<number>, _: MaybeRefOrGetter<number>, _?: MaybeRefOrGetter<UsePrecisionOptions>): ComputedRef<number>;
export declare function useProjection(_: MaybeRefOrGetter<number>, _: MaybeRefOrGetter<readonly [number, number]>, _: MaybeRefOrGetter<readonly [number, number]>, _?: ProjectorFunction<number, number>): _$vue.ComputedRef<number>;
export declare function useRound(_: MaybeRefOrGetter<number>): ComputedRef<number>;
export declare function useSum(..._: MaybeRefOrGetter<number>[]): ComputedRef<number>;
export declare function useTrunc(_: MaybeRefOrGetter<number>): ComputedRef<number>;
// #endregion

// #region Variables
export declare const and: typeof logicAnd;
export declare const not: typeof logicNot;
export declare const or: typeof logicOr;
// #endregion