/**
 * Generated by tsnapi — public API snapshot of `@vueuse/rxjs`
 */
// #region Interfaces
export interface UseExtractedObservableOptions<E> extends UseObservableOptions<E> {
  onComplete?: () => void;
}
export interface UseObservableOptions<I> {
  onError?: (_: any) => void;
  initialValue?: I | undefined;
}
export interface UseSubjectOptions<I = undefined> extends Omit<UseObservableOptions<I>, 'initialValue'> {}
export interface WatchExtractedObservableOptions {
  onError?: (_: unknown) => void;
  onComplete?: () => void;
}
// #endregion

// #region Types
export type OnCleanup = (_: () => void) => void;
export type WatchExtractedObservableCallback<Value, OldValue, ObservableElement> = (_: NonNullable<Value>, _: OldValue, _: OnCleanup) => Observable<ObservableElement>;
// #endregion

// #region Functions
export declare function from<T>(_: ObservableInput<T> | Ref<T>, _?: WatchOptions): Observable<T>;
export declare function fromEvent<T extends HTMLElement | null>(_: MaybeRef<T>, _: string): Observable<Event>;
export declare function toObserver<T>(_: Ref<T>): NextObserver<T>;
export declare function useExtractedObservable<T extends object, E, Immediate extends Readonly<boolean> = false>(_: T, _: WatchExtractedObservableCallback<T, Immediate extends true ? T | undefined : T, E>, _?: UseExtractedObservableOptions<E>, _?: WatchOptions<Immediate>): DeepReadonly<ShallowRef<E>>;
export declare function useObservable<H, I = undefined>(_: Observable<H>, _?: UseObservableOptions<I | undefined>): Readonly<Ref<H | I>>;
export declare function useSubject<H>(_: Subject<H>, _?: UseSubjectOptions): Ref<H | undefined>;
export declare function useSubscription(_: Unsubscribable): void;
export declare function watchExtractedObservable<T extends object, E, Immediate extends Readonly<boolean> = false>(_: T, _: WatchExtractedObservableCallback<T, Immediate extends true ? T | undefined : T, E>, _: (_: E) => void, _?: WatchExtractedObservableOptions, _?: WatchOptions<Immediate>): WatchHandle;
// #endregion