/**
 * Generated by tsnapi — public API snapshot of `@vueuse/router`
 */
// #region Functions
export declare function useRouteHash(_?: MaybeRefOrGetter<RouteHashValueRaw>, {
  mode,
  route,
  router
}?: ReactiveRouteOptions): _$vue.Ref<RouteHashValueRaw, RouteHashValueRaw>;
export declare function useRouteParams<T extends RouteParamValueRaw = RouteParamValueRaw, K = T>(_: string, _?: MaybeRefOrGetter<T>, _?: ReactiveRouteOptionsWithTransform<T, K>): Ref<K>;
export declare function useRouteQuery<T extends RouteQueryValueRaw = RouteQueryValueRaw, K = T>(_: string, _?: MaybeRefOrGetter<T>, _?: ReactiveRouteOptionsWithTransform<T, K>): Ref<K>;
// #endregion