/**
 * Generated by tsnapi — public API snapshot of `@vueuse/router`
 */
// #region Functions
export declare function useRouteHash(_?: MaybeRefOrGetter<RouteHashValueRaw>, { mode, route, router }?: ReactiveRouteOptions): import("vue").Ref<RouteHashValueRaw, RouteHashValueRaw>;
export declare function useRouteParams(_: string): Ref<null | string | string[]>;
export declare function useRouteParams<T extends RouteParamValueRaw = RouteParamValueRaw, K = T>(_: string, _?: MaybeRefOrGetter<T>, _?: ReactiveRouteOptionsWithTransform<T, K>): Ref<K>;
export declare function useRouteQuery(_: string): Ref<undefined | null | string | string[]>;
export declare function useRouteQuery<T extends RouteQueryValueRaw = RouteQueryValueRaw, K = T>(_: string, _?: MaybeRefOrGetter<T>, _?: ReactiveRouteOptionsWithTransform<T, K>): Ref<K>;
// #endregion

// #region Referenced (internal)
interface ReactiveRouteOptions {
  mode?: MaybeRef<'replace' | 'push'>;
  route?: ReturnType<typeof useRoute>;
  router?: ReturnType<typeof useRouter>;
}
interface ReactiveRouteOptionsWithTransform<V, R> extends ReactiveRouteOptions {
  transform?: ((_: V) => R) | ({
    get?: (_: V) => R;
    set?: (_: R) => V;
  });
}
type RouteHashValueRaw = string | null | undefined;
type RouteQueryValueRaw = RouteParamValueRaw | string[];
// #endregion