/**
 * Generated by tsnapi — public API snapshot of `@vueuse/components`
 */
// #region Interfaces
export interface OnClickOutsideProps extends RenderableComponent {
  options?: Omit<OnClickOutsideOptions, 'controls'>;
}
export interface OnLongPressProps extends RenderableComponent {
  options?: OnLongPressOptions;
}
export interface UseActiveElementProps extends UseActiveElementOptions {}
export interface UseBatteryProps extends ConfigurableNavigator {}
export interface UseClipboardProps<Source = string> extends UseClipboardOptions<Source> {}
export interface UseColorModeProps extends UseColorModeOptions {}
export interface UseDarkProps extends UseDarkOptions {}
export interface UseDeviceMotionProps extends DeviceMotionOptions {}
export interface UseDeviceOrientationProps extends ConfigurableWindow {}
export interface UseDevicePixelRatioProps extends ConfigurableWindow {}
export interface UseDevicesListProps extends UseDevicesListOptions {}
export interface UseDocumentVisibilityProps extends ConfigurableDocument {}
export interface UseDraggableProps extends UseDraggableOptions, RenderableComponent {
  storageKey?: string;
  storageType?: 'local' | 'session';
}
export interface UseElementBoundingProps extends UseElementBoundingOptions, RenderableComponent {}
export interface UseElementSizeProps extends Partial<ElementSize>, UseResizeObserverOptions, RenderableComponent {}
export interface UseElementVisibilityProps extends Omit<UseElementVisibilityOptions<true>, 'controls'>, RenderableComponent {}
export interface UseEyeDropperProps extends UseEyeDropperOptions {}
export interface UseFullscreenProps extends UseFullscreenOptions, RenderableComponent {}
export interface UseGeolocationProps extends UseGeolocationOptions {}
export interface UseIdleProps extends UseIdleOptions {
  timeout: number;
}
export interface UseImageProps extends UseImageOptions, RenderableComponent$1 {}
export interface UseMouseInElementProps extends MouseInElementOptions, RenderableComponent {}
export interface UseMousePressedProps extends Omit<UseMousePressedOptions, 'target'>, RenderableComponent {}
export interface UseMouseProps extends UseMouseOptions {}
export interface UseNetworkProps extends ConfigurableWindow {}
export interface UseNowProps extends Omit<UseNowOptions<true>, 'controls'> {}
export interface UseObjectUrlProps {
  object: Blob | MediaSource | undefined;
}
export interface UseOffsetPaginationProps extends UseOffsetPaginationOptions {}
export interface UseOnlineProps extends ConfigurableWindow {}
export interface UsePageLeaveProps extends ConfigurableWindow {}
export interface UsePointerLockProps extends RenderableComponent, UsePointerLockOptions {}
export interface UsePointerProps extends Omit<UsePointerOptions, 'target'> {
  target?: 'window' | 'self';
}
export interface UsePreferredColorSchemeProps extends ConfigurableWindow {}
export interface UsePreferredContrastProps extends ConfigurableWindow {}
export interface UsePreferredDarkProps extends ConfigurableWindow {}
export interface UsePreferredLanguagesProps extends ConfigurableWindow {}
export interface UsePreferredReducedMotionProps extends ConfigurableWindow {}
export interface UseScreenSafeAreaProps extends RenderableComponent {
  top?: boolean;
  right?: boolean;
  bottom?: boolean;
  left?: boolean;
}
export interface UseTimeAgoProps extends Omit<UseTimeAgoOptions<true>, 'controls'> {
  time: MaybeRef<Date | number | string>;
}
export interface UseTimestampProps extends Omit<UseTimestampOptions<true>, 'controls'> {}
export interface UseVirtualListProps {
  list: Array<any>;
  options: UseVirtualListOptions;
  height: string;
}
export interface UseWindowFocusProps extends ConfigurableWindow {}
export interface UseWindowSizeProps extends UseWindowSizeOptions {}
// #endregion

// #region Types
export type OnClickOutsideEmits = {
  trigger: (_: Event) => void;
};
export type OnLongPressEmits = {
  trigger: (_: PointerEvent) => void;
};
export type UseOffsetPaginationEmits = {
  'page-change': (..._: Parameters<NonNullable<UseOffsetPaginationOptions['onPageChange']>>) => void;
  'page-size-change': (..._: Parameters<NonNullable<UseOffsetPaginationOptions['onPageSizeChange']>>) => void;
  'page-count-change': (..._: Parameters<NonNullable<UseOffsetPaginationOptions['onPageCountChange']>>) => void;
};
// #endregion

// #region Variables
export declare const OnClickOutside: import("vue").DefineSetupFnComponent<OnClickOutsideProps, OnClickOutsideEmits, {}, OnClickOutsideProps & {
  onTrigger?: ((event: Event) => any) | undefined;
}, import("vue").PublicProps>;
export declare const OnLongPress: import("vue").DefineSetupFnComponent<OnLongPressProps, OnLongPressEmits, SlotsType<OnLongPressSlots>, OnLongPressProps & {
  onTrigger?: ((event: PointerEvent) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseActiveElement: import("vue").DefineSetupFnComponent<UseActiveElementProps, Record<string, never>, SlotsType<UseActiveElementSlots>, UseActiveElementProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseBattery: import("vue").DefineSetupFnComponent<UseBatteryProps, Record<string, never>, SlotsType<UseBatterySlots>, UseBatteryProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseBrowserLocation: import("vue").DefineSetupFnComponent<UseBrowserLocationProps, Record<string, never>, SlotsType<UseBrowserLocationSlots>, UseBrowserLocationProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseClipboard: import("vue").DefineSetupFnComponent<UseClipboardProps<string>, Record<string, never>, SlotsType<UseClipboardSlots>, UseClipboardProps<string> & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseColorMode: import("vue").DefineSetupFnComponent<UseColorModeProps, Record<string, never>, SlotsType<UseColorModeSlots>, UseColorModeProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseDark: import("vue").DefineSetupFnComponent<UseDarkProps, Record<string, never>, SlotsType<UseDarkSlots>, UseDarkProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseDeviceMotion: import("vue").DefineSetupFnComponent<UseDeviceMotionProps, Record<string, never>, SlotsType<UseDeviceMotionSlots>, UseDeviceMotionProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseDeviceOrientation: import("vue").DefineSetupFnComponent<UseDeviceOrientationProps, Record<string, never>, SlotsType<UseDeviceOrientationSlots>, UseDeviceOrientationProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseDevicePixelRatio: import("vue").DefineSetupFnComponent<UseDevicePixelRatioProps, Record<string, never>, SlotsType<UseDevicePixelRatioSlots>, UseDevicePixelRatioProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseDevicesList: import("vue").DefineSetupFnComponent<UseDevicesListProps, Record<string, never>, SlotsType<UseDevicesListSlots>, UseDevicesListProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseDocumentVisibility: import("vue").DefineSetupFnComponent<UseDocumentVisibilityProps, Record<string, never>, SlotsType<UseDocumentVisibilitySlots>, UseDocumentVisibilityProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseDraggable: import("vue").DefineSetupFnComponent<UseDraggableProps, Record<string, never>, SlotsType<any>, UseDraggableProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseElementBounding: import("vue").DefineSetupFnComponent<UseElementBoundingProps, Record<string, never>, SlotsType<UseElementBoundingSlots>, UseElementBoundingProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseElementOverflow: import("vue").DefineComponent<UseElementOverflowOptions & RenderableComponent, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<UseElementOverflowOptions & RenderableComponent> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, false, {}, any>;
export declare const UseElementSize: import("vue").DefineSetupFnComponent<UseElementSizeProps, Record<string, never>, SlotsType<UseElementSizeSlots>, UseElementSizeProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseElementVisibility: import("vue").DefineSetupFnComponent<UseElementVisibilityProps, Record<string, never>, SlotsType<UseElementVisibilitySlots>, UseElementVisibilityProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseEyeDropper: import("vue").DefineSetupFnComponent<UseEyeDropperProps, Record<string, never>, SlotsType<UseEyeDropperSlots>, UseEyeDropperProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseFullscreen: import("vue").DefineSetupFnComponent<UseFullscreenProps, Record<string, never>, SlotsType<UseFullscreenSlots>, UseFullscreenProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseGeolocation: import("vue").DefineSetupFnComponent<UseGeolocationProps, Record<string, never>, SlotsType<UseGeolocationSlots>, UseGeolocationProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseIdle: import("vue").DefineSetupFnComponent<UseIdleProps, Record<string, never>, SlotsType<UseIdleSlots>, UseIdleProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseImage: import("vue").DefineSetupFnComponent<UseImageProps, Record<string, never>, SlotsType<UseImageSlots>, UseImageProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseMouse: import("vue").DefineSetupFnComponent<UseMouseProps, Record<string, never>, SlotsType<UseMouseSlots>, UseMouseProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseMouseInElement: import("vue").DefineSetupFnComponent<UseMouseInElementProps, Record<string, never>, SlotsType<UseMouseInElementSlots>, UseMouseInElementProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseMousePressed: import("vue").DefineSetupFnComponent<UseMousePressedProps, Record<string, never>, SlotsType<UseMousePressedSlots>, UseMousePressedProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseNetwork: import("vue").DefineSetupFnComponent<UseNetworkProps, Record<string, never>, SlotsType<UseNetworkSlots>, UseNetworkProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseNow: import("vue").DefineSetupFnComponent<UseNowProps, Record<string, never>, SlotsType<UseNowSlots>, UseNowProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseObjectUrl: import("vue").DefineSetupFnComponent<UseObjectUrlProps, Record<string, never>, SlotsType<UseObjectUrlSlots>, UseObjectUrlProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseOffsetPagination: import("vue").DefineSetupFnComponent<UseOffsetPaginationProps, UseOffsetPaginationEmits, SlotsType<UseOffsetPaginationSlots>, UseOffsetPaginationProps & {
  "onPage-change"?: ((returnValue: {
    currentPage: number;
    currentPageSize: number;
    pageCount: number;
    isFirstPage: boolean;
    isLastPage: boolean;
    prev: () => void;
    next: () => void;
  }) => any) | undefined;
  "onPage-size-change"?: ((returnValue: {
    currentPage: number;
    currentPageSize: number;
    pageCount: number;
    isFirstPage: boolean;
    isLastPage: boolean;
    prev: () => void;
    next: () => void;
  }) => any) | undefined;
  "onPage-count-change"?: ((returnValue: {
    currentPage: number;
    currentPageSize: number;
    pageCount: number;
    isFirstPage: boolean;
    isLastPage: boolean;
    prev: () => void;
    next: () => void;
  }) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseOnline: import("vue").DefineSetupFnComponent<UseOnlineProps, Record<string, never>, SlotsType<UseOnlineSlots>, UseOnlineProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UsePageLeave: import("vue").DefineSetupFnComponent<UsePageLeaveProps, Record<string, never>, SlotsType<UsePageLeaveSlots>, UsePageLeaveProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UsePointer: import("vue").DefineSetupFnComponent<UsePointerProps, Record<string, never>, SlotsType<UsePointerSlots>, UsePointerProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UsePointerLock: import("vue").DefineSetupFnComponent<UsePointerLockProps, Record<string, never>, SlotsType<UsePointerLockSlots>, UsePointerLockProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UsePreferredColorScheme: import("vue").DefineSetupFnComponent<UsePreferredColorSchemeProps, Record<string, never>, SlotsType<UsePreferredColorSchemeSlots>, UsePreferredColorSchemeProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UsePreferredContrast: import("vue").DefineSetupFnComponent<UsePreferredContrastProps, Record<string, never>, SlotsType<UsePreferredContrastSlots>, UsePreferredContrastProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UsePreferredDark: import("vue").DefineSetupFnComponent<UsePreferredDarkProps, Record<string, never>, SlotsType<UsePreferredDarkSlots>, UsePreferredDarkProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UsePreferredLanguages: import("vue").DefineSetupFnComponent<UsePreferredLanguagesProps, Record<string, never>, SlotsType<UsePreferredLanguagesSlots>, UsePreferredLanguagesProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UsePreferredReducedMotion: import("vue").DefineSetupFnComponent<UsePreferredReducedMotionProps, Record<string, never>, SlotsType<UsePreferredReducedMotionSlots>, UsePreferredReducedMotionProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UsePreferredReducedTransparency: import("vue").DefineComponent<{}, () => import("vue").VNode<import("vue").RendererNode, import("vue").RendererElement, {
  [key: string]: any;
}>[] | undefined, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
export declare const UseScreenSafeArea: import("vue").DefineSetupFnComponent<UseScreenSafeAreaProps, Record<string, never>, SlotsType<UseScreenSafeAreaSlots>, UseScreenSafeAreaProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseTimeAgo: import("vue").DefineSetupFnComponent<UseTimeAgoProps, Record<string, never>, SlotsType<UseTimeAgoSlots>, UseTimeAgoProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseTimestamp: import("vue").DefineSetupFnComponent<UseTimestampProps, Record<string, never>, SlotsType<UseTimestampSlots>, UseTimestampProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseVirtualList: import("vue").DefineSetupFnComponent<UseVirtualListProps, {}, {}, UseVirtualListProps & {}, import("vue").PublicProps>;
export declare const UseWindowFocus: import("vue").DefineSetupFnComponent<UseWindowFocusProps, Record<string, never>, SlotsType<UseWindowFocusSlots>, UseWindowFocusProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const UseWindowSize: import("vue").DefineSetupFnComponent<UseWindowSizeProps, Record<string, never>, SlotsType<UseWindowSizeSlots>, UseWindowSizeProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
export declare const vElementBounding: import("vue").FunctionDirective<HTMLElement, BindingValue$9, string, any> | import("vue").ObjectDirective<HTMLElement, BindingValue$9, string, any>;
export declare const vElementBoundingVapor: VaporDirective<HTMLElement, BindingValue$9>;
export declare const vElementHover: import("vue").FunctionDirective<HTMLElement, BindingValue$8, string, any> | import("vue").ObjectDirective<HTMLElement, BindingValue$8, string, any>;
export declare const vElementHoverVapor: VaporDirective<HTMLElement, BindingValue$8>;
export declare const vElementOverflow: import("vue").FunctionDirective<HTMLElement, BindingValue$7, string, any> | import("vue").ObjectDirective<HTMLElement, BindingValue$7, string, any>;
export declare const vElementOverflowVapor: VaporDirective<HTMLElement, BindingValue$7>;
export declare const vElementSize: import("vue").FunctionDirective<HTMLElement, BindingValue$6, string, any> | import("vue").ObjectDirective<HTMLElement, BindingValue$6, string, any>;
export declare const vElementSizeVapor: VaporDirective<HTMLElement, BindingValue$6>;
export declare const vElementVisibility: import("vue").FunctionDirective<HTMLElement, BindingValue$5, string, any> | import("vue").ObjectDirective<HTMLElement, BindingValue$5, string, any>;
export declare const vElementVisibilityVapor: VaporDirective<HTMLElement, BindingValue$5>;
export declare const vInfiniteScroll: import("vue").FunctionDirective<HTMLElement, BindingValue$4, string, any> | import("vue").ObjectDirective<HTMLElement, BindingValue$4, string, any>;
export declare const vInfiniteScrollVapor: VaporDirective<HTMLElement, BindingValue$4>;
export declare const vIntersectionObserver: import("vue").FunctionDirective<HTMLElement, BindingValue$3, string, any> | import("vue").ObjectDirective<HTMLElement, BindingValue$3, string, any>;
export declare const vIntersectionObserverVapor: VaporDirective<HTMLElement, BindingValue$3>;
export declare const vMouseInElement: import("vue").FunctionDirective<HTMLElement, BindingValue$2, string, any> | import("vue").ObjectDirective<HTMLElement, BindingValue$2, string, any>;
export declare const vMouseInElementVapor: VaporDirective<HTMLElement, BindingValue$2>;
export declare const vOnClickOutside: ObjectDirective<HTMLElement, BindingValue$12>;
/** @deprecated */
export declare const VOnClickOutside: ObjectDirective<HTMLElement, BindingValue$12, string, any>;
export declare const vOnClickOutsideVapor: VaporDirective<HTMLElement, BindingValue$12, 'bubble'>;
export declare const vOnKeyStroke: import("vue").FunctionDirective<HTMLElement, BindingValue$11, string, any> | import("vue").ObjectDirective<HTMLElement, BindingValue$11, string, any>;
export declare const vOnKeyStrokeVapor: VaporDirective<HTMLElement, BindingValue$11, never, string>;
export declare const vOnLongPress: import("vue").FunctionDirective<HTMLElement, BindingValue$10, string, any> | import("vue").ObjectDirective<HTMLElement, BindingValue$10, string, any>;
/** @deprecated */
export declare const VOnLongPress: import("vue").FunctionDirective<HTMLElement, BindingValue$10, string, any> | import("vue").ObjectDirective<HTMLElement, BindingValue$10, string, any>;
export declare const vOnLongPressVapor: VaporDirective<HTMLElement, BindingValue$10, keyof OnLongPressModifiers>;
export declare const vResizeObserver: import("vue").FunctionDirective<HTMLElement, BindingValue$1, string, any> | import("vue").ObjectDirective<HTMLElement, BindingValue$1, string, any>;
export declare const vResizeObserverVapor: VaporDirective<HTMLElement, BindingValue$1>;
export declare const vScroll: import("vue").FunctionDirective<HTMLElement, BindingValue, string, any> | import("vue").ObjectDirective<HTMLElement, BindingValue, string, any>;
export declare const vScrollLock: import("vue").FunctionDirective<HTMLElement, boolean, string, any> | import("vue").ObjectDirective<HTMLElement, boolean, string, any>;
export declare const vScrollLockVapor: VaporDirective<HTMLElement, boolean>;
export declare const vScrollVapor: VaporDirective<HTMLElement, BindingValue>;
// #endregion

// #region Referenced (internal)
type BindingValue = BindingValueFunction | BindingValueArray;
type BindingValue$1 = BindingValueFunction$1 | BindingValueArray$1;
type BindingValue$10 = BindingValueFunction$8 | BindingValueArray$8;
type BindingValue$11 = BindingValueFunction$9 | BindingValueArray$9;
type BindingValue$12 = OnClickOutsideHandler | [(evt: any) => void, Omit<OnClickOutsideOptions, 'controls'>];
type BindingValue$2 = BindingValueFunction$2 | BindingValueArray$2;
type BindingValue$3 = BindingValueFunction$3 | BindingValueArray$3;
type BindingValue$4 = BindingValueFunction$4 | BindingValueArray$4;
type BindingValue$5 = BindingValueFunctionWithoutControls | BindingValueArray$5;
type BindingValue$6 = BindingValueFunction$5 | BindingValueArray$6;
type BindingValue$7 = VElementOverflowHandler | [VElementOverflowHandler, UseElementOverflowOptions$1];
type BindingValue$8 = BindingValueFunction$6 | [handler: BindingValueFunction$6, options: UseElementHoverOptions];
type BindingValue$9 = BindingValueFunction$7 | BindingValueArray$7;
interface OnLongPressSlots {
  default: (_: UseOnLongPressReturn) => any;
}
interface RenderableComponent$1 {
  as?: object | string;
}
interface UseActiveElementSlots {
  default: (_: Reactive<{
    element: UseActiveElementReturn;
  }>) => any;
}
interface UseBatterySlots {
  default: (_: Reactive<UseBatteryReturn>) => any;
}
interface UseBrowserLocationProps extends ConfigurableWindow {}
interface UseBrowserLocationSlots {
  default: (_: Reactive<UseBrowserLocationReturn>) => any;
}
interface UseClipboardSlots {
  default: (_: Reactive<UseClipboardReturn<true>>) => any;
}
interface UseColorModeSlots {
  default: (_: Reactive<{
    mode: UseColorModeReturn<BasicColorMode>;
    system: UseColorModeReturn['system'];
    store: UseColorModeReturn['store'];
  }>) => any;
}
interface UseDarkSlots {
  default: (_: Reactive<{
    isDark: UseDarkReturn;
    toggleDark: ToggleFn;
  }>) => any;
}
interface UseDeviceMotionSlots {
  default: (_: UseDeviceMotionReturn) => any;
}
interface UseDeviceOrientationSlots {
  default: (_: Reactive<UseDeviceOrientationReturn>) => any;
}
interface UseDevicePixelRatioSlots {
  default: (_: Reactive<UseDevicePixelRatioReturn>) => any;
}
interface UseDevicesListSlots {
  default: (_: Reactive<UseDevicesListReturn>) => any;
}
interface UseDocumentVisibilitySlots {
  default: (_: Reactive<{
    visibility: UseDocumentVisibilityReturn;
  }>) => any;
}
interface UseElementBoundingSlots {
  default: (_: Reactive<UseElementBoundingReturn>) => any;
}
interface UseElementSizeSlots {
  default: (_: Reactive<UseElementSizeReturn>) => any;
}
interface UseElementVisibilitySlots {
  default: (_: Reactive<UseElementVisibilityReturn<true>>) => any;
}
interface UseEyeDropperSlots {
  default: (_: Reactive<UseEyeDropperReturn>) => any;
}
interface UseFullscreenSlots {
  default: (_: Reactive<UseFullscreenReturn>) => any;
}
interface UseGeolocationSlots {
  default: (_: Reactive<UseGeolocationReturn>) => any;
}
interface UseIdleSlots {
  default: (_: Reactive<UseIdleReturn>) => any;
}
interface UseImageSlots {
  default: (_: Reactive<UseImageReturn>) => any;
  loading: (_: Reactive<UseImageReturn>) => any;
  error: (_: UnwrapRef<UseImageReturn['error']>) => any;
}
interface UseMouseInElementSlots {
  default: (_: Reactive<UseMouseInElementReturn>) => any;
}
interface UseMousePressedSlots {
  default: (_: Reactive<UseMousePressedReturn>) => any;
}
interface UseMouseSlots {
  default: (_: Reactive<UseMouseReturn>) => any;
}
interface UseNetworkSlots {
  default: (_: Reactive<UseNetworkReturn>) => any;
}
interface UseNowSlots {
  default: (_: Reactive<UseNowReturn<true>>) => any;
}
interface UseObjectUrlSlots {
  default: (_: Readonly<string | undefined>) => any;
}
interface UseOffsetPaginationSlots {
  default: (_: Reactive<UseOffsetPaginationReturn>) => any;
}
interface UseOnlineSlots {
  default: (_: Reactive<{
    isOnline: UseNetworkReturn['isOnline'];
  }>) => any;
}
interface UsePageLeaveSlots {
  default: (_: Reactive<{
    isLeft: UsePageLeaveReturn;
  }>) => any;
}
interface UsePointerLockSlots {
  default: (_: Reactive<UsePointerLockReturn>) => any;
}
interface UsePointerSlots {
  default: (_: Reactive<UsePointerReturn>) => any;
}
interface UsePreferredColorSchemeSlots {
  default: (_: Reactive<{
    colorScheme: ComputedRef<ColorSchemeType>;
  }>) => any;
}
interface UsePreferredContrastSlots {
  default: (_: Reactive<{
    contrast: ComputedRef<ContrastType>;
  }>) => any;
}
interface UsePreferredDarkSlots {
  default: (_: Reactive<{
    prefersDark: ComputedRef<boolean>;
  }>) => any;
}
interface UsePreferredLanguagesSlots {
  default: (_: Reactive<{
    languages: Ref<readonly string[]>;
  }>) => any;
}
interface UsePreferredReducedMotionSlots {
  default: (_: Reactive<{
    motion: ComputedRef<ReducedMotionType>;
  }>) => any;
}
interface UseScreenSafeAreaSlots {
  default: (_: Reactive<UseScreenSafeAreaReturn>) => any;
}
interface UseTimeAgoSlots {
  default: (_: Reactive<UseTimeAgoReturn<true>>) => any;
}
interface UseTimestampSlots {
  default: (_: Reactive<UseTimestampReturn<true>>) => any;
}
interface UseWindowFocusSlots {
  default: (_: Reactive<{
    focused: ShallowRef<boolean>;
  }>) => any;
}
interface UseWindowSizeSlots {
  default: (_: Reactive<UseWindowSizeReturn>) => any;
}
// #endregion