/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useFocusTrap/component` */
// Interfaces
export interface ComponentUseFocusTrapOptions extends UseFocusTrapProps {}
export interface UseFocusTrapProps extends RenderableComponent {
  options?: UseFocusTrapOptions;
}

// Variables
export declare const UseFocusTrap: vue.DefineSetupFnComponent<UseFocusTrapProps, Record<string, never>, SlotsType<UseFocusTrapSlots>, UseFocusTrapProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, vue.PublicProps>;