/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useFocusTrap/component`
 */
// #region Interfaces
/** @deprecated */
export interface ComponentUseFocusTrapOptions extends UseFocusTrapProps {}
export interface UseFocusTrapProps extends RenderableComponent {
  options?: UseFocusTrapOptions;
}
// #endregion

// #region Variables
export declare const UseFocusTrap: import("vue").DefineSetupFnComponent<UseFocusTrapProps, Record<string, never>, SlotsType<UseFocusTrapSlots>, UseFocusTrapProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, import("vue").PublicProps>;
// #endregion