/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useFocusTrap/component`
 */
// #region Interfaces
export interface ComponentUseFocusTrapOptions extends UseFocusTrapProps {}
export interface UseFocusTrapProps extends RenderableComponent {
  options?: UseFocusTrapOptions;
}
// #endregion

// #region Variables
export declare const UseFocusTrap: _$vue.DefineSetupFnComponent<UseFocusTrapProps, Record<string, never>, SlotsType<UseFocusTrapSlots>, UseFocusTrapProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, _$vue.PublicProps>;
// #endregion