/**
 * Generated by tsnapi — public API snapshot of `@vueuse/metadata`
 */
// #region Interfaces
export interface CommitInfo {
  functions: string[];
  version?: string;
  hash: string;
  date: string;
  message: string;
  refs?: string;
  body?: string;
  author_name: string;
  author_email: string;
}
export interface ContributorInfo {
  name: string;
  count: number;
  hash: string;
}
export interface PackageIndexes {
  packages: Record<string, VueUsePackage>;
  categories: string[];
  functions: VueUseFunction[];
}
export interface PackageManifest {
  name: string;
  display: string;
  addon?: boolean;
  author?: string;
  description?: string;
  external?: string[];
  globals?: Record<string, string>;
  manualImport?: boolean;
  deprecated?: boolean;
  submodules?: boolean;
  build?: boolean;
  iife?: boolean;
  mjs?: boolean;
  dts?: boolean;
  target?: string;
  utils?: boolean;
  copy?: string[];
}
export interface VueUseFunction {
  name: string;
  package: string;
  importPath?: string;
  lastUpdated?: number;
  category?: string;
  description?: string;
  docs?: string;
  deprecated?: boolean;
  internal?: boolean;
  component?: boolean;
  directive?: boolean;
  external?: string;
  alias?: string[];
  related?: string[];
  variants?: string[];
}
export interface VueUsePackage extends PackageManifest {
  dir: string;
  docs?: string;
}
// #endregion

// #region Functions
export declare function getCategories(_: VueUseFunction[]): string[];
export declare function getFunction(_: string): VueUseFunction | undefined;
export declare function uniq<T extends any[]>(_: T): any[];
// #endregion

// #region Variables
export declare const addonCategoryNames: string[];
export declare const categories: PackageIndexes["categories"];
export declare const categoryNames: string[];
export declare const coreCategoryNames: string[];
export declare const functionNames: string[];
export declare const functions: PackageIndexes["functions"];
export declare const metadata: PackageIndexes;
export declare const packages: PackageIndexes["packages"];
// #endregion