export const KEYBOARD_MAP = {
  Digit1: true,
  Digit2: true,
  Digit3: true,
  Digit4: true,
  Digit5: true,
  Digit6: true,
  Digit7: true,
  Digit8: true,
  Digit9: true,
  Numpad1: true,
  Numpad2: true,
  Numpad3: true,
  Numpad4: true,
  Numpad5: true,
  Numpad6: true,
  Numpad7: true,
  Numpad8: true,
  Numpad9: true,
  Space: true,
  KeyA: true,
  KeyB: true,
  KeyC: true,
  KeyD: true,
  KeyE: true,
  KeyF: true,
  KeyG: true,
  KeyH: true,
  KeyI: true,
  KeyJ: true,
  KeyK: true,
  KeyL: true,
  KeyM: true,
  KeyN: true,
  KeyO: true,
  KeyP: true,
  KeyQ: true,
  KeyR: true,
  KeyS: true,
  KeyT: true,
  KeyU: true,
  KeyV: true,
  KeyW: true,
  KeyX: true,
  KeyY: true,
  KeyZ: true,
  // 以下按键视为不是文本输入，而是用户的特殊操作，需要处理
  Backspace: true,
  ArrowUp: true,
  ArrowDown: true,
}

export function isSupportKey(e: KeyboardEvent): boolean {
  return Object.prototype.hasOwnProperty.call(KEYBOARD_MAP, e.code)
}
