/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useAsyncValidator`
 */
// #region Interfaces
export interface UseAsyncValidatorExecuteReturn {
  pass: boolean;
  errors: AsyncValidatorError['errors'] | undefined;
  errorInfo: AsyncValidatorError | null;
  errorFields: AsyncValidatorError['fields'] | undefined;
}
export interface UseAsyncValidatorOptions {
  validateOption?: ValidateOption;
  immediate?: boolean;
  manual?: boolean;
}
export interface UseAsyncValidatorReturn {
  pass: ShallowRef<boolean>;
  isFinished: ShallowRef<boolean>;
  errors: ComputedRef<AsyncValidatorError['errors'] | undefined>;
  errorInfo: ShallowRef<AsyncValidatorError | null>;
  errorFields: ComputedRef<AsyncValidatorError['fields'] | undefined>;
  execute: () => Promise<UseAsyncValidatorExecuteReturn>;
}
// #endregion

// #region Types
export type AsyncValidatorError = Error & {
  errors: ValidateError[];
  fields: Record<string, ValidateError[]>;
};
// #endregion

// #region Functions
export declare function useAsyncValidator(_: MaybeRefOrGetter<Record<string, any>>, _: MaybeRefOrGetter<Rules>, _?: UseAsyncValidatorOptions): UseAsyncValidatorReturn & PromiseLike<UseAsyncValidatorReturn>;
// #endregion