/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useAxios`
 */
// #region Interfaces
export interface EasyUseAxiosReturn<T, R, D> extends UseAxiosReturn<T, R, D> {
  execute: (_: string, _?: AxiosRequestConfig<D>) => Promise<EasyUseAxiosReturn<T, R, D>>;
}
export interface StrictUseAxiosReturn<T, R, D, O extends UseAxiosOptions = UseAxiosOptions<T>> extends UseAxiosReturn<T, R, D, O> {
  execute: (_?: string | AxiosRequestConfig<D>, _?: AxiosRequestConfig<D>) => Promise<StrictUseAxiosReturn<T, R, D, O>>;
}
export interface UseAxiosOptionsBase<T = any> {
  immediate?: boolean;
  shallow?: boolean;
  abortPrevious?: boolean;
  onError?: (_: unknown) => void;
  onSuccess?: (_: T) => void;
  resetOnExecute?: boolean;
  onFinish?: () => void;
}
export interface UseAxiosOptionsWithInitialData<T> extends UseAxiosOptionsBase<T> {
  initialData: T;
}
export interface UseAxiosReturn<T, R = AxiosResponse<T>, _D = any, O extends UseAxiosOptions = UseAxiosOptions<T>> {
  response: ShallowRef<R | undefined>;
  data: O extends UseAxiosOptionsWithInitialData<T> ? Ref<T> : Ref<T | undefined>;
  isFinished: Ref<boolean>;
  isLoading: Ref<boolean>;
  isAborted: Ref<boolean>;
  error: ShallowRef<unknown | undefined>;
  abort: (_?: string | undefined) => void;
  cancel: (_?: string | undefined) => void;
  isCanceled: Ref<boolean>;
}
// #endregion

// #region Types
export type UseAxiosOptions<T = any> = UseAxiosOptionsBase<T> | UseAxiosOptionsWithInitialData<T>;
// #endregion

// #region Functions
export declare function useAxios<T = any, R = AxiosResponse<T>, D = any>(_?: AxiosRequestConfig<D>, _?: AxiosInstance): EasyUseAxiosReturn<T, R, D> & Promise<EasyUseAxiosReturn<T, R, D>>;
// #endregion