/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useChangeCase`
 */
// #region Types
export type ChangeCaseType = ChangeCaseKeys[keyof ChangeCaseKeys];
// #endregion

// #region Functions
export declare function useChangeCase(_: MaybeRefOrGetter<string>, _: MaybeRefOrGetter<ChangeCaseType>, _?: MaybeRefOrGetter<Options> | undefined): ComputedRef<string>;
// #endregion