/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useCookies`
 */
// #region Functions
export declare function createCookies(_?: IncomingMessage): (_?: string[] | null, { doNotParse, autoUpdateDependencies }?: {
  doNotParse?: boolean | undefined;
  autoUpdateDependencies?: boolean | undefined;
}) => {
  get: <T = any>(_: string, _?: import("universal-cookie").CookieGetOptions | undefined) => T;
  getAll: <T = any>(_?: import("universal-cookie").CookieGetOptions | undefined) => T;
  set: (_: string, _: any, _?: import("universal-cookie").CookieSetOptions | undefined) => void;
  remove: (_: string, _?: import("universal-cookie").CookieSetOptions | undefined) => void;
  addChangeListener: (_: import("universal-cookie").CookieChangeListener) => void;
  removeChangeListener: (_: import("universal-cookie").CookieChangeListener) => void;
};
export declare function useCookies(_?: string[] | null, { doNotParse, autoUpdateDependencies }?: {
  doNotParse?: boolean | undefined;
  autoUpdateDependencies?: boolean | undefined;
}, _?: Cookie): {
  get: <T = any>(_: string, _?: import("universal-cookie").CookieGetOptions | undefined) => T;
  getAll: <T = any>(_?: import("universal-cookie").CookieGetOptions | undefined) => T;
  set: (_: string, _: any, _?: import("universal-cookie").CookieSetOptions | undefined) => void;
  remove: (_: string, _?: import("universal-cookie").CookieSetOptions | undefined) => void;
  addChangeListener: (_: import("universal-cookie").CookieChangeListener) => void;
  removeChangeListener: (_: import("universal-cookie").CookieChangeListener) => void;
};
// #endregion