/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useCookies`
 */
// #region Functions
export declare function createCookies(_?: IncomingMessage): (_?: string[] | null, {
  doNotParse,
  autoUpdateDependencies
}?: {
  doNotParse?: boolean | undefined;
  autoUpdateDependencies?: boolean | undefined;
}) => {
  get: <T = any>(_: string, _?: _$universal_cookie0.CookieGetOptions | undefined) => T;
  getAll: <T = any>(_?: _$universal_cookie0.CookieGetOptions | undefined) => T;
  set: (_: string, _: any, _?: _$universal_cookie0.CookieSetOptions | undefined) => void;
  remove: (_: string, _?: _$universal_cookie0.CookieSetOptions | undefined) => void;
  addChangeListener: (_: _$universal_cookie0.CookieChangeListener) => void;
  removeChangeListener: (_: _$universal_cookie0.CookieChangeListener) => void;
};
export declare function useCookies(_?: string[] | null, {
  doNotParse,
  autoUpdateDependencies
}?: {
  doNotParse?: boolean | undefined;
  autoUpdateDependencies?: boolean | undefined;
}, _?: Cookie): {
  get: <T = any>(_: string, _?: _$universal_cookie0.CookieGetOptions | undefined) => T;
  getAll: <T = any>(_?: _$universal_cookie0.CookieGetOptions | undefined) => T;
  set: (_: string, _: any, _?: _$universal_cookie0.CookieSetOptions | undefined) => void;
  remove: (_: string, _?: _$universal_cookie0.CookieSetOptions | undefined) => void;
  addChangeListener: (_: _$universal_cookie0.CookieChangeListener) => void;
  removeChangeListener: (_: _$universal_cookie0.CookieChangeListener) => void;
};
// #endregion