/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useChangeCase` */
// Types
export type ChangeCaseType = ChangeCaseKeys[keyof ChangeCaseKeys];

// Functions
export declare function useChangeCase(_: MaybeRefOrGetter<string>, _: MaybeRefOrGetter<ChangeCaseType>, _?: MaybeRefOrGetter<Options> | undefined): ComputedRef<string>;