/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useDrauu` */
// Interfaces
export interface UseDrauuReturn {
  drauuInstance: Ref<Drauu | undefined>;
  load: (_: string) => void;
  dump: () => string | undefined;
  clear: () => void;
  cancel: () => void;
  undo: () => boolean | undefined;
  redo: () => boolean | undefined;
  canUndo: ShallowRef<boolean>;
  canRedo: ShallowRef<boolean>;
  brush: Ref<Brush>;
  onChanged: EventHookOn;
  onCommitted: EventHookOn;
  onStart: EventHookOn;
  onEnd: EventHookOn;
  onCanceled: EventHookOn;
}

// Types
export type UseDrauuOptions = Omit<Options, 'el'>;

// Functions
export declare function useDrauu(_: MaybeComputedElementRef, _?: UseDrauuOptions): UseDrauuReturn;