/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useFocusTrap`
 */
// #region Interfaces
export interface UseFocusTrapOptions extends Options {
  immediate?: boolean;
}
export interface UseFocusTrapReturn {
  hasFocus: ShallowRef<boolean>;
  isPaused: ShallowRef<boolean>;
  activate: (_?: ActivateOptions) => void;
  deactivate: (_?: DeactivateOptions) => void;
  pause: Fn;
  unpause: Fn;
}
// #endregion

// #region Functions
export declare function useFocusTrap(_: MaybeRefOrGetter<Arrayable<MaybeRefOrGetter<string> | MaybeComputedElementRef>>, _?: UseFocusTrapOptions): UseFocusTrapReturn;
// #endregion