/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useFuse`
 */
// #region Interfaces
export interface UseFuseOptions<T> {
  fuseOptions?: FuseOptions<T>;
  resultLimit?: number;
  matchAllWhenSearchEmpty?: boolean;
}
export interface UseFuseReturn<DataItem> {
  fuse: Ref<Fuse<DataItem>>;
  results: ComputedRef<FuseResult<DataItem>[]>;
}
// #endregion

// #region Types
export type FuseOptions<T> = IFuseOptions<T>;
// #endregion

// #region Functions
export declare function useFuse<DataItem>(_: MaybeRefOrGetter<string>, _: MaybeRefOrGetter<DataItem[]>, _?: MaybeRefOrGetter<UseFuseOptions<DataItem>>): UseFuseReturn<DataItem>;
// #endregion