/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useIDBKeyval`
 */
// #region Interfaces
export interface UseIDBKeyvalReturn<T> {
  data: RemovableRef<T>;
  isFinished: ShallowRef<boolean>;
  set: (_: T) => Promise<void>;
}
export interface UseIDBOptions<T> extends ConfigurableFlush {
  deep?: boolean;
  onError?: (_: unknown) => void;
  shallow?: boolean;
  writeDefaults?: boolean;
  serializer?: Serializer<T>;
}
// #endregion

// #region Functions
export declare function useIDBKeyval<T>(_: IDBValidKey, _: MaybeRefOrGetter<T>, _?: UseIDBOptions<T>): UseIDBKeyvalReturn<T>;
// #endregion