/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useJwt`
 */
// #region Interfaces
export interface UseJwtOptions<Fallback> {
  fallbackValue?: Fallback;
  onError?: (_: unknown) => void;
}
export interface UseJwtReturn<Payload, Header, Fallback> {
  header: ComputedRef<Header | Fallback>;
  payload: ComputedRef<Payload | Fallback>;
}
// #endregion

// #region Functions
export declare function useJwt<Payload extends object = JwtPayload, Header extends object = JwtHeader, Fallback = null>(_: MaybeRefOrGetter<string>, _?: UseJwtOptions<Fallback>): UseJwtReturn<Payload, Header, Fallback>;
// #endregion