/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useNProgress` */
// Interfaces
export interface UseNProgressReturn {
  isLoading: WritableComputedRef<boolean, boolean>;
  progress: Ref<number | null | undefined>;
  start: () => NProgress;
  done: (_?: boolean) => NProgress;
  remove: () => void;
}

// Types
export type UseNProgressOptions = Partial<NProgressOptions>;

// Functions
export declare function useNProgress(_?: MaybeRefOrGetter<number | null | undefined>, _?: UseNProgressOptions): UseNProgressReturn;