/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useNProgress`
 */
// #region Interfaces
export interface UseNProgressReturn {
  isLoading: WritableComputedRef<boolean, boolean>;
  progress: Ref<number | null | undefined>;
  start: () => NProgress;
  done: (_?: boolean) => NProgress;
  remove: () => void;
}
// #endregion

// #region Types
export type UseNProgressOptions = Partial<NProgressOptions>;
// #endregion

// #region Functions
export declare function useNProgress(_?: MaybeRefOrGetter<number | null | undefined>, _?: UseNProgressOptions): UseNProgressReturn;
// #endregion