/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useQRCode`
 */
// #region Functions
export declare function useQRCode(_: MaybeRefOrGetter<string>, _?: QRCode.QRCodeToDataURLOptions): import("vue").ShallowRef<string, string>;
// #endregion