/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useSortable`
 */
// #region Interfaces
export interface UseSortableOptions extends Options, ConfigurableDocument {
  watchElement?: boolean;
}
export interface UseSortableReturn {
  start: () => void;
  stop: () => void;
  option: (<K extends keyof Sortable.Options>(_: K, _: Sortable.Options[K]) => void) & (<K extends keyof Sortable.Options>(_: K) => Sortable.Options[K]);
}
// #endregion

// #region Functions
export declare function insertNodeAt(_: Element, _: Element, _: number): void;
export declare function moveArrayElement<T>(_: MaybeRef<T[]>, _: number, _: number, _?: Sortable.SortableEvent | null): void;
export declare function removeNode(_: Node): void;
export declare function useSortable<T>(_: MaybeRefOrGetter<MaybeElement>, _: MaybeRef<T[]>, _?: UseSortableOptions): UseSortableReturn;
// #endregion