/**
 * Generated by tsnapi — public API snapshot of `@vueuse/core`
 */
// #region Interfaces
export interface AfterFetchContext<T = any> {
  response: Response;
  data: T | null;
  context: BeforeFetchContext;
  execute: (_?: boolean) => Promise<any>;
}
export interface AsyncComputedOptions<Lazy = boolean> extends ConfigurableFlushSync {
  lazy?: Lazy;
  evaluating?: Ref<boolean>;
  shallow?: boolean;
  onError?: (_: unknown) => void;
}
export interface BatteryManager extends EventTarget {
  charging: boolean;
  chargingTime: number;
  dischargingTime: number;
  level: number;
}
export interface BeforeFetchContext {
  url: string;
  options: RequestInit;
  cancel: Fn;
}
export interface BrowserLocationState {
  readonly trigger: string;
  readonly state?: any;
  readonly length?: number;
  readonly origin?: string;
  hash?: string;
  host?: string;
  hostname?: string;
  href?: string;
  pathname?: string;
  port?: string;
  protocol?: string;
  search?: string;
}
export interface ConfigurableDeepRefs<D extends boolean> {
  deepRefs?: D;
}
export interface ConfigurableDocument {
  document?: Document;
}
export interface ConfigurableDocumentOrShadowRoot {
  document?: DocumentOrShadowRoot;
}
export interface ConfigurableLocation {
  location?: Location;
}
export interface ConfigurableNavigator {
  navigator?: Navigator;
}
export interface ConfigurableScheduler {
  scheduler?: (_: Fn) => Pausable;
}
export interface ConfigurableWindow {
  window?: Window;
}
export interface CreateFetchOptions {
  baseUrl?: MaybeRefOrGetter<string>;
  combination?: Combination;
  options?: UseFetchOptions;
  fetchOptions?: RequestInit;
}
export interface CreateReusableTemplateOptions<Props extends Record<string, any>> {
  inheritAttrs?: boolean;
  name?: string;
  props?: ComponentObjectPropsOptions<Props>;
}
export interface ElementSize {
  width: number;
  height: number;
}
export interface EventBusKey<T> extends Symbol {}
export interface EyeDropper {
  new (): EyeDropper;
  open: (_?: EyeDropperOpenOptions) => Promise<{
    sRGBHex: string;
  }>;
  [Symbol.toStringTag]: 'EyeDropper';
}
export interface EyeDropperOpenOptions {
  signal?: AbortSignal;
}
export interface FileSystemAccessShowOpenFileOptions {
  multiple?: boolean;
  types?: Array<{
    description?: string;
    accept: Record<string, string[]>;
  }>;
  excludeAcceptAllOption?: boolean;
}
export interface FileSystemAccessShowSaveFileOptions {
  suggestedName?: string;
  types?: Array<{
    description?: string;
    accept: Record<string, string[]>;
  }>;
  excludeAcceptAllOption?: boolean;
}
export interface FileSystemFileHandle {
  getFile: () => Promise<File>;
  createWritable: () => FileSystemWritableFileStream;
}
export interface FormatTimeAgoIntlOptions {
  locale?: Locale;
  relativeTimeFormatOptions?: Intl.RelativeTimeFormatOptions;
  insertSpace?: boolean;
  joinParts?: (_: Intl.RelativeTimeFormatPart[], _?: Intl.UnicodeBCP47LocaleIdentifier | Intl.Locale) => string;
  units?: TimeAgoUnit[];
}
export interface FormatTimeAgoOptions<UnitNames extends string = UseTimeAgoUnitNamesDefault> {
  max?: UnitNames | number;
  fullDateFormatter?: (_: Date) => string;
  messages?: UseTimeAgoMessages<UnitNames>;
  showSecond?: boolean;
  rounding?: 'round' | 'ceil' | 'floor' | number;
  units?: UseTimeAgoUnit<UnitNames>[];
}
export interface GeneralEventListener<E = Event> {
  (_: E): void;
}
export interface MagicKeysInternal {
  current: Set<string>;
}
export interface MemoryInfo {
  readonly jsHeapSizeLimit: number;
  readonly totalJSHeapSize: number;
  readonly usedJSHeapSize: number;
  [Symbol.toStringTag]: 'MemoryInfo';
}
export interface MouseInElementOptions extends UseMouseOptions {
  handleOutside?: boolean;
  windowScroll?: boolean;
  windowResize?: boolean;
}
export interface NavigatorLanguageState extends Supportable {
  language: ShallowRef<string | undefined>;
}
export interface NetworkState extends Supportable {
  isOnline: Readonly<ShallowRef<boolean>>;
  offlineAt: Readonly<ShallowRef<number | undefined>>;
  onlineAt: Readonly<ShallowRef<number | undefined>>;
  downlink: Readonly<ShallowRef<number | undefined>>;
  downlinkMax: Readonly<ShallowRef<number | undefined>>;
  effectiveType: Readonly<ShallowRef<NetworkEffectiveType | undefined>>;
  rtt: Readonly<ShallowRef<number | undefined>>;
  saveData: Readonly<ShallowRef<boolean | undefined>>;
  type: Readonly<ShallowRef<NetworkType>>;
}
export interface OnClickOutsideOptions<Controls extends boolean = false> extends ConfigurableWindow {
  ignore?: MaybeRefOrGetter<(MaybeElementRef | string)[]>;
  capture?: boolean;
  detectIframe?: boolean;
  controls?: Controls;
}
export interface OnElementRemovalOptions extends ConfigurableWindow, ConfigurableDocumentOrShadowRoot, WatchOptionsBase {}
export interface OnFetchErrorContext<T = any, E = any> {
  error: E;
  data: T | null;
  response: Response | null;
  context: BeforeFetchContext;
  execute: (_?: boolean) => Promise<any>;
}
export interface OnKeyStrokeOptions {
  eventName?: KeyStrokeEventName;
  target?: MaybeRefOrGetter<EventTarget | null | undefined>;
  passive?: boolean;
  dedupe?: MaybeRefOrGetter<boolean>;
}
export interface OnLongPressModifiers {
  stop?: boolean;
  once?: boolean;
  prevent?: boolean;
  capture?: boolean;
  self?: boolean;
}
export interface OnLongPressOptions {
  delay?: number | ((_: PointerEvent) => number);
  modifiers?: OnLongPressModifiers;
  distanceThreshold?: number | false;
  onMouseUp?: (_: number, _: number, _: boolean, _: PointerEvent) => void;
}
export interface Position {
  x: number;
  y: number;
}
export interface RenderableComponent {
  as?: object | string;
}
export interface ResizeObserverEntry {
  readonly target: Element;
  readonly contentRect: DOMRectReadOnly;
  readonly borderBoxSize: ReadonlyArray<ResizeObserverSize>;
  readonly contentBoxSize: ReadonlyArray<ResizeObserverSize>;
  readonly devicePixelContentBoxSize: ReadonlyArray<ResizeObserverSize>;
}
export interface ResizeObserverSize {
  readonly inlineSize: number;
  readonly blockSize: number;
}
export interface ScreenOrientation extends EventTarget {
  lock: (_: OrientationLockType) => Promise<void>;
  unlock: () => void;
  readonly type: OrientationType;
  readonly angle: number;
  addEventListener: (_: 'change', _: (this: this, _: Event) => any, _?: boolean) => void;
}
export interface Serializer<T> {
  read: (_: string) => T;
  write: (_: T) => string;
}
export interface SerializerAsync<T> {
  read: (_: string) => Awaitable<T>;
  write: (_: T) => Awaitable<string>;
}
export interface SSRHandlersMap {
  getDefaultStorage: () => StorageLike | undefined;
  getDefaultStorageAsync: () => StorageLikeAsync | undefined;
  updateHTMLAttrs: (_: string | MaybeElementRef, _: string, _: string) => void;
}
export interface StorageEventLike {
  storageArea: StorageLike | null;
  key: StorageEvent['key'];
  oldValue: StorageEvent['oldValue'];
  newValue: StorageEvent['newValue'];
}
export interface StorageLike {
  getItem: (_: string) => string | null;
  setItem: (_: string, _: string) => void;
  removeItem: (_: string) => void;
}
export interface StorageLikeAsync {
  getItem: (_: string) => Awaitable<string | null>;
  setItem: (_: string, _: string) => Awaitable<void>;
  removeItem: (_: string) => Awaitable<void>;
}
export interface Supportable {
  isSupported: ComputedRef<boolean>;
}
export interface TemplatePromiseOptions {
  singleton?: boolean;
  transition?: TransitionGroupProps;
}
export interface TemplatePromiseProps<Return, Args extends any[] = []> {
  promise: Promise<Return> | undefined;
  resolve: (_: Return | Promise<Return>) => void;
  reject: (_: any) => void;
  args: Args;
  isResolving: boolean;
  options: TemplatePromiseOptions;
  key: number;
}
export interface TimeAgoUnit {
  name: Intl.RelativeTimeFormatUnit;
  ms: number;
}
export interface ToDataURLOptions extends UseBase64Options {
  type?: string | undefined;
  quality?: any;
}
export interface TransitionOptions<T> extends ConfigurableWindow {
  abort?: () => any;
  duration?: MaybeRef<number>;
  easing?: MaybeRef<EasingFunction | CubicBezierPoints>;
  interpolation?: InterpolationFunction<T>;
  transition?: MaybeRef<EasingFunction | CubicBezierPoints>;
}
export interface UseActiveElementOptions extends ConfigurableWindow, ConfigurableDocumentOrShadowRoot {
  deep?: boolean;
  triggerOnRemoval?: boolean;
}
export interface UseAnimateOptions extends KeyframeAnimationOptions, ConfigurableWindow {
  immediate?: boolean;
  commitStyles?: boolean;
  persist?: boolean;
  onReady?: (_: Animation) => void;
  onError?: (_: unknown) => void;
}
export interface UseAnimateReturn extends Supportable {
  animate: ShallowRef<Animation | undefined>;
  play: () => void;
  pause: () => void;
  reverse: () => void;
  finish: () => void;
  cancel: () => void;
  pending: ComputedRef<boolean>;
  playState: ComputedRef<AnimationPlayState>;
  replaceState: ComputedRef<AnimationReplaceState>;
  startTime: WritableComputedRef<CSSNumberish | number | null>;
  currentTime: WritableComputedRef<CSSNumberish | null>;
  timeline: WritableComputedRef<AnimationTimeline | null>;
  playbackRate: WritableComputedRef<number>;
}
export interface UseAsyncQueueOptions {
  interrupt?: boolean;
  onError?: () => void;
  onFinished?: () => void;
  signal?: AbortSignal;
}
export interface UseAsyncQueueResult<T> {
  state: 'aborted' | 'fulfilled' | 'pending' | 'rejected';
  data: T | null;
}
export interface UseAsyncQueueReturn<T> {
  activeIndex: ShallowRef<number>;
  result: T;
}
export interface UseAsyncStateOptions<Shallow extends boolean, D = any> {
  delay?: number;
  immediate?: boolean;
  onError?: (_: unknown) => void;
  onSuccess?: (_: D) => void;
  resetOnExecute?: boolean;
  shallow?: Shallow;
  throwError?: boolean;
}
export interface UseAsyncStateReturnBase<Data, Params extends any[], Shallow extends boolean> {
  state: Shallow extends true ? Ref<Data> : Ref<UnwrapRef<Data>>;
  isReady: Ref<boolean>;
  isLoading: Ref<boolean>;
  error: Ref<unknown>;
  execute: (_?: number, ..._: Params) => Promise<Data | undefined>;
  executeImmediate: (..._: Params) => Promise<Data | undefined>;
}
export interface UseBase64ObjectOptions<T> extends UseBase64Options {
  serializer?: (_: T) => string;
}
export interface UseBase64Options {
  dataUrl?: boolean;
}
export interface UseBase64Return {
  base64: ShallowRef<string>;
  promise: ShallowRef<Promise<string>>;
  execute: () => Promise<string>;
}
export interface UseBatteryOptions extends ConfigurableNavigator {}
export interface UseBatteryReturn extends Supportable {
  charging: ShallowRef<boolean>;
  chargingTime: ShallowRef<number>;
  dischargingTime: ShallowRef<number>;
  level: ShallowRef<number>;
}
export interface UseBluetoothOptions extends UseBluetoothRequestDeviceOptions, ConfigurableNavigator {
  acceptAllDevices?: boolean;
}
export interface UseBluetoothRequestDeviceOptions {
  filters?: BluetoothLEScanFilter[] | undefined;
  optionalServices?: BluetoothServiceUUID[] | undefined;
}
export interface UseBluetoothReturn extends Supportable {
  isConnected: Readonly<ShallowRef<boolean>>;
  device: ShallowRef<BluetoothDevice | undefined>;
  requestDevice: () => Promise<void>;
  server: ShallowRef<BluetoothRemoteGATTServer | undefined>;
  error: ShallowRef<unknown | null>;
}
export interface UseBreakpointsOptions extends ConfigurableWindow {
  strategy?: 'min-width' | 'max-width';
  ssrWidth?: number;
}
export interface UseBroadcastChannelOptions extends ConfigurableWindow {
  name: string;
}
export interface UseBroadcastChannelReturn<D, P> extends Supportable {
  channel: ShallowRef<BroadcastChannel | undefined>;
  data: ShallowRef<D>;
  post: (_: P) => void;
  close: () => void;
  error: ShallowRef<Event | null>;
  isClosed: ShallowRef<boolean>;
}
export interface UseBrowserLocationOptions extends ConfigurableWindow {}
export interface UseCachedOptions<D extends boolean = true> extends ConfigurableDeepRefs<D>, WatchOptions {}
export interface UseClipboardItemsOptions<Source> extends ConfigurableNavigator {
  read?: boolean;
  source?: Source;
  copiedDuring?: number;
}
export interface UseClipboardItemsReturn<Optional> extends Supportable {
  content: Readonly<Ref<ClipboardItems>>;
  copied: Readonly<ShallowRef<boolean>>;
  copy: Optional extends true ? (content?: ClipboardItems) => Promise<void> : (text: ClipboardItems) => Promise<void>;
  read: () => void;
}
export interface UseClipboardOptions<Source> extends ConfigurableNavigator {
  read?: boolean;
  source?: Source;
  copiedDuring?: number;
  legacy?: boolean;
}
export interface UseClipboardReturn<Optional> extends Supportable {
  text: Readonly<ShallowRef<string>>;
  copied: Readonly<ShallowRef<boolean>>;
  copyPending: Readonly<ShallowRef<boolean>>;
  copy: Optional extends true ? (text?: ClipboardValue) => Promise<void> : (text: ClipboardValue) => Promise<void>;
}
export interface UseClonedOptions<T = any> extends WatchOptions {
  clone?: (_: T) => T;
  manual?: boolean;
}
export interface UseClonedReturn<T> {
  cloned: Ref<T>;
  isModified: Ref<boolean>;
  sync: () => void;
}
export interface UseColorModeOptions<T extends string = BasicColorMode> extends UseStorageOptions<T | BasicColorMode> {
  selector?: string | MaybeElementRef;
  attribute?: string;
  initialValue?: MaybeRefOrGetter<T | BasicColorSchema>;
  modes?: Partial<Record<T | BasicColorSchema, string>>;
  onChanged?: (_: T | BasicColorMode, _: ((_: T | BasicColorMode) => void)) => void;
  storageRef?: Ref<T | BasicColorSchema>;
  storageKey?: string | null;
  storage?: StorageLike;
  emitAuto?: boolean;
  disableTransition?: boolean;
}
export interface UseConfirmDialogReturn<RevealData, ConfirmData, CancelData> {
  isRevealed: ComputedRef<boolean>;
  reveal: (_?: RevealData) => Promise<UseConfirmDialogRevealResult<ConfirmData, CancelData>>;
  confirm: (_?: ConfirmData) => void;
  cancel: (_?: CancelData) => void;
  onReveal: EventHookOn<RevealData>;
  onConfirm: EventHookOn<ConfirmData>;
  onCancel: EventHookOn<CancelData>;
}
export interface UseCountdownOptions extends ConfigurableScheduler {
  interval?: MaybeRefOrGetter<number>;
  onComplete?: () => void;
  onTick?: () => void;
  immediate?: boolean;
}
export interface UseCountdownReturn extends Pausable {
  remaining: ShallowRef<number>;
  reset: (_?: MaybeRefOrGetter<number>) => void;
  stop: () => void;
  start: (_?: MaybeRefOrGetter<number>) => void;
}
export interface UseCssSupportsOptions extends ConfigurableWindow {
  ssrValue?: boolean;
}
export interface UseCssSupportsReturn extends Supportable {}
export interface UseCssVarOptions extends ConfigurableWindow {
  initialValue?: string;
  observe?: boolean;
}
export interface UseCycleListOptions<T> {
  initialValue?: MaybeRef<T>;
  fallbackIndex?: number;
  getIndexOf?: (_: T, _: T[]) => number;
}
export interface UseCycleListReturn<T> {
  state: ShallowRef<T>;
  index: WritableComputedRef<number>;
  next: (_?: number) => T;
  prev: (_?: number) => T;
  go: (_: number) => T;
}
export interface UseDarkOptions extends Omit<UseColorModeOptions<BasicColorSchema>, 'modes' | 'onChanged'> {
  valueDark?: string;
  valueLight?: string;
  onChanged?: (_: boolean, _: ((_: BasicColorSchema) => void), _: BasicColorSchema) => void;
}
export interface UseDeviceMotionOptions extends ConfigurableWindow, ConfigurableEventFilter {
  requestPermissions?: boolean;
}
export interface UseDeviceMotionReturn extends Supportable {
  acceleration: Ref<DeviceMotionEventAcceleration | null>;
  accelerationIncludingGravity: Ref<DeviceMotionEventAcceleration | null>;
  rotationRate: Ref<DeviceMotionEventRotationRate | null>;
  interval: ShallowRef<number>;
  requirePermissions: ComputedRef<boolean>;
  ensurePermissions: () => Promise<void>;
  permissionGranted: ShallowRef<boolean>;
}
export interface UseDeviceOrientationOptions extends ConfigurableWindow {}
export interface UseDeviceOrientationReturn extends Supportable {
  isAbsolute: ShallowRef<boolean, boolean>;
  alpha: Ref<number | null, number | null>;
  beta: Ref<number | null, number | null>;
  gamma: Ref<number | null, number | null>;
}
export interface UseDevicePixelRatioOptions extends ConfigurableWindow {}
export interface UseDevicePixelRatioReturn {
  pixelRatio: Readonly<ShallowRef<number>>;
  stop: WatchStopHandle;
}
export interface UseDevicesListOptions extends ConfigurableNavigator {
  onUpdated?: (_: MediaDeviceInfo[]) => void;
  requestPermissions?: boolean;
  constraints?: MediaStreamConstraints;
}
export interface UseDevicesListReturn extends Supportable {
  devices: ShallowRef<MediaDeviceInfo[]>;
  videoInputs: ComputedRef<MediaDeviceInfo[]>;
  audioInputs: ComputedRef<MediaDeviceInfo[]>;
  audioOutputs: ComputedRef<MediaDeviceInfo[]>;
  permissionGranted: ShallowRef<boolean>;
  ensurePermissions: () => Promise<boolean>;
}
export interface UseDisplayMediaOptions extends ConfigurableNavigator {
  enabled?: MaybeRef<boolean>;
  video?: boolean | MediaTrackConstraints | undefined;
  audio?: boolean | MediaTrackConstraints | undefined;
}
export interface UseDisplayMediaReturn extends Supportable {
  stream: ShallowRef<MediaStream | undefined>;
  start: () => Promise<MediaStream | undefined>;
  stop: () => void;
  enabled: ShallowRef<boolean>;
}
export interface UseDocumentVisibilityOptions extends ConfigurableDocument {}
export interface UseDraggableOptions {
  exact?: MaybeRefOrGetter<boolean>;
  preventDefault?: MaybeRefOrGetter<boolean>;
  stopPropagation?: MaybeRefOrGetter<boolean>;
  capture?: boolean;
  draggingElement?: MaybeRefOrGetter<HTMLElement | SVGElement | Window | Document | null | undefined>;
  containerElement?: MaybeRefOrGetter<HTMLElement | SVGElement | null | undefined>;
  handle?: MaybeRefOrGetter<HTMLElement | SVGElement | null | undefined>;
  pointerTypes?: PointerType[];
  initialValue?: MaybeRefOrGetter<Position>;
  onStart?: (_: Position, _: PointerEvent) => void | false;
  onMove?: (_: Position, _: PointerEvent) => void;
  onEnd?: (_: Position, _: PointerEvent) => void;
  axis?: 'x' | 'y' | 'both';
  disabled?: MaybeRefOrGetter<boolean>;
  buttons?: MaybeRefOrGetter<number[]>;
  restrictInView?: MaybeRefOrGetter<boolean>;
  autoScroll?: MaybeRefOrGetter<boolean | {
    speed?: MaybeRefOrGetter<number | Position>;
    margin?: MaybeRefOrGetter<number | Position>;
    direction?: 'x' | 'y' | 'both';
  }>;
}
export interface UseDraggableReturn {
  x: Ref<number>;
  y: Ref<number>;
  position: Ref<Position>;
  isDragging: ComputedRef<boolean>;
  style: ComputedRef<string>;
}
export interface UseDropZoneOptions {
  dataTypes?: MaybeRef<readonly string[]> | ((_: readonly string[]) => boolean);
  checkValidity?: (_: DataTransferItemList) => boolean;
  onDrop?: (_: File[] | null, _: DragEvent) => void;
  onEnter?: (_: File[] | null, _: DragEvent) => void;
  onLeave?: (_: File[] | null, _: DragEvent) => void;
  onOver?: (_: File[] | null, _: DragEvent) => void;
  multiple?: boolean;
  preventDefaultForUnhandled?: boolean;
}
export interface UseDropZoneReturn {
  files: ShallowRef<File[] | null>;
  isOverDropZone: ShallowRef<boolean>;
}
export interface UseElementBoundingOptions {
  reset?: boolean;
  windowResize?: boolean;
  windowScroll?: boolean;
  immediate?: boolean;
  updateTiming?: 'sync' | 'next-frame';
}
export interface UseElementBoundingReturn {
  height: ShallowRef<number>;
  bottom: ShallowRef<number>;
  left: ShallowRef<number>;
  right: ShallowRef<number>;
  top: ShallowRef<number>;
  width: ShallowRef<number>;
  x: ShallowRef<number>;
  y: ShallowRef<number>;
  update: () => void;
}
export interface UseElementByPointOptions<Multiple extends boolean = false> extends ConfigurableDocument, ConfigurableScheduler {
  x: MaybeRefOrGetter<number>;
  y: MaybeRefOrGetter<number>;
  multiple?: MaybeRefOrGetter<Multiple>;
  immediate?: boolean;
  interval?: 'requestAnimationFrame' | number;
}
export interface UseElementByPointReturn<Multiple extends boolean = false> extends Supportable, Pausable {
  element: ShallowRef<Multiple extends true ? HTMLElement[] : HTMLElement | null>;
}
export interface UseElementHoverOptions extends ConfigurableWindow {
  delayEnter?: number;
  delayLeave?: number;
  triggerOnRemoval?: boolean;
}
export interface UseElementSizeOptions extends UseResizeObserverOptions {}
export interface UseElementSizeReturn {
  width: ShallowRef<number>;
  height: ShallowRef<number>;
  stop: () => void;
}
export interface UseElementVisibilityOptions<Controls extends boolean = false> extends ConfigurableWindow, Pick<UseIntersectionObserverOptions, 'rootMargin' | 'threshold'> {
  initialValue?: boolean;
  scrollTarget?: UseIntersectionObserverOptions['root'];
  once?: boolean;
  controls?: Controls;
}
export interface UseElementVisibilityReturnWithControls extends UseIntersectionObserverReturn {
  isVisible: ShallowRef<boolean>;
}
export interface UseEventBusReturn<T, P> {
  on: (_: EventBusListener<T, P>) => Fn;
  once: (_: EventBusListener<T, P>) => Fn;
  emit: (_?: T, _?: P) => void;
  off: (_: EventBusListener<T>) => void;
  reset: () => void;
}
export interface UseEventSourceOptions<Data> extends EventSourceInit {
  autoReconnect?: boolean | {
    retries?: number | (() => boolean);
    delay?: number;
    onFailed?: Fn;
  };
  immediate?: boolean;
  autoConnect?: boolean;
  serializer?: {
    read: (_?: string) => Data;
  };
}
export interface UseEventSourceReturn<Events extends string[], Data = any> {
  data: ShallowRef<Data | null>;
  status: ShallowRef<EventSourceStatus>;
  event: ShallowRef<Events[number] | null>;
  error: ShallowRef<Event | null>;
  close: EventSource['close'];
  open: Fn;
  eventSource: ShallowRef<EventSource | null>;
  lastEventId: ShallowRef<string | null>;
}
export interface UseEyeDropperOptions {
  initialValue?: string;
}
export interface UseEyeDropperReturn extends Supportable {
  sRGBHex: ShallowRef<string>;
  open: (_?: EyeDropperOpenOptions) => Promise<{
    sRGBHex: string;
  } | undefined>;
}
export interface UseFaviconOptions extends ConfigurableDocument {
  baseUrl?: string;
  rel?: string;
}
export interface UseFetchOptions {
  fetch?: typeof window.fetch;
  immediate?: boolean;
  refetch?: MaybeRefOrGetter<boolean>;
  initialData?: any;
  timeout?: number;
  updateDataOnError?: boolean;
  beforeFetch?: (_: BeforeFetchContext) => Promise<Partial<BeforeFetchContext> | void> | Partial<BeforeFetchContext> | void;
  afterFetch?: (_: AfterFetchContext) => Promise<Partial<AfterFetchContext>> | Partial<AfterFetchContext>;
  onFetchError?: (_: OnFetchErrorContext) => Promise<Partial<OnFetchErrorContext>> | Partial<OnFetchErrorContext>;
}
export interface UseFetchReturn<T> {
  isFinished: Readonly<ShallowRef<boolean>>;
  statusCode: ShallowRef<number | null>;
  response: ShallowRef<Response | null>;
  error: ShallowRef<any>;
  data: ShallowRef<T | null>;
  isFetching: Readonly<ShallowRef<boolean>>;
  canAbort: ComputedRef<boolean>;
  aborted: ShallowRef<boolean>;
  abort: (_?: any) => void;
  execute: (_?: boolean) => Promise<any>;
  onFetchResponse: EventHookOn<Response>;
  onFetchError: EventHookOn;
  onFetchFinally: EventHookOn;
  get: () => UseFetchReturn<T> & PromiseLike<UseFetchReturn<T>>;
  post: (_?: MaybeRefOrGetter<unknown>, _?: string) => UseFetchReturn<T> & PromiseLike<UseFetchReturn<T>>;
  put: (_?: MaybeRefOrGetter<unknown>, _?: string) => UseFetchReturn<T> & PromiseLike<UseFetchReturn<T>>;
  delete: (_?: MaybeRefOrGetter<unknown>, _?: string) => UseFetchReturn<T> & PromiseLike<UseFetchReturn<T>>;
  patch: (_?: MaybeRefOrGetter<unknown>, _?: string) => UseFetchReturn<T> & PromiseLike<UseFetchReturn<T>>;
  head: (_?: MaybeRefOrGetter<unknown>, _?: string) => UseFetchReturn<T> & PromiseLike<UseFetchReturn<T>>;
  options: (_?: MaybeRefOrGetter<unknown>, _?: string) => UseFetchReturn<T> & PromiseLike<UseFetchReturn<T>>;
  json: <JSON = any>() => UseFetchReturn<JSON> & PromiseLike<UseFetchReturn<JSON>>;
  text: () => UseFetchReturn<string> & PromiseLike<UseFetchReturn<string>>;
  blob: () => UseFetchReturn<Blob> & PromiseLike<UseFetchReturn<Blob>>;
  arrayBuffer: () => UseFetchReturn<ArrayBuffer> & PromiseLike<UseFetchReturn<ArrayBuffer>>;
  formData: () => UseFetchReturn<FormData> & PromiseLike<UseFetchReturn<FormData>>;
}
export interface UseFileDialogOptions extends ConfigurableDocument {
  multiple?: MaybeRef<boolean>;
  accept?: MaybeRef<string>;
  capture?: MaybeRef<string>;
  reset?: MaybeRef<boolean>;
  directory?: MaybeRef<boolean>;
  initialFiles?: Array<File> | FileList;
  input?: MaybeElementRef<HTMLInputElement>;
}
export interface UseFileDialogReturn {
  files: Ref<FileList | null>;
  open: (_?: Partial<UseFileDialogOptions>) => void;
  reset: () => void;
  onChange: EventHookOn<FileList | null>;
  onCancel: EventHookOn;
}
export interface UseFileSystemAccessReturn<T = string> extends Supportable {
  data: ShallowRef<T | undefined>;
  file: ShallowRef<File | undefined>;
  fileName: ComputedRef<string>;
  fileMIME: ComputedRef<string>;
  fileSize: ComputedRef<number>;
  fileLastModified: ComputedRef<number>;
  open: (_?: UseFileSystemAccessCommonOptions) => Awaitable<void>;
  create: (_?: UseFileSystemAccessShowSaveFileOptions) => Awaitable<void>;
  save: (_?: UseFileSystemAccessShowSaveFileOptions) => Awaitable<void>;
  saveAs: (_?: UseFileSystemAccessShowSaveFileOptions) => Awaitable<void>;
  updateData: () => Awaitable<void>;
}
export interface UseFocusOptions extends ConfigurableWindow {
  initialValue?: boolean;
  focusVisible?: boolean;
  preventScroll?: boolean;
}
export interface UseFocusReturn {
  focused: WritableComputedRef<boolean>;
}
export interface UseFocusWithinReturn {
  focused: ComputedRef<boolean>;
}
export interface UseFpsOptions {
  every?: number;
}
export interface UseFullscreenOptions extends ConfigurableDocument {
  autoExit?: boolean;
}
export interface UseFullscreenReturn extends Supportable {
  isFullscreen: ShallowRef<boolean>;
  enter: () => Promise<void>;
  exit: () => Promise<void>;
  toggle: () => Promise<void>;
}
export interface UseGamepadOptions extends ConfigurableWindow, ConfigurableNavigator {}
export interface UseGamepadReturn extends Supportable, Pausable {
  onConnected: EventHookOn<number>;
  onDisconnected: EventHookOn<number>;
  gamepads: Ref<Gamepad[]>;
}
export interface UseGeolocationOptions extends Partial<PositionOptions>, ConfigurableNavigator {
  immediate?: boolean;
}
export interface UseGeolocationReturn extends Supportable {
  coords: ShallowRef<Omit<GeolocationPosition['coords'], 'toJSON'>>;
  locatedAt: ShallowRef<number | null>;
  error: ShallowRef<GeolocationPositionError | null>;
  resume: () => void;
  pause: () => void;
}
export interface UseHorizontalVirtualListOptions extends UseVirtualListOptionsBase {
  itemWidth: UseVirtualListItemSize;
}
export interface UseIdleOptions extends ConfigurableWindow, ConfigurableEventFilter {
  events?: WindowEventName[];
  listenForVisibilityChange?: boolean;
  initialState?: boolean;
}
export interface UseIdleReturn extends Stoppable {
  idle: ShallowRef<boolean>;
  lastActive: ShallowRef<number>;
  reset: () => void;
}
export interface UseImageOptions {
  src: string;
  srcset?: string;
  sizes?: string;
  alt?: string;
  class?: string;
  loading?: HTMLImageElement['loading'];
  crossorigin?: string;
  referrerPolicy?: HTMLImageElement['referrerPolicy'];
  width?: HTMLImageElement['width'];
  height?: HTMLImageElement['height'];
  decoding?: HTMLImageElement['decoding'];
  fetchPriority?: HTMLImageElement['fetchPriority'];
  ismap?: HTMLImageElement['isMap'];
  usemap?: HTMLImageElement['useMap'];
}
export interface UseInfiniteScrollOptions<T extends InfiniteScrollElement = InfiniteScrollElement> extends UseScrollOptions {
  distance?: number;
  direction?: 'top' | 'bottom' | 'left' | 'right';
  interval?: number;
  canLoadMore?: (_: T) => boolean;
}
export interface UseInfiniteScrollReturn {
  isLoading: ComputedRef<boolean>;
  reset: () => void;
}
export interface UseIntersectionObserverOptions extends ConfigurableWindow {
  immediate?: boolean;
  root?: MaybeComputedElementRef | Document;
  rootMargin?: MaybeRefOrGetter<string>;
  threshold?: number | number[];
}
export interface UseIntersectionObserverReturn extends Supportable, Pausable {
  stop: () => void;
}
export interface UseMagicKeysOptions<Reactive extends boolean> {
  reactive?: Reactive;
  target?: MaybeRefOrGetter<EventTarget>;
  aliasMap?: Record<string, string>;
  passive?: boolean;
  onEventFired?: (_: KeyboardEvent) => void | boolean;
}
export interface UseManualRefHistoryOptions<Raw, Serialized = Raw> {
  capacity?: number;
  clone?: boolean | CloneFn<Raw>;
  dump?: (_: Raw) => Serialized;
  parse?: (_: Serialized) => Raw;
  setSource?: (_: Ref<Raw>, _: Raw) => void;
}
export interface UseManualRefHistoryReturn<Raw, Serialized> {
  source: Ref<Raw>;
  history: ComputedRef<UseRefHistoryRecord<Serialized>[]>;
  last: Ref<UseRefHistoryRecord<Serialized>>;
  undoStack: Ref<UseRefHistoryRecord<Serialized>[]>;
  redoStack: Ref<UseRefHistoryRecord<Serialized>[]>;
  canUndo: ComputedRef<boolean>;
  canRedo: ComputedRef<boolean>;
  undo: () => void;
  redo: () => void;
  clear: () => void;
  commit: () => void;
  reset: () => void;
}
export interface UseMediaControlsReturn {
  currentTime: ShallowRef<number>;
  duration: ShallowRef<number>;
  waiting: ShallowRef<boolean>;
  seeking: ShallowRef<boolean>;
  ended: ShallowRef<boolean>;
  stalled: ShallowRef<boolean>;
  buffered: ShallowRef<[number, number][]>;
  playing: ShallowRef<boolean>;
  rate: ShallowRef<number>;
  volume: ShallowRef<number>;
  muted: ShallowRef<boolean>;
  tracks: ShallowRef<UseMediaTextTrack[]>;
  selectedTrack: ShallowRef<number>;
  enableTrack: (_: number | UseMediaTextTrack, _?: boolean) => void;
  disableTrack: (_?: number | UseMediaTextTrack) => void;
  supportsPictureInPicture: boolean;
  togglePictureInPicture: () => Promise<PictureInPictureWindow | void>;
  isPictureInPicture: ShallowRef<boolean>;
  onSourceError: EventHookOn<Event>;
  onPlaybackError: EventHookOn<Event>;
}
export interface UseMediaSource {
  src: string;
  type?: string;
  media?: string;
}
export interface UseMediaTextTrack {
  id: number;
  label: string;
  language: string;
  mode: TextTrackMode;
  kind: TextTrackKind;
  inBandMetadataTrackDispatchType: string;
  cues: TextTrackCueList | null;
  activeCues: TextTrackCueList | null;
}
export interface UseMediaTextTrackSource {
  default?: boolean;
  kind: TextTrackKind;
  label: string;
  src: string;
  srcLang: string;
}
export interface UseMemoizeCache<Key, Value> {
  get: (_: Key) => Value | undefined;
  set: (_: Key, _: Value) => void;
  has: (_: Key) => boolean;
  delete: (_: Key) => void;
  clear: () => void;
}
export interface UseMemoizeOptions<Result, Args extends unknown[]> {
  getKey?: (..._: Args) => string | number;
  cache?: UseMemoizeCache<CacheKey, Result>;
}
export interface UseMemoizeReturn<Result, Args extends unknown[]> {
  (..._: Args): Result;
  load: (..._: Args) => Result;
  delete: (..._: Args) => void;
  clear: () => void;
  generateKey: (..._: Args) => CacheKey;
  cache: UseMemoizeCache<CacheKey, Result>;
}
export interface UseMemoryOptions extends ConfigurableScheduler {
  immediate?: boolean;
  immediateCallback?: boolean;
  interval?: number;
}
export interface UseMemoryReturn extends Supportable {
  memory: ShallowRef<MemoryInfo | undefined>;
}
export interface UseModifierOptions<Initial> extends ConfigurableDocument {
  events?: WindowEventName[];
  initial?: Initial;
}
export interface UseMouseInElementReturn extends UseMouseReturn {
  elementX: ShallowRef<number>;
  elementY: ShallowRef<number>;
  elementPositionX: ShallowRef<number>;
  elementPositionY: ShallowRef<number>;
  elementHeight: ShallowRef<number>;
  elementWidth: ShallowRef<number>;
  isOutside: ShallowRef<boolean>;
  stop: () => void;
}
export interface UseMouseOptions extends ConfigurableWindow, ConfigurableEventFilter {
  type?: UseMouseCoordType | UseMouseEventExtractor;
  target?: MaybeRefOrGetter<Window | EventTarget | null | undefined>;
  touch?: boolean;
  scroll?: boolean;
  resetOnTouchEnds?: boolean;
  initialValue?: Position;
}
export interface UseMousePressedOptions extends ConfigurableWindow {
  touch?: boolean;
  drag?: boolean;
  capture?: boolean;
  initialValue?: boolean;
  target?: MaybeComputedElementRef;
  onPressed?: (_: MouseEvent | TouchEvent | DragEvent) => void;
  onReleased?: (_: MouseEvent | TouchEvent | DragEvent) => void;
}
export interface UseMousePressedReturn {
  pressed: ShallowRef<boolean>;
  sourceType: ShallowRef<UseMouseSourceType>;
}
export interface UseMouseReturn {
  x: ShallowRef<number>;
  y: ShallowRef<number>;
  sourceType: ShallowRef<UseMouseSourceType>;
}
export interface UseMutationObserverOptions extends MutationObserverInit, ConfigurableWindow {}
export interface UseMutationObserverReturn extends Supportable {
  stop: () => void;
  takeRecords: () => MutationRecord[] | undefined;
}
export interface UseNavigatorLanguageOptions extends ConfigurableWindow {}
export interface UseNetworkOptions extends ConfigurableWindow {}
export interface UseNowOptions<Controls extends boolean> extends ConfigurableScheduler {
  controls?: Controls;
  immediate?: boolean;
  interval?: 'requestAnimationFrame' | number;
}
export interface UseOffsetPaginationOptions {
  total?: MaybeRefOrGetter<number>;
  pageSize?: MaybeRefOrGetter<number>;
  page?: MaybeRef<number>;
  onPageChange?: (_: UnwrapNestedRefs<UseOffsetPaginationReturn>) => unknown;
  onPageSizeChange?: (_: UnwrapNestedRefs<UseOffsetPaginationReturn>) => unknown;
  onPageCountChange?: (_: UnwrapNestedRefs<UseOffsetPaginationReturn>) => unknown;
}
export interface UseOffsetPaginationReturn {
  currentPage: Ref<number>;
  currentPageSize: Ref<number>;
  pageCount: ComputedRef<number>;
  isFirstPage: ComputedRef<boolean>;
  isLastPage: ComputedRef<boolean>;
  prev: () => void;
  next: () => void;
}
export interface UsePageLeaveOptions extends ConfigurableWindow {}
export interface UseParallaxOptions extends ConfigurableWindow {
  deviceOrientationTiltAdjust?: (_: number) => number;
  deviceOrientationRollAdjust?: (_: number) => number;
  mouseTiltAdjust?: (_: number) => number;
  mouseRollAdjust?: (_: number) => number;
}
export interface UseParallaxReturn {
  roll: ComputedRef<number>;
  tilt: ComputedRef<number>;
  source: ComputedRef<'deviceOrientation' | 'mouse'>;
}
export interface UsePermissionOptions<Controls extends boolean> extends ConfigurableNavigator {
  controls?: Controls;
}
export interface UsePermissionReturnWithControls extends Supportable {
  state: UsePermissionReturn;
  query: () => Promise<PermissionStatus | undefined>;
}
export interface UsePointerLockOptions extends ConfigurableDocument {}
export interface UsePointerLockReturn extends Supportable {
  element: ShallowRef<MaybeElement>;
  triggerElement: ShallowRef<MaybeElement>;
  lock: (_: MaybeElementRef | Event) => Promise<MaybeElement>;
  unlock: () => Promise<boolean>;
}
export interface UsePointerOptions extends ConfigurableWindow {
  pointerTypes?: PointerType[];
  initialValue?: MaybeRef<Partial<UsePointerState>>;
  target?: MaybeRef<EventTarget | null | undefined> | Document | Window;
}
export interface UsePointerReturn {
  pressure: Ref<number>;
  pointerId: Ref<number>;
  tiltX: Ref<number>;
  tiltY: Ref<number>;
  width: Ref<number>;
  height: Ref<number>;
  twist: Ref<number>;
  pointerType: Ref<PointerType | null>;
  x: Ref<number>;
  y: Ref<number>;
  isInside: ShallowRef<boolean>;
}
export interface UsePointerState extends Position {
  pressure: number;
  pointerId: number;
  tiltX: number;
  tiltY: number;
  width: number;
  height: number;
  twist: number;
  pointerType: PointerType | null;
}
export interface UsePointerSwipeOptions {
  threshold?: number;
  onSwipeStart?: (_: PointerEvent) => void;
  onSwipe?: (_: PointerEvent) => void;
  onSwipeEnd?: (_: PointerEvent, _: UseSwipeDirection) => void;
  pointerTypes?: PointerType[];
  disableTextSelect?: boolean;
}
export interface UsePointerSwipeReturn {
  readonly isSwiping: ShallowRef<boolean>;
  direction: Readonly<ShallowRef<UseSwipeDirection>>;
  readonly posStart: DeepReadonly<Position>;
  readonly posEnd: DeepReadonly<Position>;
  distanceX: Readonly<ComputedRef<number>>;
  distanceY: Readonly<ComputedRef<number>>;
  stop: () => void;
}
export interface UseRafFnCallbackArguments {
  delta: number;
  timestamp: DOMHighResTimeStamp;
}
export interface UseRafFnOptions extends ConfigurableWindow {
  immediate?: boolean;
  fpsLimit?: MaybeRefOrGetter<number | null>;
  once?: boolean;
}
export interface UseRefHistoryOptions<Raw, Serialized = Raw> extends ConfigurableEventFilter, ConfigurableFlush {
  deep?: boolean;
  capacity?: number;
  clone?: boolean | CloneFn<Raw>;
  dump?: (_: Raw) => Serialized;
  parse?: (_: Serialized) => Raw;
  shouldCommit?: (_: Raw | undefined, _: Raw) => boolean;
}
export interface UseRefHistoryRecord<T> {
  snapshot: T;
  timestamp: number;
}
export interface UseRefHistoryReturn<Raw, Serialized> extends UseManualRefHistoryReturn<Raw, Serialized> {
  isTracking: Ref<boolean>;
  pause: () => void;
  resume: (_?: boolean) => void;
  batch: (_: (_: Fn) => void) => void;
  dispose: () => void;
}
export interface UseResizeObserverOptions extends ResizeObserverOptions, ConfigurableWindow {}
export interface UseResizeObserverReturn extends Supportable {
  stop: () => void;
}
export interface UseScreenOrientationOptions extends ConfigurableWindow {}
export interface UseScreenOrientationReturn extends Supportable {
  orientation: ShallowRef<OrientationType | undefined>;
  angle: ShallowRef<number>;
  lockOrientation: (_: OrientationLockType) => Promise<void>;
  unlockOrientation: () => void;
}
export interface UseScreenSafeAreaReturn {
  top: ShallowRef<string>;
  right: ShallowRef<string>;
  bottom: ShallowRef<string>;
  left: ShallowRef<string>;
  update: () => void;
}
export interface UseScriptTagOptions extends ConfigurableDocument {
  immediate?: boolean;
  async?: boolean;
  type?: string;
  manual?: boolean;
  crossOrigin?: 'anonymous' | 'use-credentials';
  referrerPolicy?: 'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url';
  noModule?: boolean;
  defer?: boolean;
  attrs?: Record<string, string>;
  nonce?: string;
}
export interface UseScriptTagReturn {
  scriptTag: ShallowRef<HTMLScriptElement | null>;
  load: (_?: boolean) => Promise<HTMLScriptElement | boolean>;
  unload: () => void;
}
export interface UseScrollOptions extends ConfigurableWindow {
  throttle?: number;
  idle?: number;
  offset?: {
    left?: number;
    right?: number;
    top?: number;
    bottom?: number;
  };
  observe?: boolean | {
    mutation?: boolean;
  };
  onScroll?: (_: Event) => void;
  onStop?: (_: Event) => void;
  eventListenerOptions?: boolean | AddEventListenerOptions;
  behavior?: MaybeRefOrGetter<ScrollBehavior>;
  onError?: (_: unknown) => void;
}
export interface UseScrollReturn {
  x: WritableComputedRef<number>;
  y: WritableComputedRef<number>;
  isScrolling: ShallowRef<boolean>;
  arrivedState: {
    left: boolean;
    right: boolean;
    top: boolean;
    bottom: boolean;
  };
  directions: {
    left: boolean;
    right: boolean;
    top: boolean;
    bottom: boolean;
  };
  measure: () => void;
}
export interface UseShareOptions {
  title?: string;
  files?: File[];
  text?: string;
  url?: string;
}
export interface UseShareReturn extends Supportable {
  share: (_?: MaybeRefOrGetter<UseShareOptions>) => Promise<void>;
}
export interface UseSortedOptions<T = any> {
  sortFn?: UseSortedFn<T>;
  compareFn?: UseSortedCompareFn<T>;
  dirty?: boolean;
}
export interface UseSpeechRecognitionOptions extends ConfigurableWindow {
  continuous?: boolean;
  interimResults?: boolean;
  lang?: MaybeRefOrGetter<string>;
  maxAlternatives?: number;
}
export interface UseSpeechRecognitionReturn extends Supportable {
  isListening: ShallowRef<boolean>;
  isFinal: ShallowRef<boolean>;
  recognition: SpeechRecognition | undefined;
  result: ShallowRef<string>;
  error: ShallowRef<SpeechRecognitionErrorEvent | Error | undefined>;
  toggle: (_?: boolean) => void;
  start: () => void;
  stop: () => void;
}
export interface UseSpeechSynthesisOptions extends ConfigurableWindow {
  lang?: MaybeRefOrGetter<string>;
  pitch?: MaybeRefOrGetter<SpeechSynthesisUtterance['pitch']>;
  rate?: MaybeRefOrGetter<SpeechSynthesisUtterance['rate']>;
  voice?: MaybeRef<SpeechSynthesisVoice>;
  volume?: MaybeRefOrGetter<SpeechSynthesisUtterance['volume']>;
  onBoundary?: (_: SpeechSynthesisEvent) => void;
}
export interface UseSpeechSynthesisReturn extends Supportable {
  isPlaying: ShallowRef<boolean>;
  status: ShallowRef<UseSpeechSynthesisStatus>;
  utterance: ComputedRef<SpeechSynthesisUtterance>;
  error: ShallowRef<SpeechSynthesisErrorEvent | undefined>;
  stop: () => void;
  toggle: (_?: boolean) => void;
  speak: () => void;
}
export interface UseStepperReturn<StepName, Steps, Step> {
  steps: Readonly<Ref<Steps>>;
  stepNames: Readonly<Ref<StepName[]>>;
  index: Ref<number>;
  current: ComputedRef<Step>;
  next: ComputedRef<StepName | undefined>;
  previous: ComputedRef<StepName | undefined>;
  isFirst: ComputedRef<boolean>;
  isLast: ComputedRef<boolean>;
  at: (_: number) => Step | undefined;
  get: (_: StepName) => Step | undefined;
  goTo: (_: StepName) => void;
  goToNext: () => void;
  goToPrevious: () => void;
  goBackTo: (_: StepName) => void;
  isNext: (_: StepName) => boolean;
  isPrevious: (_: StepName) => boolean;
  isCurrent: (_: StepName) => boolean;
  isBefore: (_: StepName) => boolean;
  isAfter: (_: StepName) => boolean;
}
export interface UseStorageAsyncOptions<T> extends Omit<UseStorageOptions<T>, 'serializer'> {
  serializer?: SerializerAsync<T>;
  onReady?: (_: T) => void;
}
export interface UseStorageOptions<T> extends ConfigurableEventFilter, ConfigurableWindow, ConfigurableFlush {
  deep?: boolean;
  listenToStorageChanges?: boolean;
  writeDefaults?: boolean;
  mergeDefaults?: boolean | ((_: T, _: T) => T);
  serializer?: Serializer<T>;
  onError?: (_: unknown) => void;
  shallow?: boolean;
  initOnMounted?: boolean;
}
export interface UseStyleTagOptions extends ConfigurableDocument {
  media?: string;
  immediate?: boolean;
  manual?: boolean;
  id?: string;
  nonce?: string;
}
export interface UseStyleTagReturn {
  id: string;
  css: ShallowRef<string>;
  load: () => void;
  unload: () => void;
  isLoaded: Readonly<ShallowRef<boolean>>;
}
export interface UseSwipeOptions extends ConfigurableWindow {
  passive?: boolean;
  threshold?: number;
  onSwipeStart?: (_: TouchEvent) => void;
  onSwipe?: (_: TouchEvent) => void;
  onSwipeEnd?: (_: TouchEvent, _: UseSwipeDirection) => void;
}
export interface UseSwipeReturn {
  isSwiping: ShallowRef<boolean>;
  direction: ComputedRef<UseSwipeDirection>;
  coordsStart: Readonly<Position>;
  coordsEnd: Readonly<Position>;
  lengthX: ComputedRef<number>;
  lengthY: ComputedRef<number>;
  stop: () => void;
}
export interface UseTextareaAutosizeOptions extends ConfigurableWindow {
  element?: MaybeRef<HTMLTextAreaElement | undefined | null>;
  input?: MaybeRef<string>;
  watch?: WatchSource | MultiWatchSources;
  onResize?: () => void;
  styleTarget?: MaybeRef<HTMLElement | undefined>;
  styleProp?: 'height' | 'minHeight';
}
export interface UseTextareaAutosizeReturn {
  textarea: Ref<HTMLTextAreaElement | undefined | null>;
  input: Ref<string>;
  triggerResize: () => void;
}
export interface UseTextDirectionOptions extends ConfigurableDocument {
  selector?: string;
  observe?: boolean;
  initialValue?: UseTextDirectionValue;
}
export interface UseTextSelectionOptions extends ConfigurableWindow {}
export interface UseTextSelectionReturn {
  text: ComputedRef<string>;
  rects: ComputedRef<DOMRect[]>;
  ranges: ComputedRef<Range[]>;
  selection: ShallowRef<Selection | null>;
}
export interface UseTimeAgoIntlOptions<Controls extends boolean> extends FormatTimeAgoIntlOptions, ConfigurableScheduler {
  controls?: Controls;
  updateInterval?: number;
}
export interface UseTimeAgoMessagesBuiltIn {
  justNow: string;
  past: string | UseTimeAgoFormatter<string>;
  future: string | UseTimeAgoFormatter<string>;
  invalid: string;
}
export interface UseTimeAgoOptions<Controls extends boolean, UnitNames extends string = UseTimeAgoUnitNamesDefault> extends FormatTimeAgoOptions<UnitNames>, ConfigurableScheduler {
  controls?: Controls;
  updateInterval?: number;
}
export interface UseTimeAgoUnit<Unit extends string = UseTimeAgoUnitNamesDefault> {
  max: number;
  value: number;
  name: Unit;
}
export interface UseTimeoutPollOptions {
  immediate?: boolean;
  immediateCallback?: boolean;
}
export interface UseTimestampOptions<Controls extends boolean> extends ConfigurableScheduler {
  controls?: Controls;
  offset?: number;
  immediate?: boolean;
  interval?: 'requestAnimationFrame' | number;
  callback?: (_: number) => void;
}
export interface UseTransitionOptions<T> extends TransitionOptions<T> {
  delay?: MaybeRef<number>;
  disabled?: MaybeRef<boolean>;
  onFinished?: () => void;
  onStarted?: () => void;
}
export interface UseUrlSearchParamsOptions<T> extends ConfigurableWindow {
  removeNullishValues?: boolean;
  removeFalsyValues?: boolean;
  initialValue?: T;
  write?: boolean;
  writeMode?: 'replace' | 'push';
  stringify?: (_: URLSearchParams) => string;
}
export interface UseUserMediaOptions extends ConfigurableNavigator {
  enabled?: MaybeRef<boolean>;
  autoSwitch?: MaybeRef<boolean>;
  constraints?: MaybeRef<MediaStreamConstraints>;
}
export interface UseUserMediaReturn extends Supportable {
  stream: Ref<MediaStream | undefined>;
  start: () => Promise<MediaStream | undefined>;
  stop: () => void;
  restart: () => Promise<MediaStream | undefined>;
  constraints: Ref<MediaStreamConstraints | undefined>;
  enabled: ShallowRef<boolean>;
  autoSwitch: ShallowRef<boolean>;
}
export interface UseVerticalVirtualListOptions extends UseVirtualListOptionsBase {
  itemHeight: UseVirtualListItemSize;
}
export interface UseVibrateOptions extends ConfigurableNavigator, ConfigurableScheduler {
  pattern?: MaybeRefOrGetter<Arrayable<number>>;
  interval: number;
}
export interface UseVibrateReturn extends Supportable {
  pattern: MaybeRefOrGetter<Arrayable<number>>;
  intervalControls?: Pausable;
  vibrate: (_?: Arrayable<number>) => void;
  stop: () => void;
}
export interface UseVirtualListItem<T> {
  data: T;
  index: number;
}
export interface UseVirtualListOptionsBase {
  overscan?: number;
}
export interface UseVirtualListReturn<T> {
  list: Ref<UseVirtualListItem<T>[]>;
  scrollTo: (_: number) => void;
  containerProps: {
    ref: Ref<HTMLElement | null>;
    onScroll: () => void;
    style: StyleValue;
  };
  wrapperProps: ComputedRef<{
    style: {
      width: string;
      height: string;
      marginTop: string;
    } | {
      width: string;
      height: string;
      marginLeft: string;
      display: string;
    };
  }>;
}
export interface UseVModelOptions<T, Passive extends boolean = false> {
  passive?: Passive;
  eventName?: string;
  deep?: boolean;
  defaultValue?: T;
  clone?: boolean | CloneFn<T>;
  shouldEmit?: (_: T) => boolean;
}
export interface UseWakeLockReturn extends Supportable {
  sentinel: ShallowRef<WakeLockSentinel | null>;
  isActive: ComputedRef<boolean>;
  request: (_: WakeLockType) => Promise<void>;
  forceRequest: (_: WakeLockType) => Promise<void>;
  release: () => Promise<void>;
}
export interface UseWebNotificationOptions extends ConfigurableWindow, WebNotificationOptions {
  requestPermissions?: boolean;
}
export interface UseWebNotificationReturn extends Supportable {
  notification: ShallowRef<Notification | null>;
  ensurePermissions: () => Promise<boolean | undefined>;
  permissionGranted: ShallowRef<boolean>;
  show: (_?: WebNotificationOptions) => Promise<Notification | undefined>;
  close: () => void;
  onClick: EventHookOn<Event>;
  onShow: EventHookOn<Event>;
  onError: EventHookOn<Event>;
  onClose: EventHookOn<Event>;
}
export interface UseWebSocketOptions {
  onConnected?: (_: WebSocket) => void;
  onDisconnected?: (_: WebSocket, _: CloseEvent) => void;
  onError?: (_: WebSocket, _: Event) => void;
  onMessage?: (_: WebSocket, _: MessageEvent) => void;
  heartbeat?: boolean | ConfigurableScheduler & {
    message?: MaybeRefOrGetter<WebSocketHeartbeatMessage>;
    responseMessage?: MaybeRefOrGetter<WebSocketHeartbeatMessage>;
    interval?: number;
    pongTimeout?: number;
  };
  autoReconnect?: boolean | {
    retries?: number | ((_: number) => boolean);
    delay?: number | ((_: number) => number);
    onFailed?: Fn;
  };
  immediate?: boolean;
  autoConnect?: boolean;
  autoClose?: boolean;
  protocols?: string[];
}
export interface UseWebSocketReturn<T> {
  data: ShallowRef<T | null>;
  status: ShallowRef<WebSocketStatus>;
  close: WebSocket['close'];
  open: Fn;
  send: (_: string | ArrayBuffer | Blob, _?: boolean) => boolean;
  ws: ShallowRef<WebSocket | undefined>;
}
export interface UseWebWorkerFnReturn<T extends (...fnArgs: any[]) => any> {
  workerFn: (..._: Parameters<T>) => Promise<ReturnType<T>>;
  workerStatus: ShallowRef<WebWorkerStatus>;
  workerTerminate: (_?: WebWorkerStatus) => void;
}
export interface UseWebWorkerOptions extends ConfigurableWindow {
  timeout?: number;
  dependencies?: string[];
  localDependencies?: Function[];
}
export interface UseWebWorkerReturn<Data = any> {
  data: ShallowRef<Data>;
  post: PostMessage;
  terminate: () => void;
  worker: ShallowRef<Worker | undefined>;
}
export interface UseWindowScrollOptions extends ConfigurableWindow, UseScrollOptions {}
export interface UseWindowScrollReturn extends UseScrollReturn {}
export interface UseWindowSizeOptions extends ConfigurableWindow {
  initialWidth?: number;
  initialHeight?: number;
  listenOrientation?: boolean;
  includeScrollbar?: boolean;
  type?: 'inner' | 'outer' | 'visual';
}
export interface UseWindowSizeReturn {
  width: ShallowRef<number>;
  height: ShallowRef<number>;
}
export interface WakeLockSentinel extends EventTarget {
  type: WakeLockType;
  released: boolean;
  release: () => Promise<void>;
}
export interface WebNotificationOptions {
  title?: string;
  body?: string;
  dir?: 'auto' | 'ltr' | 'rtl';
  lang?: string;
  tag?: string;
  icon?: string;
  renotify?: boolean;
  requireInteraction?: boolean;
  silent?: boolean;
  vibrate?: number[];
}
export interface WritableComputedInjectOptions<T, K> {
  get: ComputedInjectGetter<T, K>;
  set: ComputedInjectSetter<K>;
}
export interface WritableComputedInjectOptionsWithDefault<T, K> {
  get: ComputedInjectGetterWithDefault<T, K>;
  set: ComputedInjectSetter<K>;
}
// #endregion

// #region Types
export type AsyncComputedOnCancel = (_: Fn) => void;
export type BasicColorMode = 'light' | 'dark';
export type BasicColorSchema = BasicColorMode | 'auto';
export type Breakpoints<K extends string = string> = Record<K, MaybeRefOrGetter<number | string>>;
export type CloneFn<F, T = F> = (_: F) => T;
export type ColorSchemeType = 'dark' | 'light' | 'no-preference';
export type ComputedInjectGetter<T, K> = (_: T | undefined, _?: K) => K;
export type ComputedInjectGetterWithDefault<T, K> = (_: T, _?: K) => K;
export type ComputedInjectSetter<T> = (_: T) => void;
export type ContrastType = 'more' | 'less' | 'custom' | 'no-preference';
export type CubicBezierPoints = [number, number, number, number];
export type DefineTemplateComponent<Bindings extends Record<string, any>, MapSlotNameToSlotProps extends ObjectLiteralWithPotentialObjectLiterals> = DefineComponent & {
  new (): {
    $slots: {
      default: (_: Bindings & {
        $slots: GenerateSlotsFromSlotMap<MapSlotNameToSlotProps>;
      }) => any;
    };
  };
};
export type DeviceMotionOptions = UseDeviceMotionOptions;
export type DocumentEventName = keyof DocumentEventMap;
export type EasingFunction = (_: number) => number;
export type EventBusEvents<T, P = any> = Set<EventBusListener<T, P>>;
export type EventBusIdentifier<T = unknown> = EventBusKey<T> | string | number;
export type EventBusListener<T = unknown, P = any> = (_: T, _?: P) => void;
export type EventSourceStatus = 'CONNECTING' | 'OPEN' | 'CLOSED';
export type FileSystemAccessWindow = Window & {
  showSaveFilePicker: (_: FileSystemAccessShowSaveFileOptions) => Promise<FileSystemFileHandle>;
  showOpenFilePicker: (_: FileSystemAccessShowOpenFileOptions) => Promise<FileSystemFileHandle[]>;
};
export type GeneralPermissionDescriptor = PermissionDescriptor | {
  name: DescriptorNamePolyfill;
};
export type InterpolationFunction<T> = (_: T, _: T, _: number) => T;
export type KeyFilter = true | string | string[] | KeyPredicate;
export type KeyModifier = 'Alt' | 'AltGraph' | 'CapsLock' | 'Control' | 'Fn' | 'FnLock' | 'Meta' | 'NumLock' | 'ScrollLock' | 'Shift' | 'Symbol' | 'SymbolLock';
export type KeyPredicate = (_: KeyboardEvent) => boolean;
export type KeyStrokeEventName = 'keydown' | 'keypress' | 'keyup';
export type MaybeComputedElementRef<T extends MaybeElement = MaybeElement> = MaybeRefOrGetter<T>;
export type MaybeElement = HTMLElement | SVGElement | VueInstance | undefined | null;
export type MaybeElementRef<T extends MaybeElement = MaybeElement> = MaybeRef<T>;
export type MousePressedOptions = UseMousePressedOptions;
export type NetworkEffectiveType = 'slow-2g' | '2g' | '3g' | '4g' | undefined;
export type NetworkType = 'bluetooth' | 'cellular' | 'ethernet' | 'none' | 'wifi' | 'wimax' | 'other' | 'unknown';
export type OnClickOutsideHandler<T extends OnClickOutsideOptions<boolean> = OnClickOutsideOptions> = (_: (T['detectIframe'] extends true ? FocusEvent : never) | (T['controls'] extends true ? Event : never) | PointerEvent) => void;
export type OnClickOutsideReturn<Controls extends boolean = false> = Controls extends false ? Fn : {
  stop: Fn;
  cancel: Fn;
  trigger: (event: Event) => void;
};
export type OnLongPressReturn = () => void;
export type OrientationLockType = 'any' | 'natural' | 'landscape' | 'portrait' | 'portrait-primary' | 'portrait-secondary' | 'landscape-primary' | 'landscape-secondary';
export type OrientationType = 'portrait-primary' | 'portrait-secondary' | 'landscape-primary' | 'landscape-secondary';
export type PointerType = 'mouse' | 'touch' | 'pen';
export type ReducedMotionType = 'reduce' | 'no-preference';
export type ReducedTransparencyType = 'reduce' | 'no-preference';
export type ResizeObserverCallback = (_: ReadonlyArray<ResizeObserverEntry>, _: ResizeObserver) => void;
export type ReusableTemplatePair<Bindings extends Record<string, any>, MapSlotNameToSlotProps extends ObjectLiteralWithPotentialObjectLiterals> = [DefineTemplateComponent<Bindings, MapSlotNameToSlotProps>, ReuseTemplateComponent<Bindings, MapSlotNameToSlotProps>] & {
  define: DefineTemplateComponent<Bindings, MapSlotNameToSlotProps>;
  reuse: ReuseTemplateComponent<Bindings, MapSlotNameToSlotProps>;
};
export type ReuseTemplateComponent<Bindings extends Record<string, any>, MapSlotNameToSlotProps extends ObjectLiteralWithPotentialObjectLiterals> = DefineComponent<Bindings> & {
  new (): {
    $slots: GenerateSlotsFromSlotMap<MapSlotNameToSlotProps>;
  };
};
export type ShadowRootEventName = keyof ShadowRootEventMap;
export type TemplatePromise<Return, Args extends any[] = []> = DefineComponent<object> & {
  new (): {
    $slots: {
      default: (_: TemplatePromiseProps<Return, Args>) => any;
    };
  };
} & {
  start: (..._: Args) => Promise<Return>;
};
export type TemplateRefsList<T> = T[] & {
  set: (_: object | null) => void;
};
export type UnRefElementReturn<T extends MaybeElement = MaybeElement> = T extends VueInstance ? Exclude<MaybeElement, VueInstance> : T | undefined;
export type UnrefFn<T> = T extends ((...args: infer A) => infer R) ? (...args: { [K in keyof A]: MaybeRef<A[K]> }) => R : never;
export type UrlParams = Record<string, string[] | string>;
export type UseActiveElementReturn<T extends HTMLElement = HTMLElement> = ShallowRef<T | null | undefined>;
export type UseAnimateKeyframes = MaybeRef<Keyframe[] | PropertyIndexedKeyframes | null>;
export type UseAsyncQueueTask<T> = (..._: any[]) => T | Promise<T>;
export type UseAsyncStateReturn<Data, Params extends any[], Shallow extends boolean> = UseAsyncStateReturnBase<Data, Params, Shallow> & PromiseLike<UseAsyncStateReturnBase<Data, Params, Shallow>>;
export type UseBreakpointReturn<K extends string = string> = Record<K, ComputedRef<boolean>> & {
  greaterOrEqual: (_: MaybeRefOrGetter<K>) => ComputedRef<boolean>;
  smallerOrEqual: (_: MaybeRefOrGetter<K>) => ComputedRef<boolean>;
  greater: (_: MaybeRefOrGetter<K>) => ComputedRef<boolean>;
  smaller: (_: MaybeRefOrGetter<K>) => ComputedRef<boolean>;
  between: (_: MaybeRefOrGetter<K>, _: MaybeRefOrGetter<K>) => ComputedRef<boolean>;
  isGreater: (_: MaybeRefOrGetter<K>) => boolean;
  isGreaterOrEqual: (_: MaybeRefOrGetter<K>) => boolean;
  isSmaller: (_: MaybeRefOrGetter<K>) => boolean;
  isSmallerOrEqual: (_: MaybeRefOrGetter<K>) => boolean;
  isInBetween: (_: MaybeRefOrGetter<K>, _: MaybeRefOrGetter<K>) => boolean;
  current: () => ComputedRef<K[]>;
  active: () => ComputedRef<K | ''>;
};
export type UseBrowserLocationReturn = Ref<BrowserLocationState>;
export type UseCachedReturn<T = any, D extends boolean = true> = ShallowOrDeepRef<T, D>;
export type UseColorModeReturn<T extends string = BasicColorMode> = Ref<T | BasicColorSchema> & {
  store: Ref<T | BasicColorSchema>;
  system: ComputedRef<BasicColorMode>;
  state: ComputedRef<T | BasicColorMode>;
};
export type UseConfirmDialogRevealResult<C, D> = {
  data?: C;
  isCanceled: false;
} | {
  data?: D;
  isCanceled: true;
};
export type UseDarkReturn = WritableComputedRef<boolean>;
export type UseDocumentVisibilityReturn = ShallowRef<DocumentVisibilityState>;
export type UseElementVisibilityReturn<Controls extends boolean = false> = Controls extends true ? UseElementVisibilityReturnWithControls : ShallowRef<boolean>;
export type UseFaviconReturn = ComputedRef<string | null | undefined> | Ref<string | null | undefined>;
export type UseFileSystemAccessCommonOptions = Pick<FileSystemAccessShowOpenFileOptions, 'types' | 'excludeAcceptAllOption'>;
export type UseFileSystemAccessOptions = ConfigurableWindow & UseFileSystemAccessCommonOptions & {
  dataType?: MaybeRefOrGetter<'Text' | 'ArrayBuffer' | 'Blob'>;
};
export type UseFileSystemAccessShowSaveFileOptions = Pick<FileSystemAccessShowSaveFileOptions, 'suggestedName'>;
export type UseImageReturn = UseAsyncStateReturn<HTMLImageElement | undefined, any[], true>;
export type UseKeyModifierReturn<Initial> = ShallowRef<Initial extends boolean ? boolean : boolean | null>;
export type UseMagicKeysReturn<Reactive extends boolean> = Readonly<Record<string, Reactive extends true ? boolean : ComputedRef<boolean>> & MagicKeysInternal>;
export type UseMouseCoordType = 'page' | 'client' | 'screen' | 'movement';
export type UseMouseEventExtractor = (_: MouseEvent | Touch) => [x: number, y: number] | null | undefined;
export type UseMouseSourceType = 'mouse' | 'touch' | null;
export type UseNavigatorLanguageReturn = Readonly<NavigatorLanguageState>;
export type UseNetworkReturn = Readonly<NetworkState>;
export type UseNowReturn<Controls extends boolean> = Controls extends true ? ({
  now: ShallowRef<Date>;
} & Pausable) : ShallowRef<Date>;
export type UseOffsetPaginationInfinityPageReturn = Omit<UseOffsetPaginationReturn, 'isLastPage'>;
export type UseOnLongPressReturn = OnLongPressReturn;
export type UsePageLeaveReturn = ShallowRef<boolean>;
export type UsePerformanceObserverOptions = PerformanceObserverInit & ConfigurableWindow & {
  immediate?: boolean;
};
export type UsePermissionReturn = Readonly<ShallowRef<PermissionState | undefined>>;
export type UseSortedCompareFn<T = any> = (_: T, _: T) => number;
export type UseSortedFn<T = any> = (_: T[], _: UseSortedCompareFn<T>) => T[];
export type UseSpeechSynthesisStatus = 'init' | 'play' | 'pause' | 'end';
export type UseSupportedReturn = ComputedRef<boolean>;
export type UseSwipeDirection = 'up' | 'down' | 'left' | 'right' | 'none';
export type UseTextDirectionValue = 'ltr' | 'rtl' | 'auto';
export type UseThrottledRefHistoryOptions<Raw, Serialized = Raw> = Omit<UseRefHistoryOptions<Raw, Serialized>, 'eventFilter'> & {
  throttle?: MaybeRef<number>;
  trailing?: boolean;
};
export type UseThrottledRefHistoryReturn<Raw, Serialized = Raw> = UseRefHistoryReturn<Raw, Serialized>;
export type UseTimeAgoFormatter<T = number> = (_: T, _: boolean) => string;
export type UseTimeAgoMessages<UnitNames extends string = UseTimeAgoUnitNamesDefault> = UseTimeAgoMessagesBuiltIn & Record<UnitNames, string | UseTimeAgoFormatter<number>>;
export type UseTimeAgoReturn<Controls extends boolean = false> = Controls extends true ? {
  timeAgo: ComputedRef<string>;
} & Pausable : ComputedRef<string>;
export type UseTimeAgoUnitNamesDefault = 'second' | 'minute' | 'hour' | 'day' | 'week' | 'month' | 'year';
export type UseTimestampReturn<Controls extends boolean> = Controls extends true ? ({
  timestamp: ShallowRef<number>;
} & Pausable) : ShallowRef<number>;
export type UseTitleOptions = ConfigurableDocument & UseTitleOptionsBase;
export type UseTitleOptionsBase = {
  restoreOnUnmount?: false | ((_: string, _: string) => string | null | undefined);
} & ({
  observe?: boolean;
} | {
  titleTemplate?: MaybeRef<string> | ((_: string) => string);
});
export type UseTitleReturn = ComputedRef<string | null | undefined> | Ref<string | null | undefined>;
export type UseVirtualListOptions = UseHorizontalVirtualListOptions | UseVerticalVirtualListOptions;
export type UseWakeLockOptions = ConfigurableNavigator & ConfigurableDocument;
export type VueInstance = ComponentPublicInstance;
export type WebSocketHeartbeatMessage = string | ArrayBuffer | Blob;
export type WebSocketStatus = 'OPEN' | 'CONNECTING' | 'CLOSED';
export type WebWorkerStatus = 'PENDING' | 'SUCCESS' | 'RUNNING' | 'ERROR' | 'TIMEOUT_EXPIRED';
export type WindowEventName = keyof WindowEventMap;
// #endregion

// #region Functions
export declare function cloneFnJSON<T>(_: T): T;
export declare function computedAsync<T>(_: (_: AsyncComputedOnCancel) => T | Promise<T>, _?: undefined, _?: Ref<boolean> | AsyncComputedOptions): Ref<T | undefined>;
export declare function computedInject<T, K = any>(_: InjectionKey<T> | string, _: WritableComputedInjectOptionsWithDefault<T, K>, _: T | (() => T), _: true): ComputedRef<K>;
export declare function createFetch(_?: CreateFetchOptions): typeof useFetch;
export declare function createReusableTemplate<Bindings extends Record<string, any>, MapSlotNameToSlotProps extends ObjectLiteralWithPotentialObjectLiterals = Record<'default', undefined>>(_?: CreateReusableTemplateOptions<Bindings>): ReusableTemplatePair<Bindings, MapSlotNameToSlotProps>;
export declare function createTemplatePromise<Return, Args extends any[] = []>(_?: TemplatePromiseOptions): TemplatePromise<Return, Args>;
export declare function createUnrefFn<T extends Function>(_: T): UnrefFn<T>;
export declare function executeTransition<T>(_: Ref<T>, _: MaybeRefOrGetter<T>, _: MaybeRefOrGetter<T>, _?: TransitionOptions<T>): PromiseLike<void>;
export declare function formatTimeAgo<UnitNames extends string = UseTimeAgoUnitNamesDefault>(_: Date, _?: FormatTimeAgoOptions<UnitNames>, _?: Date | number): string;
export declare function formatTimeAgoIntl(_: Date, _?: FormatTimeAgoIntlOptions, _?: Date | number): string;
export declare function formatTimeAgoIntlParts(_: Intl.RelativeTimeFormatPart[], _?: FormatTimeAgoIntlOptions): string;
export declare function getSSRHandler<T extends keyof SSRHandlersMap>(_: T, _: SSRHandlersMap[T] | undefined): SSRHandlersMap[T] | undefined;
export declare function mapGamepadToXbox360Controller(_: Ref<Gamepad | undefined>): _$vue.ComputedRef<{
  buttons: {
    a: GamepadButton;
    b: GamepadButton;
    x: GamepadButton;
    y: GamepadButton;
  };
  bumper: {
    left: GamepadButton;
    right: GamepadButton;
  };
  triggers: {
    left: GamepadButton;
    right: GamepadButton;
  };
  stick: {
    left: {
      horizontal: number;
      vertical: number;
      button: GamepadButton;
    };
    right: {
      horizontal: number;
      vertical: number;
      button: GamepadButton;
    };
  };
  dpad: {
    up: GamepadButton;
    down: GamepadButton;
    left: GamepadButton;
    right: GamepadButton;
  };
  back: GamepadButton;
  start: GamepadButton;
} | null>;
export declare function onClickOutside<T extends OnClickOutsideOptions<true>>(_: MaybeComputedElementRef, _: OnClickOutsideHandler<T>, _: T): {
  stop: Fn;
  cancel: Fn;
  trigger: (_: Event) => void;
};
export declare function onElementRemoval(_: MaybeElementRef, _: (_: MutationRecord[]) => void, _?: OnElementRemovalOptions): Fn;
export declare function onKeyDown(_: KeyFilter, _: (_: KeyboardEvent) => void, _?: Omit<OnKeyStrokeOptions, 'eventName'>): () => void;
export declare function onKeyPressed(_: KeyFilter, _: (_: KeyboardEvent) => void, _?: Omit<OnKeyStrokeOptions, 'eventName'>): () => void;
export declare function onKeyStroke(_: (_: KeyboardEvent) => void, _?: OnKeyStrokeOptions): () => void;
export declare function onKeyUp(_: KeyFilter, _: (_: KeyboardEvent) => void, _?: Omit<OnKeyStrokeOptions, 'eventName'>): () => void;
export declare function onLongPress(_: MaybeElementRef, _: (_: PointerEvent) => void, _?: OnLongPressOptions): OnLongPressReturn;
export declare function onStartTyping(_: (_: KeyboardEvent) => void, _?: ConfigurableDocument): void;
export declare function provideSSRWidth(_: number | null, _?: App<unknown>): void;
export declare function setSSRHandler<T extends keyof SSRHandlersMap>(_: T, _: SSRHandlersMap[T]): void;
export declare function templateRef<T extends HTMLElement | SVGElement | Component | null, Keys extends string = string>(_: Keys, _?: T | null): Readonly<Ref<T>>;
export declare function transition<T>(_: Ref<T>, _: MaybeRefOrGetter<T>, _: MaybeRefOrGetter<T>, _?: TransitionOptions<T>): PromiseLike<void>;
export declare function unrefElement<T extends MaybeElement>(_: MaybeComputedElementRef<T>): UnRefElementReturn<T>;
export declare function useActiveElement<T extends HTMLElement>(_?: UseActiveElementOptions): UseActiveElementReturn<T>;
export declare function useAnimate(_: MaybeComputedElementRef, _: UseAnimateKeyframes, _?: number | UseAnimateOptions): UseAnimateReturn;
export declare function useAsyncQueue<T extends any[], S = MapQueueTask<T>>(_: S & Array<UseAsyncQueueTask<any>>, _?: UseAsyncQueueOptions): UseAsyncQueueReturn<{ [P in keyof T]: UseAsyncQueueResult<T[P]> }>;
export declare function useAsyncState<Data, Params extends any[] = any[], Shallow extends boolean = true>(_: Promise<Data> | ((..._: Params) => Promise<Data>), _: MaybeRef<Data>, _?: UseAsyncStateOptions<Shallow, Data>): UseAsyncStateReturn<Data, Params, Shallow>;
export declare function useBase64<T>(_: MaybeRefOrGetter<T[]>, _?: UseBase64ObjectOptions<T[]>): UseBase64Return;
export declare function useBattery(_?: UseBatteryOptions): UseBatteryReturn;
export declare function useBluetooth(_?: UseBluetoothOptions): UseBluetoothReturn;
export declare function useBreakpoints<K extends string>(_: Breakpoints<K>, _?: UseBreakpointsOptions): UseBreakpointReturn<K>;
export declare function useBroadcastChannel<D, P>(_: UseBroadcastChannelOptions): UseBroadcastChannelReturn<D, P>;
export declare function useBrowserLocation(_?: UseBrowserLocationOptions): UseBrowserLocationReturn;
export declare function useCached<T, D extends boolean = true>(_: Ref<T>, _?: (_: T, _: T) => boolean, _?: UseCachedOptions<D>): UseCachedReturn<T, D>;
export declare function useClipboard(_: UseClipboardOptions<MaybeRefOrGetter<string>>): UseClipboardReturn<true>;
export declare function useClipboardItems(_: UseClipboardItemsOptions<MaybeRefOrGetter<ClipboardItems>>): UseClipboardItemsReturn<true>;
export declare function useCloned<T>(_: MaybeRefOrGetter<T>, _?: UseClonedOptions): UseClonedReturn<T>;
export declare function useColorMode<T extends string = BasicColorMode>(_?: UseColorModeOptions<T>): UseColorModeReturn<T>;
export declare function useConfirmDialog<RevealData = any, ConfirmData = any, CancelData = any>(_?: ShallowRef<boolean>): UseConfirmDialogReturn<RevealData, ConfirmData, CancelData>;
export declare function useCountdown(_: MaybeRefOrGetter<number>, _?: UseCountdownOptions): UseCountdownReturn;
export declare function useCssSupports(_: MaybeRefOrGetter<string>, _?: UseCssSupportsOptions): UseCssSupportsReturn;
export declare function useCssVar(_: MaybeRefOrGetter<string | null | undefined>, _?: MaybeElementRef, _?: UseCssVarOptions): _$vue.ShallowRef<string | undefined, string | undefined>;
export declare function useCurrentElement<T extends MaybeElement = MaybeElement, R extends VueInstance = VueInstance, E extends MaybeElement = (MaybeElement extends T ? IsAny<R['$el']> extends false ? R['$el'] : T : T)>(_?: MaybeElementRef<R>): _$_vueuse_shared0.ComputedRefWithControl<E>;
export declare function useCycleList<T>(_: MaybeRefOrGetter<T[]>, _?: UseCycleListOptions<T>): UseCycleListReturn<T>;
export declare function useDark(_?: UseDarkOptions): UseDarkReturn;
export declare function useDebouncedRefHistory<Raw, Serialized = Raw>(_: Ref<Raw>, _?: Omit<UseRefHistoryOptions<Raw, Serialized>, 'eventFilter'> & {
  debounce?: MaybeRefOrGetter<number>;
}): UseRefHistoryReturn<Raw, Serialized>;
export declare function useDeviceMotion(_?: UseDeviceMotionOptions): UseDeviceMotionReturn;
export declare function useDeviceOrientation(_?: UseDeviceOrientationOptions): UseDeviceOrientationReturn;
export declare function useDevicePixelRatio(_?: UseDevicePixelRatioOptions): UseDevicePixelRatioReturn;
export declare function useDevicesList(_?: UseDevicesListOptions): UseDevicesListReturn;
export declare function useDisplayMedia(_?: UseDisplayMediaOptions): UseDisplayMediaReturn;
export declare function useDocumentVisibility(_?: UseDocumentVisibilityOptions): UseDocumentVisibilityReturn;
export declare function useDraggable(_: MaybeRefOrGetter<HTMLElement | SVGElement | null | undefined>, _?: UseDraggableOptions): UseDraggableReturn;
export declare function useDropZone(_: MaybeRefOrGetter<HTMLElement | Document | null | undefined>, _?: UseDropZoneOptions | UseDropZoneOptions['onDrop']): UseDropZoneReturn;
export declare function useElementBounding(_: MaybeComputedElementRef, _?: UseElementBoundingOptions): UseElementBoundingReturn;
export declare function useElementByPoint<M extends boolean = false>(_: UseElementByPointOptions<M>): UseElementByPointReturn<M>;
export declare function useElementHover(_: MaybeRefOrGetter<EventTarget | null | undefined>, _?: UseElementHoverOptions): ShallowRef<boolean>;
export declare function useElementSize(_: MaybeComputedElementRef, _?: ElementSize, _?: UseElementSizeOptions): UseElementSizeReturn;
export declare function useElementVisibility(_: MaybeComputedElementRef, _?: UseElementVisibilityOptions<true>): UseElementVisibilityReturn<true>;
export declare function useEventBus<T = unknown, P = any>(_: EventBusIdentifier<T>): UseEventBusReturn<T, P>;
export declare function useEventListener<EventType = Event>(_: MaybeRefOrGetter<Arrayable<EventTarget> | null | undefined>, _: MaybeRefOrGetter<Arrayable<string>>, _: MaybeRef<Arrayable<GeneralEventListener<EventType>>>, _?: MaybeRefOrGetter<boolean | AddEventListenerOptions>): Fn;
export declare function useEventSource<Events extends string[], Data = any>(_: MaybeRefOrGetter<string | URL | undefined>, _?: Events, _?: UseEventSourceOptions<Data>): UseEventSourceReturn<Events, Data>;
export declare function useEyeDropper(_?: UseEyeDropperOptions): UseEyeDropperReturn;
export declare function useFavicon(_?: MaybeRef<string | null | undefined>, _?: UseFaviconOptions): Ref<string | null | undefined>;
export declare function useFetch<T>(_: MaybeRefOrGetter<string>, _: RequestInit, _?: UseFetchOptions): UseFetchReturn<T> & PromiseLike<UseFetchReturn<T>>;
export declare function useFileDialog(_?: UseFileDialogOptions): UseFileDialogReturn;
export declare function useFileSystemAccess(_: UseFileSystemAccessOptions): UseFileSystemAccessReturn<string | ArrayBuffer | Blob>;
export declare function useFocus(_: MaybeElementRef, _?: UseFocusOptions): UseFocusReturn;
export declare function useFocusWithin(_: MaybeElementRef, _?: ConfigurableWindow): UseFocusWithinReturn;
export declare function useFps(_?: UseFpsOptions): ShallowRef<number>;
export declare function useFullscreen(_?: MaybeElementRef, _?: UseFullscreenOptions): UseFullscreenReturn;
export declare function useGamepad(_?: UseGamepadOptions): UseGamepadReturn;
export declare function useGeolocation(_?: UseGeolocationOptions): UseGeolocationReturn;
export declare function useIdle(_?: number, _?: UseIdleOptions): UseIdleReturn;
export declare function useImage<Shallow extends true>(_: MaybeRefOrGetter<UseImageOptions>, _?: UseAsyncStateOptions<Shallow>): UseImageReturn;
export declare function useInfiniteScroll<T extends InfiniteScrollElement>(_: MaybeRefOrGetter<T>, _: (_: UnwrapNestedRefs<UseScrollReturn>) => Awaitable<void>, _?: UseInfiniteScrollOptions<T>): UseInfiniteScrollReturn;
export declare function useIntersectionObserver(_: MaybeComputedElementRef | MaybeRefOrGetter<MaybeElement[]> | MaybeComputedElementRef[], _: IntersectionObserverCallback, _?: UseIntersectionObserverOptions): UseIntersectionObserverReturn;
export declare function useKeyModifier<Initial extends boolean | null>(_: KeyModifier, _?: UseModifierOptions<Initial>): UseKeyModifierReturn<Initial>;
export declare function useLocalStorage<T = unknown>(_: MaybeRefOrGetter<string>, _: MaybeRefOrGetter<null>, _?: UseStorageOptions<T>): RemovableRef<T>;
export declare function useMagicKeys<T extends boolean = false>(_?: UseMagicKeysOptions<T>): UseMagicKeysReturn<T>;
export declare function useManualRefHistory<Raw, Serialized = Raw>(_: Ref<Raw>, _?: UseManualRefHistoryOptions<Raw, Serialized>): UseManualRefHistoryReturn<Raw, Serialized>;
export declare function useMediaControls(_: MaybeRef<HTMLMediaElement | null | undefined>, _?: UseMediaControlsOptions): UseMediaControlsReturn;
export declare function useMediaQuery(_: MaybeRefOrGetter<string>, _?: ConfigurableWindow & {
  ssrWidth?: number;
}): _$vue.ComputedRef<boolean>;
export declare function useMemoize<Result, Args extends unknown[]>(_: (..._: Args) => Result, _?: UseMemoizeOptions<Result, Args>): UseMemoizeReturn<Result, Args>;
export declare function useMemory(_?: UseMemoryOptions): UseMemoryReturn;
export declare function useMounted(): _$vue.ShallowRef<boolean, boolean>;
export declare function useMouse(_?: UseMouseOptions): UseMouseReturn;
export declare function useMouseInElement(_?: MaybeElementRef, _?: MouseInElementOptions): {
  x: ShallowRef<number>;
  y: ShallowRef<number>;
  sourceType: ShallowRef<UseMouseSourceType>;
  elementX: ShallowRef<number, number>;
  elementY: ShallowRef<number, number>;
  elementPositionX: ShallowRef<number, number>;
  elementPositionY: ShallowRef<number, number>;
  elementHeight: ShallowRef<number, number>;
  elementWidth: ShallowRef<number, number>;
  isOutside: ShallowRef<boolean, boolean>;
  stop: () => void;
};
export declare function useMousePressed(_?: UseMousePressedOptions): UseMousePressedReturn;
export declare function useMutationObserver(_: MaybeComputedElementRef | MaybeComputedElementRef[] | MaybeRefOrGetter<MaybeElement[]>, _: MutationCallback, _?: UseMutationObserverOptions): UseMutationObserverReturn;
export declare function useNavigatorLanguage(_?: UseNavigatorLanguageOptions): UseNavigatorLanguageReturn;
export declare function useNetwork(_?: UseNetworkOptions): UseNetworkReturn;
export declare function useNow(_: UseNowOptions<true>): {
  now: ShallowRef<Date>;
} & Pausable;
export declare function useObjectUrl(_: MaybeRefOrGetter<Blob | MediaSource | null | undefined>): Readonly<_$vue.ShallowRef<string | undefined, string | undefined>>;
export declare function useOffsetPagination(_: UseOffsetPaginationOptions): UseOffsetPaginationReturn;
export declare function useOnline(_?: ConfigurableWindow): Readonly<_$vue.ShallowRef<boolean>>;
export declare function usePageLeave(_?: UsePageLeaveOptions): UsePageLeaveReturn;
export declare function useParallax(_: MaybeElementRef, _?: UseParallaxOptions): UseParallaxReturn;
export declare function useParentElement(_?: MaybeRefOrGetter<HTMLElement | SVGElement | null | undefined>): Readonly<ShallowRef<HTMLElement | SVGElement | null | undefined>>;
export declare function usePerformanceObserver(_: UsePerformanceObserverOptions, _: PerformanceObserverCallback): {
  isSupported: UseSupportedReturn;
  start: () => void;
  stop: () => void;
};
export declare function usePermission(_: GeneralPermissionDescriptor | GeneralPermissionDescriptor['name'], _: UsePermissionOptions<true>): UsePermissionReturnWithControls;
export declare function usePointer(_?: UsePointerOptions): UsePointerReturn;
export declare function usePointerLock(_?: MaybeElementRef, _?: UsePointerLockOptions): UsePointerLockReturn;
export declare function usePointerSwipe(_: MaybeRefOrGetter<HTMLElement | null | undefined>, _?: UsePointerSwipeOptions): UsePointerSwipeReturn;
export declare function usePreferredColorScheme(_?: ConfigurableWindow): _$vue.ComputedRef<ColorSchemeType>;
export declare function usePreferredContrast(_?: ConfigurableWindow): _$vue.ComputedRef<ContrastType>;
export declare function usePreferredDark(_?: ConfigurableWindow): _$vue.ComputedRef<boolean>;
export declare function usePreferredLanguages(_?: ConfigurableWindow): ShallowRef<readonly string[]>;
export declare function usePreferredReducedMotion(_?: ConfigurableWindow): _$vue.ComputedRef<ReducedMotionType>;
export declare function usePreferredReducedTransparency(_?: ConfigurableWindow): _$vue.ComputedRef<ReducedTransparencyType>;
export declare function usePrevious<T>(_: MaybeRefOrGetter<T>, _: T): Readonly<ShallowRef<T>>;
export declare function useRafFn(_: (_: UseRafFnCallbackArguments) => void, _?: UseRafFnOptions): Pausable;
export declare function useRefHistory<Raw, Serialized = Raw>(_: Ref<Raw>, _?: UseRefHistoryOptions<Raw, Serialized>): UseRefHistoryReturn<Raw, Serialized>;
export declare function useResizeObserver(_: MaybeComputedElementRef | MaybeComputedElementRef[] | MaybeRefOrGetter<MaybeElement[]>, _: globalThis.ResizeObserverCallback, _?: UseResizeObserverOptions): UseResizeObserverReturn;
export declare function useScreenOrientation(_?: UseScreenOrientationOptions): UseScreenOrientationReturn;
export declare function useScreenSafeArea(): UseScreenSafeAreaReturn;
export declare function useScriptTag(_: MaybeRefOrGetter<string>, _?: (_: HTMLScriptElement) => void, _?: UseScriptTagOptions): UseScriptTagReturn;
export declare function useScroll(_: MaybeRefOrGetter<HTMLElement | SVGElement | Window | Document | null | undefined>, _?: UseScrollOptions): UseScrollReturn;
export declare function useScrollLock(_: MaybeRefOrGetter<HTMLElement | SVGElement | Window | Document | null | undefined>, _?: boolean): _$vue.WritableComputedRef<boolean, boolean>;
export declare function useSessionStorage<T = unknown>(_: MaybeRefOrGetter<string>, _: MaybeRefOrGetter<null>, _?: UseStorageOptions<T>): RemovableRef<T>;
export declare function useShare(_?: MaybeRefOrGetter<UseShareOptions>, _?: ConfigurableNavigator): UseShareReturn;
export declare function useSorted<T = any>(_: MaybeRefOrGetter<T[]>, _?: UseSortedCompareFn<T>, _?: Omit<UseSortedOptions<T>, 'compareFn'>): Ref<T[]>;
export declare function useSpeechRecognition(_?: UseSpeechRecognitionOptions): UseSpeechRecognitionReturn;
export declare function useSpeechSynthesis(_: MaybeRefOrGetter<string>, _?: UseSpeechSynthesisOptions): UseSpeechSynthesisReturn;
export declare function useSSRWidth(): number | undefined;
export declare function useStepper<T extends Record<string, any>>(_: MaybeRef<T>, _?: keyof T): UseStepperReturn<Exclude<keyof T, symbol>, T, T[keyof T]>;
export declare function useStorage<T = unknown>(_: MaybeRefOrGetter<string>, _: MaybeRefOrGetter<null>, _?: StorageLike, _?: UseStorageOptions<T>): RemovableRef<T>;
export declare function useStorageAsync<T = unknown>(_: string, _: MaybeRefOrGetter<null>, _?: StorageLikeAsync, _?: UseStorageAsyncOptions<T>): RemovableRef<T> & Promise<RemovableRef<T>>;
export declare function useStyleTag(_: MaybeRef<string>, _?: UseStyleTagOptions): UseStyleTagReturn;
export declare function useSupported(_: () => unknown): UseSupportedReturn;
export declare function useSwipe(_: MaybeRefOrGetter<EventTarget | null | undefined>, _?: UseSwipeOptions): UseSwipeReturn;
export declare function useTemplateRefsList<T = Element>(): Readonly<Ref<Readonly<TemplateRefsList<T>>>>;
export declare function useTextareaAutosize(_?: UseTextareaAutosizeOptions): UseTextareaAutosizeReturn;
export declare function useTextDirection(_?: UseTextDirectionOptions): _$vue.WritableComputedRef<UseTextDirectionValue, UseTextDirectionValue>;
export declare function useTextSelection(_?: UseTextSelectionOptions): UseTextSelectionReturn;
export declare function useThrottledRefHistory<Raw, Serialized = Raw>(_: Ref<Raw>, _?: UseThrottledRefHistoryOptions<Raw, Serialized>): UseThrottledRefHistoryReturn<Raw, Serialized>;
export declare function useTimeAgo<UnitNames extends string = UseTimeAgoUnitNamesDefault>(_: MaybeRefOrGetter<Date | number | string>, _: UseTimeAgoOptions<true, UnitNames>): UseTimeAgoReturn<true>;
export declare function useTimeAgoIntl(_: MaybeRefOrGetter<Date | number | string>, _: UseTimeAgoIntlOptions<true>): UseTimeAgoReturn$1<true>;
export declare function useTimeoutPoll(_: () => Awaitable<void>, _: MaybeRefOrGetter<number>, _?: UseTimeoutFnOptions): Pausable;
export declare function useTimestamp(_: UseTimestampOptions<true>): {
  timestamp: ShallowRef<number>;
} & Pausable;
export declare function useTitle(_?: MaybeRef<string | null | undefined>, _?: UseTitleOptions): Ref<string | null | undefined>;
export declare function useTransition<T>(_: MaybeRefOrGetter<T>, _?: UseTransitionOptions<T>): ComputedRef<T>;
export declare function useUrlSearchParams<T extends Record<string, any> = UrlParams>(_?: 'history' | 'hash' | 'hash-params', _?: UseUrlSearchParamsOptions<T>): T;
export declare function useUserMedia(_?: UseUserMediaOptions): UseUserMediaReturn;
export declare function useVibrate(_?: UseVibrateOptions): UseVibrateReturn;
export declare function useVirtualList<T = any>(_: MaybeRef<readonly T[]>, _: UseVirtualListOptions): UseVirtualListReturn<T>;
export declare function useVModel<P extends object, K extends keyof P, Name extends string>(_: P, _?: K, _?: (_: Name, ..._: any[]) => void, _?: UseVModelOptions<P[K], true>): Ref<UnwrapRef<P[K]>>;
export declare function useVModels<P extends object, Name extends string>(_: P, _?: (_: Name, ..._: any[]) => void, _?: UseVModelOptions<any, false>): ToRefs<P>;
export declare function useWakeLock(_?: UseWakeLockOptions): UseWakeLockReturn;
export declare function useWebNotification(_?: UseWebNotificationOptions): UseWebNotificationReturn;
export declare function useWebSocket<Data = any>(_: MaybeRefOrGetter<string | URL | undefined>, _?: UseWebSocketOptions): UseWebSocketReturn<Data>;
export declare function useWebWorker<T = any>(_: Worker | WorkerFn): UseWebWorkerReturn<T>;
export declare function useWebWorkerFn<T extends (...fnArgs: any[]) => any>(_: T, _?: UseWebWorkerOptions): UseWebWorkerFnReturn<T>;
export declare function useWindowFocus(_?: ConfigurableWindow): ShallowRef<boolean>;
export declare function useWindowScroll(_?: UseWindowScrollOptions): UseWindowScrollReturn;
export declare function useWindowSize(_?: UseWindowSizeOptions): UseWindowSizeReturn;
// #endregion

// #region Variables
export declare const asyncComputed: typeof computedAsync;
export declare const breakpointsAntDesign: {
  xs: number;
  sm: number;
  md: number;
  lg: number;
  xl: number;
  xxl: number;
};
export declare const breakpointsBootstrapV5: {
  xs: number;
  sm: number;
  md: number;
  lg: number;
  xl: number;
  xxl: number;
};
export declare const breakpointsElement: {
  xs: number;
  sm: number;
  md: number;
  lg: number;
  xl: number;
};
export declare const breakpointsMasterCss: {
  '3xs': number;
  '2xs': number;
  xs: number;
  sm: number;
  md: number;
  lg: number;
  xl: number;
  '2xl': number;
  '3xl': number;
  '4xl': number;
};
export declare const breakpointsPrimeFlex: {
  sm: number;
  md: number;
  lg: number;
  xl: number;
};
export declare const breakpointsQuasar: {
  xs: number;
  sm: number;
  md: number;
  lg: number;
  xl: number;
};
export declare const breakpointsSematic: {
  mobileS: number;
  mobileM: number;
  mobileL: number;
  tablet: number;
  laptop: number;
  laptopL: number;
  desktop4K: number;
};
export declare const breakpointsTailwind: {
  sm: number;
  md: number;
  lg: number;
  xl: number;
  '2xl': number;
};
export declare const breakpointsVuetify: {
  xs: number;
  sm: number;
  md: number;
  lg: number;
  xl: number;
};
export declare const breakpointsVuetifyV2: {
  xs: number;
  sm: number;
  md: number;
  lg: number;
  xl: number;
};
export declare const breakpointsVuetifyV3: {
  xs: number;
  sm: number;
  md: number;
  lg: number;
  xl: number;
  xxl: number;
};
export declare const customStorageEventName: string;
export declare const defaultDocument: Document | undefined;
export declare const defaultLocation: Location | undefined;
export declare const DefaultMagicKeysAliasMap: Readonly<Record<string, string>>;
export declare const defaultNavigator: Navigator | undefined;
export declare const defaultWindow: (Window & typeof globalThis) | undefined;
export declare const StorageSerializers: Record<'boolean' | 'object' | 'number' | 'any' | 'string' | 'map' | 'set' | 'date', Serializer<any>>;
export declare const TransitionPresets: Record<keyof typeof _TransitionPresets, CubicBezierPoints> & {
  linear: EasingFunction;
};
// #endregion

// #region Re-exports
export * from "@vueuse/shared";
// #endregion