/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useSortable/component` */
// Interfaces
export interface UseSortableProps extends RenderableComponent {
  modelValue: any[];
  options?: UseSortableOptions;
}

// Variables
export declare const UseSortable: vue.DefineSetupFnComponent<UseSortableProps, Record<string, never>, SlotsType<UseSortableSlots>, UseSortableProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, vue.PublicProps>;