/**
 * Generated by tsnapi — public API snapshot of `@vueuse/integrations/useSortable/component`
 */
// #region Interfaces
export interface UseSortableProps extends RenderableComponent {
  modelValue: any[];
  options?: UseSortableOptions;
}
// #endregion

// #region Variables
export declare const UseSortable: _$vue.DefineSetupFnComponent<UseSortableProps, Record<string, never>, SlotsType<UseSortableSlots>, UseSortableProps & {
  [x: `on${Capitalize<string>}`]: ((...args: unknown[]) => any) | undefined;
}, _$vue.PublicProps>;
// #endregion