name: Lint

on:
  push:
    branches:
      - main
      - dev
      - next

  pull_request:
    branches:
      - main
      - dev
      - next

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - run: pnpm install

      - name: Lint
        run: pnpm run lint
