/**
 * Generated by tsnapi — public API snapshot of `@vueuse/electron`
 */
// #region Interfaces
export interface UseIpcRendererReturn {
  on: (_: string, _: IpcRendererListener) => IpcRenderer;
  once: (_: string, _: (_: IpcRendererEvent, ..._: any[]) => void) => IpcRenderer;
  removeListener: (_: string, _: (..._: any[]) => void) => IpcRenderer;
  removeAllListeners: (_: string) => IpcRenderer;
  send: (_: string, ..._: any[]) => void;
  invoke: <T>(_: string, ..._: any[]) => ShallowRef<T | null>;
  sendSync: <T>(_: string, ..._: any[]) => ShallowRef<T | null>;
  postMessage: (_: string, _: any, _?: MessagePort[]) => void;
  sendTo: (_: number, _: string, ..._: any[]) => void;
  sendToHost: (_: string, ..._: any[]) => void;
}
// #endregion

// #region Functions
export declare function useIpcRenderer(_?: IpcRenderer): UseIpcRendererReturn;
export declare function useIpcRendererInvoke<T>(_: string, ..._: any[]): ShallowRef<T | null>;
export declare function useIpcRendererOn(_: string, _: IpcRendererListener): IpcRenderer;
export declare function useZoomFactor(): Ref<number>;
export declare function useZoomLevel(): Ref<number>;
// #endregion